### ISSUE TITLE
Using a folder as a buildpack to build static sites

### ISSUE THREAD

**Issue by 0x4139** [buildpacks/pack#1006]
### Summary

I am trying to use a simple static buildpack. I've tried multiple static buildpacks with the following buildpack configuration
```toml
api = "0.2"
[buildpack]
name = "Static HTML"
id="static"
version="1"
[[stacks]]
  id = "heroku-18"
  build-image="heroku/pack:18-build"
  run-image="heroku/pack:18"
```
---
I am running it using `pack build test --builder heroku/buildpacks:18 --buildpack heroku-buildpack-static-master --clear-cache --path static`
when in detect phase i use the following script
```bash
#!/usr/bin/env bash
# bin/detect <build-dir>
echo $@
ls -all /platform
build_dir=$1
echo 'Detecting static site'
ls -all
echo $build_dir
if [ ! -f "$build_dir/static.json" ]; then
    exit 1
fi

echo 'Static HTML'
exit 0
```
I can't figure it out what's with the `/platform` folder and why it doesn't detect my files to pass.
The platform folder comes from a parameter variable called $build_dir i saw this variable across many buildpacks.
my output is:
```bash
18: Pulling from heroku/buildpacks
Digest: sha256:bd8d53d438e08b81ea81e1d9bd0b170818ab3bc8d57d137f239ce3ff221d62f1
Status: Image is up to date for heroku/buildpacks:18
18: Pulling from heroku/pack
Digest: sha256:6ecf58a5e6adc43da74460188e2816749a189aac691bc831094e0ccb945edfaf
Status: Image is up to date for heroku/pack:18
===> DETECTING
======== Output: static@1 ========
/platform /tmp/plan.029371703/plan.toml
total 12
drwxr-xr-x 1 root root 4096 Jan  1  1980 .
drwxr-xr-x 1 root root 4096 Jan  5 19:21 ..
drwxr-xr-x 1 root root 4096 Jan  1  1980 env
Detecting static site
total 8
drwxr-xr-x 2 heroku heroku 4096 Jan  5 19:21 .
drwxr-xr-x 1 root   root   4096 Jan  5 19:21 ..
-rw-r--r-- 1 heroku heroku    0 Jan  5 18:58 index.html
-rw-r--r-- 1 heroku heroku    0 Jan  5 19:21 static.json
/platform
err:  static@1 (1)
ERROR: No buildpack groups passed detection.
ERROR: failed to detect: buildpack(s) failed with err
ERROR: failed to build: executing lifecycle: failed with status code: 101
```

Any ideas what i am doing wrong?

**Comment by jromero** [comment]
GIST: Based on the [spec](https://github.com/buildpacks/spec/blob/main/buildpack.md#detection), what you want is to look for `static.json` within the current working directory (aka `$PWD`).

![image](https://user-images.githubusercontent.com/475559/103691837-7ac13500-4f5c-11eb-820f-4dc158e0d7be.png)

The `platform` directory is intended for "platforms" such as `pack`, heroku, Google, etc. to provide additional configuration and extensions. It's not necessarily intended for buildpacks to use unless they are targeting some very platform specific functionality. The app source is in the current working directory.

**Comment by 0x4139** [comment]
Thank you @jromero for the answer
It seems that the buildpack that i am using is not compatible with the V2 of CNB and it needs shimming, specific for this case `pack build -B heroku/buildpacks:18 --buildpack https://cnb-shim.herokuapp.com/v1/heroku-community/static yourimgname`

**Comment by jromero** [comment]
Great, glad you found what you needed. If there is anything else, it seems like you know where to find it. 😁
