### ISSUE TITLE
Support Stack Buildpacks

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#1021]
### Additional context
Stack Buildpacks were defined in [RFC 0069](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md) (the discussion is in this PR: https://github.com/buildpacks/rfcs/pull/111). 

This work is blocked on https://github.com/buildpacks/lifecycle/issues/501

**Comment by jjbustamante** [comment]
No relevant anymore, closing it. We implemented the extensions approach
