### ISSUE TITLE
Relative paths in project.toml should be relative to the project not the working dir

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#1031]
### Summary
When a buildpack uri in `project.toml` contains a relative path `pack` treats this path as relative to the current working directory. Instead it should be relative to the directory containing `project.toml`.

---

##### Steps

In the root dir of https://github.com/buildpacks/samples
```
pack build samples/bash-script -p apps/bash-script --builder cnbs/sample-builder:bionic
```

##### Current behavior
```
ERROR: failed to build: extracting from file:///Users/ekcasey/workspace/samples/bash-script-buildpack: inspecting buildpack blob: read blob at path '/Users/ekcasey/workspace/samples/bash-script-buildpack': stat /Users/ekcasey/workspace/samples/bash-script-buildpack: no such file or directory
```

##### Expected behavior
Given the `project.toml` file at the root of the app containing
```
[[build.buildpacks]]
uri = "bash-script-buildpack/"
```
I expected `pack` to look for the `bash-script-buildpack` directory within the app dir.

---

##### pack info

```
pack report
Pack:
  Version:  0.16.0+git-e0f6c50.build-1898
  OS/Arch:  darwin/amd64
  ```

##### docker info
N/A

**Comment by dfreilich** [comment]
Closed in #1044
