### ISSUE TITLE
Add buildpack homepages to inspect-image output

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#1033]
### Description
As of Platform API 0.5 the [`io.buildpacks.build.metadata`](https://github.com/buildpacks/spec/blob/main/platform.md#iobuildpacksbuildmetadata-json) label on app images now contains buildpack homepages. It would be nice if `pack inspect-image` displayed this information.

### Proposed solution
`pack inspect-images` should include a `HOMEPAGE` column in the `Buildpacks` table, similar to the current output from `pack inspect-builder`.

Instead of:
```
Buildpacks:
  ID                                         VERSION
  paketo-buildpacks/ca-certificates          1.0.1
  paketo-buildpacks/bellsoft-liberica        6.1.0
  paketo-buildpacks/executable-jar           3.1.3
  paketo-buildpacks/spring-boot              3.5.0
```
print:
```
Buildpacks:
  ID                                                  VERSION        HOMEPAGE
  paketo-buildpacks/ca-certificates                   1.0.1          https://github.com/paketo-buildpacks/ca-certificates
  paketo-buildpacks/bellsoft-liberica                 6.1.0          https://github.com/paketo-buildpacks/bellsoft-liberica
  paketo-buildpacks/executable-jar                    3.1.3          https://github.com/paketo-buildpacks/executable-jar
  paketo-buildpacks/spring-boot                       3.5.0          https://github.com/paketo-buildpacks/spring-boot
```

### Describe alternatives you've considered
Do nothing?

### Additional context
- [x] This feature should be documented somewhere

**Comment by dfreilich** [comment]
Would there be any ask to display the new added fields for buildpacks? (https://github.com/buildpacks/pack/pull/1022)

**Comment by ekcasey** [comment]
@dfreilich Those additional fields aren't available on the app image yet and we don't yet have a plan to expose them (we may well in the future). I do think those fields should be displayed for `inspect-buildpack` and `inspect-builder` though.

**Comment by aemengo** [comment]
PR: https://github.com/buildpacks/pack/pull/1092
