### ISSUE TITLE
Error while pushing kpack build image to harbor

### ISSUE THREAD

**Issue by kvsuresh14** [buildpacks/pack#1045]
I am getting an error while pushing kpack image to harbor.
Error:images.kpack.io "g54cft7vu.....
78htf " is already exists.

**Comment by dfreilich** [comment]
Hey @kvsuresh14 ! `kpack` and `harbor` are separate projects. kpack, while an implementation of the Cloud Native Buildpacks Platform specification, isn't maintained by the Buildpacks organization. It looks like you've already opened an issue in the appropriate repo (https://github.com/vmware-tanzu/kpack-cli/issues/151) and https://github.com/vmware-tanzu/kpack-cli/issues/74#issuecomment-769700398, so I'll close this in favor of those.
