### ISSUE TITLE
Standardize Cache Flag options

### ISSUE THREAD

**Issue by dwillist** [buildpacks/pack#1077]
### Description
We have received a couple different requests for functionality around the flexibility of the `.build` cache. These have all been implemented by adding additional flags to the `pack` cli. and as a result we have `--cache-image` and `--cache-name? (pending)` to specify the build cache type & name. 

It feels like we might want consolidate this behavior to use more descriptive flags to make these combinations both easier to understand & extensible.

### Proposed solution
Flags can be specified in a way similar to the `--mount` option for docker.
Possible Flags:

`pack build ... --cache 'src_type=volume,src=<VOLUME-NAME>,dst_type=remote_image,dst=<IMAGE-PATH>`

### Additional context
- [x] This feature should be documented somewhere

Related issues:
#1024 
#665 
#317

---

## Update (2022-06-15)

Since this issue was opened an [RFC](https://github.com/buildpacks/rfcs/blob/main/text/0091-pack-cache-options.md) was created and approved.

The following are tasks that need to be implemented in order to consider this issue resolved:

- [x] https://github.com/buildpacks/pack/issues/1458
- [x] https://github.com/buildpacks/pack/issues/1457
- [x] #1471
- [x] #1472
- [x] #1473
- [x] #1474
- [x] #1475

**Comment by ekcasey** [comment]
@dwillist  Not sure I am following this. How can the cache src be a volume but the cache destination be a remote image?

**Comment by dwillist** [comment]
@ekcasey I would expect using the `--cache-dir` argument for the `analyzer` and `restorer` would allow pulling info from a mounted cache volume, then using a `--cache-image` flag for the exporter would cause the lifecycle to push the cache as a remote image. Am I missing something?

**Comment by ekcasey** [comment]
@dwillist ahhh gotcha. I hadn't thought about that use case (migrating caches) but I think it would work fine from a lifecycle perspective if you use the individual phase. With `creator` (trusted builders), this would not work because we don't accept different inputs for source cache and destination cache. `creator` would need to be changed to support this.

If we did something like this I think it would be important to have good defaults. As a user `--cache-volume my-cache` feels easier (to remember, type, autocomplete) than `--cache 'src_type=volume,src=my-cache,dst_type=volume,dst=my-cache` but if `--cache my-volume` worked (because we default `src_type` to volume and default the `dst` and `dst_type` to match `src` and `src_type` etc.) the proposed optionality would be great.

**Comment by jromero** [comment]
An additional use case for this feature with Bitbucket (via [slack](https://buildpacks.slack.com/archives/C94UJCNV6/p1616479368022600)):

![image](https://user-images.githubusercontent.com/475559/112330242-dced2480-8c85-11eb-8bfc-9182f89f29a9.png)

![image](https://user-images.githubusercontent.com/475559/112330337-f0988b00-8c85-11eb-8d34-6e2d6dad54cb.png)

Links:

- https://community.atlassian.com/t5/Bitbucket-discussions/Using-CNCF-Buildpacks-on-Bitbucket-Pipelines/td-p/1516690
- https://github.com/buildpacks/pack/issues/665

**Comment by jromero** [comment]
@dwillist I've started an RFC. Would love to get your contributions in there.

https://github.com/buildpacks/rfcs/pull/149

**Comment by jromero** [comment]
This is ready to implement as per [RFC#0091](https://github.com/buildpacks/rfcs/blob/main/text/0091-pack-cache-options.md)

**Comment by Nivedita-coder** [comment]
Hi @jromero @dwillist,  I want to contribute to this project for GSoC 2022, can you guide me on how can I get started with this project? Thanks!

**Comment by jromero** [comment]
Setting status to **blocked**, since this issue was submitted to Google Summer of Code. This is scheduled to be worked on by a mentee.

**Comment by jromero** [comment]
Hi @Nivedita-coder 👋 ,

Nice to see you here. I'd be more than happy to show you around.

If you can, could you reach out to me over in the [CNCF slack](https://slack.cncf.io/)? My username there is `@jromero`. Also, we have [`#buildpacks-mentoring`](https://cloud-native.slack.com/archives/C032LNSKPP1) channel if you have more general questions regarding Google Summer of Code.
