### ISSUE TITLE
[RFC 0075] Move analyze phase before detect 

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#1078]
### Description

Implement https://github.com/buildpacks/rfcs/pull/135 for untrusted builder builds

### Additional context
- [x] This feature should be documented somewhere
https://github.com/buildpacks/spec/issues/194
https://github.com/buildpacks/lifecycle/issues/530

**Comment by dwillist** [comment]
Need to wait for the associated lifecycle changes to land: buildpacks/lifecycle#505 .
This will probably require some coordination around how to handle both new and old lifecycle versions.

**Comment by micahyoung** [comment]
For WCOW, this will likely require selectively moving [`EnsureVolumeAccess`](https://github.com/buildpacks/pack/blob/0c84b4ae7a30a22fec257d539dcd857584bb6246/internal/build/container_ops.go) which currently runs in [`Detect`](https://github.com/buildpacks/pack/blob/48440b923121dba2253f4e66b42f2519c286f81e/internal/build/lifecycle_execution.go#L233) to run somewhere in `Analyze`, depending on the API version

**Comment by jromero** [comment]
We should be able to simply use the platform API version to determine the execution order.

- Migration and features enabled by this are separate to this issue.

**Comment by jjbustamante** [comment]
This was already done!! closing it
