### ISSUE TITLE
[ CLI autocompletion] unable to parse docker host `localhost:2375`

### ISSUE THREAD

**Issue by abdennour** [buildpacks/pack#1090]
### Summary

CLI autocompletion cannot be enabled

---

##### Steps

1. Having zsh
2. Having DOCKER_HOST env var set to `localhost:2375`
3. Having pack installed `(curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.17.0/pack-v0.17.0-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)`
4. Running: . $(pack completion --shell zsh)
5. Results to this error: 
```
ERROR: creating docker client: unable to parse docker host `localhost:2375`
.: not enough arguments
```

##### Current behavior

pack does not enable auto completion

##### Expected behavior

pack must consider "tcp://" as the default protocol if the DOCKER_HOST env var is not empty.

---

##### pack info
```
0.17.0+git-d9cb4e7.build-2045
```

##### docker info

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:11:26 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dwillist** [comment]
Looks like this is the default behavior implemented by docker [(here is their parsing method)](https://github.com/docker/cli/blob/70a00157f161b109be77cd4f30ce0662bfe8cc32/opts/hosts.go#L71). @abdennour any interest in contributing this fix? Should be adding similar logic [here in our codebase](https://github.com/buildpacks/pack/blob/0c84b4ae7a30a22fec257d539dcd857584bb6246/internal/build/phase_config_provider.go#L139).

**Comment by abdennour** [comment]
I found that `DOCKER_HOST=localhost:2375` . 
I replaced it by `DOCKER_HOST=tcp://localhost:2375` , and now, it's working
