### ISSUE TITLE
Detect the right version of platform api to use 

### ISSUE THREAD

**Issue by samj1912** [buildpacks/pack#1091]
### Description

With the PR #1088 we allow users to provide a custom lifecycle image name. Previously we used to have pack select the appropriate lifecycle version based on the version it supported and the version used by the builder.

With this change we need to figure out the right platform version which is compatible with the lifecycle, the builder and pack 

See @ekcasey 's comment at https://github.com/buildpacks/pack/pull/1088#issuecomment-785178471

### Proposed solution

pack should pick the highest platform version compatible with the lifecycle image, the builder and pack. 

### Additional context
- [ ] This feature should be documented somewhere

**Comment by natalieparellano** [comment]
The latest buildpacksio/lifecycle has the following metadata:

```
"Labels": {
        "io.buildpacks.builder.metadata": "{\"lifecycle\":{\"version\":\"0.10.2\"},\"api\":{\"buildpack\":\"0.2\",\"platform\":\"0.3\"}}",
        "io.buildpacks.lifecycle.apis": "{\"buildpack\":{\"deprecated\":[],\"supported\":[\"0.2\",\"0.3\",\"0.4\",\"0.5\"]},\"platform\":{\"deprecated\":[],\"supported\":[\"0.3\",\"0.4\",\"0.5\"]}}",
        "io.buildpacks.lifecycle.version": "0.10.2"
      }
```

`io.buildpacks.builder.metadata` is the "legacy label" and `io.buildpacks.lifecycle.apis` is updated with the latest supported apis. However it looks like `pack` doesn't currently know or care about `io.buildpacks.lifecycle.apis`.

**Comment by jromero** [comment]
@natalieparellano It looks like `io.buildpacks.lifecycle.apis` is up and coming from the [builder 0.1 spec](https://github.com/buildpacks/spec/blob/extensions/builder/0.1/extensions/builder.md#iobuildpackslifecycleapis-json) release so we don't technically have it yet. Good call out though.

Until that is released and more public builders move to that spec, we'll need to rely on `io.buildpacks.builder.metadata`

**Comment by jromero** [comment]
@natalieparellano  Is there a contract/spec provided for lifecycle images? I just now realize that you were talking about the lifecycle image which is interesting because AFAIK, that isn't spec'd making it more difficult for us to set expectations on the lifecycle image provided to pack.

**Comment by natalieparellano** [comment]
@jromero apologies for the slow reply. AFAIK lifecycle image isn't spec'd.

**Comment by jromero** [comment]
Given that neither set of labels and supported APIs were spec'd, I'm comfortable with moving to using the new label. Additionally, for context we are specing this out via the [distribution spec](https://github.com/buildpacks/spec/pull/264/files).

# Proposed Solution

1. Get the supported versions  for the **builder** image from the label `io.buildpacks.builder.metadata` (property: `.lifecycle.apis.platform.supported`).
1. Get the supported versions  for the **lifecycle** image from the label `io.buildpacks.lifecycle.apis` (property: `.platform.supported`).
1. Intersect builder, lifecycle, and [pack supported](https://github.com/buildpacks/pack/blob/a0eac323493902a172bc0eb48c7772762d88ccca/internal/build/lifecycle_executor.go#L22-L29) platform APIs.
    * Exception: if no Platform APIs intersect, error with message.
 1. The highest intersected Platform API version should be used by `pack`.

# Acceptance Criteria

```Gherkin
Given lifecycle image "my/lifecycle" has the following values in label "io.buildpacks.lifecycle.apis", property ".platform.supported":
"""
[
  "0.3",
  "0.4",
  "0.5",
  "0.6",
  "0.7",
  "0.8"
]
"""
And builder image "my/builder" has the following values in label "io.buildpacks.builder.metadata", property ".lifecycle.apis.platform.supported":
"""
[
  "0.3",
  "0.4",
  "0.5",
  "0.6"
]
"""
And pack supports the following Platform API version:
"""
0.4
0.5
"""
When I run "pack build" with builder "my/builder" and lifecycle "my/lifecycle"
Then pack should use Platform API 0.5 when interacting with the lifecycle

```

**Comment by basit9958** [comment]
@jromero  I Want to try to solve this can you please assign this to me and point out some resources to solve this issue

**Comment by jromero** [comment]
> @jromero  I Want to try to solve this can you please assign this to me and point out some resources to solve this issue
> 

Hi @basit9958 ,

Thank you for volunteering. What additional information do you think would be beneficial to better understanding and resolving this issue?

For what it's worth, we have a [Slack](https://slack.buildpacks.io) channel `#pack-cli` that you can join and ask more specific questions as you run into them.

Lastly, keep in mind that a lot of contributors (myself included) are out this week for the holidays but happy to help in passing.

**Comment by basit9958** [comment]
Additional info such as some other PR that I can refer to. I am really new to this so anything would be of great help. 
Also Happy Holidays

**Comment by basit9958** [comment]
@jromero can you give me some pointers to know what to implement and where.

**Comment by jromero** [comment]
Hi @basit9958, wanted to check in since we last chatted on Slack. Is there anything we can do to further assist?

**Comment by oovk** [comment]
Hi @jromero, Can you point me to the related code part and a bit of explanation about the issue will be really helpful.
