### ISSUE TITLE
RFC: Support `build.pre.buildpacks` `build.post.buildpacks` in `project.toml`

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#1100]
### Description

Based on the [RFC](https://github.com/buildpacks/rfcs/pull/129), we will want to support the additional properties in `project.toml`:

```
[build.pre]

  [[build.pre.buildpacks]]
  id = "<buildpack ID>"
  version = "<string>"
  uri = "<string>"

[build.post]

  [[build.post.buildpacks]]
  id = "<buildpack ID>"
  version = "<string>"
  uri = "<string>"
```

### Proposed solution

See [RFC "How it works"](https://github.com/buildpacks/rfcs/blob/group-additions/text/0000-group-additions.md#how-it-works).

### Additional context
- RFC PR: https://github.com/buildpacks/rfcs/pull/129
- Blocked by https://github.com/buildpacks/spec/issues/195

**Comment by jjbustamante** [comment]
This issue probably requires a small effort because this [PR](https://github.com/buildpacks/pack/pull/1621) from Joe already added support on flags, we just need to add it into the project.toml

**Comment by natalieparellano** [comment]
Actually looking at https://github.com/buildpacks/pack/pull/1621/files#diff-03220a2f3a516ece374582fcc687eb7c47a3c6e2dcd11e0f5a117c5a9c0decc6R1276 more closely, it appears this is already implemented. I'm going to close this issue
