### ISSUE TITLE
reported version is 0.0.0

### ISSUE THREAD

**Issue by adrianliechti** [buildpacks/pack#1107]
pack does not return the correct version

$ pack version
0.0.0+git-d9cb4e7.build-2045

this seems to happen on builds downloaded with brew on mac; and github releases on both mac and windows.

it would help us a lot to get the correct version (e.g. 0.17.0, so we can auto update the binaries

thanks a 1000

**Comment by dwillist** [comment]
Should be fixed by #1112

**Comment by adrianliechti** [comment]
thanks a 1000!
amazing responsiveness
