### ISSUE TITLE
unable to release pack `0.18.0` for `i386` on ubuntu bionic

### ISSUE THREAD

**Issue by dwillist** [buildpacks/pack#1117]
### Summary
We are currently unable to release the above version of pack for bionic i386 architectures due to the difficulties building the golang dependency, see https://github.com/longsleep/golang-deb/issues/5

There should be a workaround possible if we build a golang deb dependency ourselves & use it. Though this is a quite complicated. See https://github.com/longsleep/golang-deb for a possible template.

**Comment by jromero** [comment]
May want to look into other ecosystem tooling as to how they are solving this limitation or if they are using an alternative method to building go binaries on x86 for Ubuntu.

**Comment by dfreilich** [comment]
I wonder whether switching to goreleaser would simplify our whole release process. I'm not sure whether it works for x86 for Ubuntu, though.
