### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by abdennour** [buildpacks/pack#1120]
### Description
buildpack solves reducing build files for building **app container images**.. but still there is no way to declaratively define **container runtime**

### Proposed solution

`buildpack-compose -f docker-compose.yaml up -d` should build the images then run the container

### Describe alternatives you've considered
N/A

**Comment by samj1912** [comment]
There's a separate/related ticket at https://github.com/buildpacks/pack/issues/768

If we have a buildkit frontend - buildpacks could just "work" out of the box with docker.

**Comment by jromero** [comment]
From a [slack conversation](https://buildpacks.slack.com/archives/CJ6B92ZSB/p1617105466016700):

> buildpacks have certainly focused on the image generation aspect of things. FWIW, there was a `pack run` command at some point in time but we found very quickly that exposing all the functionality that `docke`r run provides is very hard to maintain. Since then we've tried to stay away from the runtime aspect of images.
>
> That said, if we are able to integrate "properly" with the docker CLI (via BuildKit). `docker-compose` could essentially "just work". 

See https://github.com/buildpacks/pack/issues/768

**Comment by samj1912** [comment]
Alternatively an easy way out that I use right now if put as many arguments as possible in `project.toml` to configure `pack` and run a `pack build <image-name>`  and use the output image in docker-compose instead of building it through docker-compose. You can tie the two together in a make command or some higher level wrapper.

**Comment by jjbustamante** [comment]
Closing this issue in favor of #768 

As @samj1912 and @jromero mentioned, `we've tried to stay away from the runtime aspect of images`
