### ISSUE TITLE
Need support in buildpacks to change the location where all the source code gets copied.

### ISSUE THREAD

**Issue by jattgurpreet** [buildpacks/pack#1121]
**On Page:** [Getting Started](https://buildpacks.io/docs/)

As of now by default , it seems there is no way to specify where in docker container soource code should be copied, default is  '/workspace' Can we please get a feature where we can override this as not everybody wants to maintain there code in /workspace.
https://github.com/buildpacks/pack/blob/aa49ae6d845f40bd576cc488a3105845e9e77506/internal/build/mount_paths.go#L36

**Comment by jasonschroeder-sfdc** [comment]
One example of "not everybody wants to maintain code in /workspace":
TektonCD always volume-mounts /workspace, so builder images built with buildpacks are not compatible with TektonCD.

https://tekton.dev/docs/pipelines/tasks/#reserved-directories
>There are several directories that all Tasks run by Tekton will treat as special
>
>- `/workspace` - This directory is where resources and workspaces are mounted. Paths to these are available to Task authors via variable substitution

**Comment by banka01** [comment]
Can you please know how to use it. i tried with pack build  --workspace <>. But the detect steps fails . if we dont provide the --workspace, current directory is considered as source code and copied to "/workspace". How can we ensure that app code is copied to other directory.

**Comment by natalieparellano** [comment]
> But the detect steps fails
What does detect fail with? It might be an issue with the buildpack...
