### ISSUE TITLE
RFC 140: Project Descriptor Domains

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#1127]
### Description

Implement https://github.com/buildpacks/rfcs/pull/140

### Additional context
- [ ] This feature should be documented somewhere

**Comment by YousefHaggyHeroku** [comment]
I'm working on this issue 👍

**Comment by samj1912** [comment]
@buildpacks/platform-maintainers can we have more details on this issue on how we expect b/w compat with existing project descriptor files? Since this is a breaking change for app developers, this will impact a lot of users who may not be aware of CB internals.

**Comment by YousefHaggyHeroku** [comment]
My thoughts were to do something like having a `ParseV1Descriptor` and `ParseV2Descriptor` in the pack code. If the "_" top level key exists, `ParseV2Descriptor`, else `ParseV1Descriptor`.  Curious to hear other thoughts
