### ISSUE TITLE
Would you expect --publish && --cache-image to work for a new image to a registry?

### ISSUE THREAD

**Issue by genevieve** [buildpacks/pack#1131]
### Summary

I did something probably unusual but got a weird error and thought I'd ask about the behavior here.

I am testing performance times using `--publish` && `--cache-image` on rebuilds for a given application's code (unchanging between rebuilds.)

I ran `pack build APP_NAME:TAG --publish --cache-image APP_NAME:TAG` so that it would publish the image _for the first time_ to a public registry. I realize now that's weird and you would publish first, then on subsequent runs would attach the `--cache-image`. Anywho, I got a strange error and thought I'd share in case there could be improvement in the framing of it.

##### Steps

1. delete the image that's there
2. `pack build doxgen/leftovers:latest --publish --cache-image doxgen/leftovers:latest`

##### Current behavior

```
2021/04/09 17:05:48.083472 Saving doxgen/leftovers:latest...
2021/04/09 17:06:08.605000 *** Images (sha256:3b13f11bf3314fc20398de572e21b4f47d34c6508367a500ae46d8f3ff1669ee):
      doxgen/leftovers:latest - Put "https://index.docker.io/v2/doxgen/leftovers/blobs/uploads/...": EOF

*** Digest: sha256:3b13f11bf3314fc20398de572e21b4f47d34c6508367a500ae46d8f3ff1669ee

*** Manifest Size: 2045
2021/04/09 17:06:08.614047 ERROR: failed to export: failed to write image to the following tags: [doxgen/leftovers:latest: Put "https://index.docker.io/v2/doxgen/leftovers/blobs/uploads/3...": EOF]
2021/04/09 17:06:09.790338 ERROR: failed to build: executing lifecycle: failed with status code: 246
```

##### Expected behavior

Probably an unusual mistake but perhaps a more clear of what's wrong? Or just _skipping_ the use of the `cache-image` work if it's not available?

---

##### pack info

```
Pack:
  Version:  0.18.0+git-e00ee4a.build-2328
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.10.2

Supported Platform APIs:  0.3, 0.4
```

##### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 20.10.5
```

**Comment by genevieve** [comment]
I didn't add those labels above so is that an automated thing? ^ 🤔

**Comment by ekcasey** [comment]
@genevieve Are you seeing this consistently on every first build? If not, I would guess you are running into [this flake](https://github.com/buildpacks/lifecycle/issues/414) which should be mitigated in lifecycle `0.11.x`.

> I didn't add those labels above so is that an automated thing? ^ 🤔
which labels?

**Comment by genevieve** [comment]
The issue labels, I realized after, are automated but look like I set them.
<img width="658" alt="Screen Shot 2021-04-13 at 9 07 49 AM" src="https://user-images.githubusercontent.com/12158641/114584628-b93f4d80-9c37-11eb-9f52-adeee33fe758.png">

**Comment by genevieve** [comment]
I haven't seen the issue again so perhaps it was a flake. The lifecycle version used is `0.11.1`.

**Comment by natalieparellano** [comment]
Ah... we added retries on EOF errors for image fetches but not image pushes. This is something we could explore.
