### ISSUE TITLE
Provide project source metadata from local git information

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#1137]
### Description
As a buildpacks user, I'd like to have the source and version information of my project embedded as metadata in the final app image.

### Proposed solution

Based on the spec, we should be able to provide `<layers>/project-metadata.toml` in [this format](https://github.com/buildpacks/spec/blob/platform/0.6/platform.md#project-metadatatoml-toml) which would be translated into the [`io.buildpacks.project.metadata` label](https://github.com/buildpacks/spec/blob/platform/0.6/platform.md#iobuildpacksprojectmetadata-json) on the image.

This issue should be scoped to local git information. 

##### General case

```gherkin
Given I clone a project from git@github.com:buildpacks/pack.git
And `git rev-parse HEAD` returns "8348484564e6aa0699de0ee78c258e88240eb0b5"
And `git describe --tags --always` returns "v0.18.1-2-g83484845"
And `git branch --show-current` returns "main"
And `git remote -v | grep "fetch"` returns:
    "origin	git@github.com:buildpacks/pack.git (fetch)"
And I run `pack build my-app`
When I run the following command `docker inspect my-app | jq -r '.[0].Config.Labels["io.buildpacks.project.metadata"] | fromjson'`
Then I should see:
{
  "type": "git",
  "version": { "commit": "8348484564e6aa0699de0ee78c258e88240eb0b5", "describe": "v0.18.1-2-g83484845"},
  "metadata": {
    "refs": ["main"],
    "url": "git@github.com:buildpacks/pack.git"
  }
}
```

##### At a tag(s)

```gherkin
Given I clone a project from git@github.com:buildpacks/pack.git
And `git rev-parse HEAD` returns "8348484564e6aa0699de0ee78c258e88240eb0b5"
And `git describe --tags --always` returns "v0.18.1"
And `git branch --show-current` returns "main"
And `git tag --points-at HEAD` returns:
  v0.18.1
  v0.18.1-rc2
And `git remote -v | grep "fetch"` returns:
    "origin	git@github.com:buildpacks/pack.git (fetch)"
And I run `pack build my-app`
When I run the following command `docker inspect my-app | jq -r '.[0].Config.Labels["io.buildpacks.project.metadata"] | fromjson'`
Then I should see:
{
  "type": "git",
  "version": { "commit": "8348484564e6aa0699de0ee78c258e88240eb0b5", "describe": "v0.18.1"},
  "metadata": {
    "refs": ["main", "v0.18.1", "v0.18.1-rc2"],
    "url": "git@github.com:buildpacks/pack.git"
  }
}
```

### Additional context

This issue is part of an epic of work. The related issues may be see by filtering on [epic/source-metadata](https://github.com/buildpacks/pack/labels/epic%2Fsource-metadata).

**Comment by imnitishng** [comment]
I see this is listed in the next milestone, and has already been worked on by someone else. I'd be happy to finish this 😄
