### ISSUE TITLE
Epic: Embed source metadata in OCI image

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#1139]
## Description

As a pack user, I would like to be able to inspect the final app image and determine where the source of the code is located as well as what _version_ (keeping in consideration SCM systems) was used.

## Issues

_full list of issues: [epic/source-metadata](https://github.com/buildpacks/pack/labels/epic%2Fsource-metadata)_

The following is a current snapshot of issues:

- [Provide project source metadata from project.toml](https://github.com/buildpacks/pack/issues/1138)
- [Provide project source metadata from local git information](https://github.com/buildpacks/pack/issues/1137)
- [Understand Spring Boot Git Properties](https://github.com/buildpacks/pack/issues/446)

**Comment by samj1912** [comment]
I would like to help out with this if possible. Especially item 2.

**Comment by jromero** [comment]
## Additional Resources

* [RFC Pull Request](https://github.com/buildpacks/rfcs/pull/9) (conversations behind idea)
* [Accepted RFC](https://github.com/buildpacks/rfcs/blob/main/text/0013-app-layer-metadata-source.md) (accepted idea)
* Spec Changes:
    * [Draft](https://github.com/buildpacks/spec/pull/68/files)
    * [Final](https://github.com/buildpacks/spec/pull/81/files)


**NOTE: RFC details may change as the move from idea to implementation (aka spec). Where there is a discrepancy, the spec always wins.**

**Comment by natalieparellano** [comment]
Closing as 1 was implemented in pack, 2 appears to have been implemented in Paketo, and 3 is covered by the linked issue
