### ISSUE TITLE
permission denied when using container option

### ISSUE THREAD

**Issue by mleegwt** [buildpacks/pack#1156]
**On Page:** [Pack](https://buildpacks.io/docs/tools/pack/)

From the instructions I chose the 'container' option.

After running `docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/workspace -w /workspace buildpacksio/pack build myimage --builder packetobuildpacks/builder:tiny` I receive the message:

```
ERROR: failed to build: failed to fetch builder image 'index.docker.io/packetobuildpacks/builder:tiny': Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.38/info": dial unix /var/run/docker.sock: connect: permission denied
```

I run as a local user. The user is in the 'docker' group. `ls -lha` for the docker.sock file results in 
```
srw-rw---- 1 root docker   0 apr 22 09:25 /var/run/docker.sock
```
How do I start pack from a container?

Thanks!

**Comment by mleegwt** [comment]
I found out that for Windows the `--user root` option works. On linux the fix was similar: `chmod 666 /var/run/docker.sock`. The Stackoverflow question: https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows helped in this regard.

**Comment by jromero** [comment]
Sounds like this was resolved. Thank you for posting your resolution. 🙏
