### ISSUE TITLE
PPA seems to be supplying the wrong version

### ISSUE THREAD

**Issue by iainfogg** [buildpacks/pack#1172]
### Summary
I've followed the instructions for installing `pack-cli` but although it says it installed `0.18.1-0ubuntu1~focal`, `pack` says it's version `0.15.1`.

##### Steps

1. I followed the Linux/Ubuntu instructions at https://buildpacks.io/docs/tools/pack/
```
sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
sudo apt-get update
sudo apt-get install pack-cli
```
The output from the last step was:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  pack-cli
0 to upgrade, 1 to newly install, 0 to remove and 7 not to upgrade.
Need to get 4,350 kB of archives.
After this operation, 16.0 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/cncf-buildpacks/pack-cli/ubuntu focal/main amd64 pack-cli amd64 0.18.1-0ubuntu1~focal [4,350 kB]
```
2. If I run `pack --version` I get `0.15.1`
3. If I rerun `sudo apt-get install pack-cli` the output is:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pack-cli is already the newest version (0.18.1-0ubuntu1~focal).
```
It seems to have installed the correct package, but the contents of that package seem to be an old version.

---

##### pack info
`pack info` cannot be run (`unknown command "info"`) - presumably that didn't exist in 0.15.1.

##### docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 21
  Running: 0
  Paused: 0
  Stopped: 21
 Images: 33
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-72-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.08GiB
 Name: ENTRO01
 ID: XOPP:BMZH:6662:MJXU:3OX4:CLHS:6YRO:IMOS:23OK:P7SM:4RC4:OK6W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by jromero** [comment]
@dwillist would you know what may be going on here?

**Comment by dwillist** [comment]
do you have multiple pack binaries on your path? what is the output of `type -a pack`?

**Comment by iainfogg** [comment]
Thanks, that's helped - I ran `type -a pack` and got this:

```
pack is a function with definition
# Defined via `source`
function pack --wraps='docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/muyser:/workspace -w /workspace buildpacksio/pack' --description 'alias pack=docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/muyser:/workspace -w /workspace buildpacksio/pack'
  docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/muyser:/workspace -w /workspace buildpacksio/pack $argv; 
end
pack is /usr/bin/pack
```

When I saw that, I noticed it's actually running a Docker image. I tried running `docker pull buildpacksio/pack:latest` which did pull down a new image (there already was one present) and when I re-ran `pack --version` it showed the correct output.

I'm guessing that I must have installed it in the past and forgotten about it, but it seems odd that nothing triggered an update of the Docker image - should something have forced it to update?

**Comment by jromero** [comment]
In the alias when `docker run` is called you can add the [`--pull always`](https://docs.docker.com/engine/reference/commandline/run/) argument but note that this will add a small delay every time you execute `pack` so that it can check it has the latest version.

**Comment by iainfogg** [comment]
Thanks, that's helpful.

I'm wondering what should normally do the pull though, and what a new version in `apt` is actually installing?

**Comment by jromero** [comment]
The way I read [this output](https://github.com/buildpacks/pack/issues/1172#issuecomment-839732373), is that you have two different installs of pack. 

1. An `alias` declared somewhere.
    - Likely somewhere in these locations: `~/.bashrc, ~/.bash_profile, ~/.profile, /etc/profile, /etc/bash.bashrc`
2. The binary installed from `apt`


I would suggest that you find the alias definition and remove it so that you can rely, and only have to work with, `apt`.

**Comment by iainfogg** [comment]
Credit to you, and my apologies! When I'd used `pack` a while ago, I must have followed the Docker approach, and this time I did the `apt` approach (having forgotten all about the first time!). I'd not realised that there were effectively two versions running.

The alias is gone, and it's happily reporting the correct version.

Thanks again!
