### ISSUE TITLE
Fully support Platform API 0.5 & 0.6

### ISSUE THREAD

**Issue by dwillist** [buildpacks/pack#1184]
### Description
Now that the lifecycle has support for these new platform API versions. We should support them as well in pack.

#### Work needed to support each API:
- `0.5`
  - None, all of the path changes in this API version are abstracted  from us via lifecycle env vars (thanks lifecycle folks) for a list of these changes see the [lifecycle release notes](https://github.com/buildpacks/lifecycle/releases/tag/v0.10.0) when `0.5` was introduced, and [this resolved lifecycle issue](https://github.com/buildpacks/lifecycle/issues/393) 
- `0.6` See [Lifecycle Release](https://github.com/buildpacks/lifecycle/releases/tag/v0.11.0) notes for list of changes in lifecycle.
  - List of issues [here](https://github.com/buildpacks/pack/labels/platform-api%2F0.6)

**Comment by robdimsdale** [comment]
Given that PR (#1051) was merged, is this issue complete?

I ask because I'm trying to understand what platform API pack supports, and this issue being open is a little confusing as it implies that 0.6 is not fully supported.

**Comment by samj1912** [comment]
@jromero may correct me if I am wrong but pack uses platform 0.6 I believe.

**Comment by robdimsdale** [comment]
Right, so we can close this issue?
