### ISSUE TITLE
Pack build should show terminal UI with log: info

### ISSUE THREAD

**Issue by aemengo** [buildpacks/pack#1204]
### Context
At this point of the `pack build` visual workflow, the pull and detect steps will have been completed and we will be in the *build step*. To avoid too much work in one PR, this issue is only about showing information about the **logs**.

### Objective
**When** I run `pack build --interactive/-i <name>`
**And** the pull step completes successfully
**And** the detect step completes successfully
**Then** I should see a full terminal panel for the **logs:** info

### Notes
- [Mockup](https://user-images.githubusercontent.com/4236888/121939771-5c394400-cd1b-11eb-80fc-db7eccaf0186.png)
   - _the logs should be streaming in, as the build is occurring_
   - _just a starting point, the final design is up to you_
- RFC: https://github.com/buildpacks/rfcs/pull/160

**Comment by smsufyian** [comment]
@aemengo Is there a way to assign the issue to myself , I want to work on this

**Comment by aemengo** [comment]
@smsufyian Thanks so much for expressing interest! Writing that comment is as good as getting yourself assigned.

This issue is currently part of a track of work. I'm afraid that this issue isn't ready to work on: _as written, at this exact_ moment.

If you want to be involved with the track of work more generally, please consider my [first PR for it](https://github.com/buildpacks/pack/pull/1230) which introduces the general architecture. 

--

I could certainly use the help 😅. Feel free to comment. And, if you want, I can give you write access to my fork to make edits yourself.

**Comment by aemengo** [comment]
This issue has been implemented and shipped.
