### ISSUE TITLE
RFE: vendor go dependencies

### ISSUE THREAD

**Issue by lsm5** [buildpacks/pack#1220]
Not a bug. I have a request on my plate to package this up for Fedora. It would be really convenient if all the go dependencies were vendored into the upstream source.

**Comment by lsm5** [comment]
if maintainers are open to this, i'll be happy to submit a PR.

**Comment by lsm5** [comment]
ping

**Comment by aemengo** [comment]
Committing vendored dependencies tends to bloat the git repository.

Go modules tend to pull dependencies deterministically. Are you having trouble vendoring on your end before packaging?

**Comment by lsm5** [comment]
@aemengo The fedora build environment doesn't allow network access at build time, so it would be really convenient and trustworthy to simply point to an upstream tar archive that contains the dependencies already vendored in instead of a tarball that's generated locally after local vendoring.

**Comment by aemengo** [comment]
And it's also a requirement to build the tool yourselves? As opposed to relying on official releases?

I'm keen on relying on community demand for this. Vendoring dependencies isn't just a one time effort, but our automation would also have to change.

**Comment by dfreilich** [comment]
We had used to do it, but moved away from vendoring – we found that it was hard to keep up to date, and it needlessly bloated the repository. 

It sounds to me like the underlying request is to package/release pack for Fedora. If you'd like to contribute a workflow to do that, we'd be happy to have that in the repository – we already support [arch](https://github.com/buildpacks/pack/blob/main/.github/workflows/delivery-archlinux.yml) and have an [ubuntu PPA](https://github.com/buildpacks/pack/blob/main/.github/workflows/deliver-ubuntu.yml), among others releases (you can see the list of delivery workflows [here](https://github.com/buildpacks/pack/tree/main/.github/workflows))

**Comment by jromero** [comment]
Vendoring dependencies solely for the purpose of one specific workflow (Fedora build environment) doesn't sound ideal or sustainable given the overhead we historically found. It sounds like an interim step that packages pack for Fedora seems more feasible.

Would @dfreilich's proposal work for @lsm5?

**Comment by lsm5** [comment]
all, thanks for the suggestions, I haven't tried the workflows yet, but I'm quite certain the ubuntu PPA workflow can be replicated for Fedora Copr, but that may not work for the fedora package review process though. But no worries, I guess I can generate tarballs locally to get things going. Closing this, thanks again.

**Comment by lsm5** [comment]
Hi all, `pack` is now available in the [Fedora updates-testing repos](https://bodhi.fedoraproject.org/updates/?packages=pack) with `dnf install pack`. It'd be great if you could get any Fedora users in here to test it. Thanks!

**Comment by dfreilich** [comment]
Fantastic, @lsm5! I'm relatively unfamiliar with the Fedora setup – is that something we should put on our docs as a method to install, or is `updates-testing` still a testing space, and we should hold off from putting it in our install docs? 

cc @buildpacks/learning-maintainers

**Comment by lsm5** [comment]
> Fantastic, @lsm5! I'm relatively unfamiliar with the Fedora setup – is that something we should put on our docs as a method to install, or is `updates-testing` still a testing space, and we should hold off from putting it in our install docs?

Yes, it's a testing space but kinda the first stage before moving to stable repos. Usually for every Fedora release, there's 2 major repos: `updates (stable)` repo and `updates-testing (testing)` repo. Packages in the updates-testing repo stay there for around a week or +3 karma (3 humans testing that the package works well (subjective), whichever is earlier. There's also gating tests (need to be manually enabled) if needed before packages could be pushed from updates-testing to updates. 

I can send a PR for install docs once it's available in the stable `updates` repo.

In case you're curious to read further on fedora repos: https://docs.fedoraproject.org/en-US/quick-docs/repositories/

**Comment by dfreilich** [comment]
Great, thanks for the work @lsm5!

**Comment by lsm5** [comment]
@dfreilich the rpm has landed in the stable `updates` repo. Could you point me to the right file for docs update please?

**Comment by dfreilich** [comment]
Fantastic to hear! The docs are located in the [buildpacks/docs](https://github.com/buildpacks/docs) repo. The right file is this one (https://github.com/buildpacks/docs/blob/main/themes/buildpacks/layouts/shortcodes/pack-install.html), but if it proves too difficult, we'll be happy to add it in as well.
