### ISSUE TITLE
pack should export report.toml

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1221]
### Description
[report.toml](https://github.com/buildpacks/spec/blob/main/platform.md#reporttoml-toml) contains information about the built image as well as the "build BOM" - build-time only dependencies. It is written (by default) to `/layers/report.toml` but the exporter does NOT put it in the final image. Therefore, unless the platform copies it out of the build container, it will be gone when the build is over and is not useful to anyone.

### Proposed solution
The platform should copy `report.toml` out of the build container, to some location (maybe specified by the user?). 

### Describe alternatives you've considered
Do nothing. Maybe pack users don't care about `report.toml`.

### Additional context
- [x] This feature should be documented somewhere

[Slack conversation](https://buildpacks.slack.com/archives/CD61YAG69/p1624387863052800) with more context.

**Comment by aemengo** [comment]
Is there a preferred user workflow that you have in mind for this?

For instance, the user reads the `report.toml` via the supplied file argument?

**Comment by natalieparellano** [comment]
cc @ForestEckhardt @sophiewigmore

**Comment by jromero** [comment]
I can envision a new flag named `--output-dir` which points to where `report.toml` would be placed. This would allow for any additional future artifacts to be extracted to as well. If they flag is not provided, then I'm of the opinion that we shouldn't default to any directory and therefore not export the `report.toml` (This can easily change in the future if we want different behaviour).

### Proposed Solution

#### `--output-dir` is provided with absolute path

```
Given /tmp/some-dir does or doesn't exist
When user runs "pack build my-app --output-dir /tmp/some-dir"
Then "report.toml" should be present in "/tmp/some-dir"
```

#### `--output-dir` is provided with relative path

```
Given PWD is "/some/dir/app/"
When user runs "pack build my-app --output-dir nested/dir"
Then "report.toml" should be present in "/some/dir/app/nested/dir"
```

#### `--output-dir` is not provided

```
Given PWD is "/some/dir/app/"
When user runs "pack build my-app"
Then no changes should have been made to PWD
```

**Comment by SAY-droid427** [comment]
Hey! @jromero! I am a new contributor here. May I take up this issue?

**Comment by jromero** [comment]
@SAY-droid427, it's nice to have you. I've assigned the issue.

Let me know if you have any questions on the issue. If you run into any issues please post a detailed question on here or on our [slack](https://slack.buildpacks.io/) (channel `#platform`).

**Comment by SAY-droid427** [comment]
Thank you so much @jromero ! I couldn't start working on the issue right away because I was down with fever after my first vaccine dose. Could you please help me a bit by pinting out where exactly the changes need to be made? thanks!

**Comment by aemengo** [comment]
Hey @SAY-droid427, I wanted to check on how you're finding this issue. In general, the way it works is that there's 2 code paths when building the application image:
* the [create](https://github.com/buildpacks/pack/blob/main/internal/build/lifecycle_execution.go#L180) container 
* the deconstructed 5-phase containers - in this case, [build](https://github.com/buildpacks/pack/blob/main/internal/build/lifecycle_execution.go#L405) container

What's tricky is that these are, by nature, ephemeral container instances. So the `report.toml` (_which is generated at runtime_) needs to be extracted before the file, and/or container, is cleaned up.

Feel free to pop by [https://slack.buildpacks.io/](https://slack.buildpacks.io/) for more real-time assistance.

**Comment by 4molybdenum2** [comment]
I can take this issue if its still relevant ? Just to clarify a few things... Can I get the ```report.toml``` from there and then write it to a host directory?
https://github.com/buildpacks/pack/blob/b09c8c8e6e02d22606513342057030f55577f191/pkg/client/rebase.go#L82-L83
Just change it to ```report, err = rebaser.Rebase(appImage, baseImage, nil)```?

**Comment by natalieparellano** [comment]
@4molybdenum2 thanks for offering to work on this! I believe this issue is still relevant (@dfreilich @jromero please correct me if I'm wrong).

We generate `report.toml` for both `pack build` and `pack rebase`. I think we'd be interested in getting it in both cases. For `pack build` it's a bit tricker as we'd need to copy it out of the build container before the container exits. I know @jromero has some ideas about the user interface for this. 

If you're still interested in working on this, I'd suggest reaching out in the #buildpacks-pack-cli channel in [Slack](https://slack.cncf.io/) for more real-time feedback.

**Comment by joe-kimmel-vmw** [comment]
If there's any maintainers who feel like assigning this, i'm working on it in the PR that's actually linked above already.
