### ISSUE TITLE
The '--no-color' flag doesn't apply to the buildpack log output in build step

### ISSUE THREAD

**Issue by trisberg** [buildpacks/pack#123]
I can use the `--no-color` flag and most steps honor this flag but the logging from individual buildpacks still shows as color coded. This is not a big deal in terminals that support the color codes but looks terrible in Windows PowerShell.

**Comment by trisberg** [comment]
color:
<img width="1431" alt="color" src="https://user-images.githubusercontent.com/78614/55237272-2bd36100-5208-11e9-82b6-5ce295894b14.png">

no-color:
<img width="1387" alt="no-color" src="https://user-images.githubusercontent.com/78614/55237279-31c94200-5208-11e9-97b7-9f72fbf891aa.png">

**Comment by ameyer-pivotal** [comment]
@trisberg Thanks for bringing this up! The buildpack itself runs as a separate binary that `pack` invokes, so it makes sense why this is happening. We do have on our roadmap to improve the logging interface between `pack` and the buildpacks, so this is a good bug to keep in mind.

**Comment by trisberg** [comment]
Thanks, good to hear it is on the roadmap. Would also be nice to be able to control this via an env var so it is easier to set when run with a Knative buildtemplate.

**Comment by nebhale** [comment]
See https://github.com/projectriff/libfnbuildpack/issues/56#issuecomment-482681372 for what's going on and a suggestion for `pack` to let us relax a bit.

**Comment by jromero** [comment]
Issue #141 is related in that it's more problematic in Windows. The changes made for #141 might lower the impact or priority of this issue.

**Comment by six-edge** [comment]
I can confirm that colour output on Windows Powershell or git bash doesn't work. The colour control chars makes the output messy. Was a bit surprised on the first run. Not the best impression. We have to use Powershell as we are using Docker Desktop for Windows. Could these chars be turned off by default for the Windows CLI installer?

**Comment by ameyer-pivotal** [comment]
@six-edge It should work on CMD on Windows, but we've known about Powershell issues for a bit. It should have recently been fixed on master. Were you using a specific release or master?

**Comment by abarke** [comment]
Using pack v0.4.1 I still get strange chars:
[[36mbuilder[0m]        Loading composer repositories with package information
[[36mbuilder[0m]        Installing dependencies from lock file
[[36mbuilder[0m]        Nothing to install or update
[[36mbuilder[0m]        Generating optimized autoload files
[[36mbuilder[0m] -----> Preparing runtime environment...
[[36mbuilder[0m] -----> Checking for additional extensions to install...
[[36mbuilder[0m] -----> Discovering process types
[[36mbuilder[0m]        Procfile declares types     -> web

However when using --no-color I get better formatting but there are still a few control chars in there:
[builder] [1;33m
[builder]  !     WARNING: Your app's PHP version is close to end of maintenance
[builder]  !
[builder]  !     Only security updates will be provided for your PHP version
[builder]  !     series by the PHP Group as of 2019-11-30.
[builder]  !
[builder]  !     It is strongly recommended you update your app to a version of
[builder]  !     PHP with "active support" status immediately to ensure you get
[builder]  !     the latest bugfixes and security updates each time you deploy.
[builder]  !
[builder]  !     You may check the list of versions supported by the PHP Group
[builder]  !     and their EOL dates here: http://php.net/supported-versions.php
[builder]  !
[builder]  !     For a list of supported runtimes & extensions on Heroku, please
[builder]  !     refer to: https://devcenter.heroku.com/articles/php-support
[builder] [0m

**Comment by jromero** [comment]
@abarke The related changes mentioned prior regarding issue #141 will be available on **0.5.0** which we haven't released yet. If you want to give it a try (for testing purposes) you can build from `master`.

**Comment by abarke** [comment]
@jromero ah ok thanks for the info. Will give it a try.

**Comment by jromero** [comment]
@abarke It should be fairly trivial specially when doing so on a linux/macos machine by using the Makefile (`make build`).

See https://github.com/buildpack/pack/blob/master/CONTRIBUTING.md#development

If you are using Windows you'd want to look at the contents of [Makefile here](https://github.com/buildpack/pack/blob/master/Makefile#L16) but it's still pretty simple if you have [go](https://golang.org/doc/install) setup.

**Comment by natalieparellano** [comment]
@abarke did the changes in 0.5.0 solve your issue?

**Comment by nebhale** [comment]
There is still an outstanding bug here that one of the outputs (from `lifecycle` I believe) doesn't honor the flag:

![image](https://user-images.githubusercontent.com/60754/73975994-3d7f9d80-48dc-11ea-9e6d-c5e50117a1bd.png)

The buildpacks that @trisberg is seeing the "always color" behavior with are mine and I'll take a look if I can make them respect that flag a bit more.

**Comment by natalieparellano** [comment]
Hmm there may be a regression as `pack` is supposed to strip off color from output returned by the lifecycle. Maybe we could implement this better.

**Comment by abarke** [comment]
@natalieparellano my issue was fixed. Im currently using v0.5.0
