### ISSUE TITLE
pack version 0.19 dont support a builder TOML config having an api version

### ISSUE THREAD

**Issue by cmoulliard** [buildpacks/pack#1232]
### Summary

pack version 0.19 `0.19.0+git-360dbae.build-2550` dont support to execute `pack builder` using a TOML file containing the api version 
```
# Buildpack API version
api = "0.5"

[[buildpacks]]
uri = "docker://snowdrop/maven-bp"

[[order]]
[[order.group]]
id = "dev.snowdrop.buildpacks.maven"
version = "0.0.1"

# Stack(s) that will be used by the Builder
[stack]
id = "dev.snowdrop.buildpacks.stack.jvm"
run-image = "redhat/buildpacks-stack-snowdrop-run:jvm"
build-image = "redhat/buildpacks-stack-snowdrop-build:jvm"
```
and will report this error
```
pack builder create redhat/buildpacks-builder-maven-jvm:latest --config ./tmp/builder.toml 
ERROR: invalid builder toml: parse contents of './tmp/builder.toml': unknown configuration element api in tmp/builder.toml
```

The api field is mentioned here within the spec or examples:
- https://github.com/buildpacks/spec/blob/buildpack/v0.6/buildpack.md#buildpacktoml-toml
- https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb/#buildpacktoml

---

##### Steps

1. Create a toml file containing `api = "0.5"`
2. Execute `pack builder create redhat/buildpacks-builder-maven-jvm:latest --config ./tmp/builder.toml `

**Comment by samj1912** [comment]
The builder toml is not versioned and is currently not supposed to have an api key. The builder also isn't part of the official spec currently and is a pack only construct. You can find more details about creating a builder at 
https://buildpacks.io/docs/operator-guide/create-a-builder/
https://buildpacks.io/docs/reference/config/builder-config/

It doesn't contain an api key in it's schema.

**Comment by cmoulliard** [comment]
> It doesn't contain an api key in it's schema.

But then, if it is not part of the schema/spec, then `pack builder` should not raise an error and maybe only raise a warning message. 


Ideally `pack builder` should check the version to be sure that it matches the lifecyle version and/or buildpack version ;-)

**Comment by cmoulliard** [comment]
My fault. I was not using the correct schema for the builder: https://buildpacks.io/docs/reference/config/builder-config/
So this ticket can be closed. WDYT ?
