### ISSUE TITLE
Zip files with preamble text are not recognized by pack build

### ISSUE THREAD

**Issue by scottfrederick** [buildpacks/pack#1236]
### Summary
The zip file specification allows for arbitrary [text to exist at the beginning of the file](https://en.wikipedia.org/wiki/ZIP_(file_format)#Combination_with_other_file_formats), before the first file entry header. This is often used to create self-extracting or self-executable zip files. 

Spring Boot uses this technique to create executable jar files that include a Unix launch script at the beginning of the file, as described in the Spring Boot [Gradle](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable.configuring.launch-script) and [Maven](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-executable) documentation. 

`pack` expects a zip file to begin with a file entry header (`PK/3/4`) [at offset zero of the file](https://github.com/buildpacks/pack/blob/main/pkg/archive/archive.go#L370-L381), so it does not recognize a self-extracting or self-executable zip or jar file. The standard Go `archive/zip` package is able to read zip and jar files with a preamble. 

---

##### Steps

Clone a branch of the CNB samples repo containing a modified version of the `java-maven` sample that enables the Spring Boot launch script: 

```
$ git clone https://github.com/scottfrederick/cnb-samples --branch boot-launch-script --single-branch
```

Build the app: 

```
$ cd cnb-samples/apps/java-maven
$ ./mvnw package
```

Verify the built app: 

```
$ target/sample-0.0.1-SNAPSHOT.jar
[ app runs as an executable using launch script ]

$ zipinfo target/sample-0.0.1-SNAPSHOT.jar
Archive:  target/sample-0.0.1-SNAPSHOT.jar
Zip file size: 18859754 bytes, number of entries: 131
drwxr-xr-x  2.0 unx        0 bX defN 21-Jul-20 14:17 META-INF/
-rw-r--r--  2.0 unx      479 bl defN 21-Jul-20 14:17 META-INF/MANIFEST.MF
[ listing of zip file contents ]
131 files, 18977800 bytes uncompressed, 18826154 bytes compressed:  0.8%

$ head -50 target/sample-0.0.1-SNAPSHOT.jar
[ partial listing of launch script pre-pended to jar file contents ]
```

##### Current behavior

```
$ pack build sample-app --path target/sample-0.0.1-SNAPSHOT.jar --builder cnbs/sample-builder:bionic
ERROR: failed to build: invalid app path 'target/sample-0.0.1-SNAPSHOT.jar': app path must be a directory or zip
```

##### Expected behavior

The `pack build` command recognizes and processes the jar file as a properly formed zip archive. 

---

##### pack info

```
Pack:
  Version:  0.19.0+git-360dbae.build-2550
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.11.3

Supported Platform APIs:  0.3, 0.4

Config:
  default-builder-image = "[REDACTED]"
```

**Comment by corneil** [comment]
I would suggest if the file is named with .jar and starts with '#!' then pack shouldn't try to unzip it and produce a warning about performance impact and assume it is an executable jar.

**Comment by jromero** [comment]
Hi @corneil, I see your comment but I'm curious of the reason for the comment. Are you running into a specific issue at the moment? If so, do you mind opening a new issue?

**Comment by corneil** [comment]
If a spring boot application os built with executable = true and you then use pack to create an image it fails with the complaint that the file isn't a zip file.

**Comment by corneil** [comment]
We are running pack with java 8, 11 and 17.
