### ISSUE TITLE
Update default version in pack-orb and github-actions as part of Pack release process 

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#1244]
### Description
The pack-orb and github-actions repositories simplify the process of installing Pack CLI in on Circle CI and GitHub actions respectively. They both have a default Pack version that will be used, unless the user overrides it. This default version is often quite out of date.

### Proposed solution
Add a post-pack-release step to `RELEASE.md` for updating the default Pack versions used by the above tools, so that the defaults are always up to date:
https://github.com/buildpacks/pack-orb/blob/1abdea7406c545ce85d5aa4e93302c365947a68f/src/%40orb.yml#L42-L43
https://github.com/buildpacks/github-actions/blob/92f1f32cd6905fad05cbf97de235a8e2dbb7effb/setup-pack/action.yml#L15-L17

### Additional context
https://github.com/buildpacks/github-actions/pull/71
https://github.com/buildpacks/pack-orb/pull/33

**Comment by importhuman** [comment]
Hi @edmorley, can I work on this? If I understand correctly, the YAML in the linked files needs to be updated so that the default version is the latest pack release?

**Comment by edmorley** [comment]
@importhuman Hi! This issue is about updating the playbook used when maintainers release a new Pack version, such that the playbook reminds them to update the defaults in the yaml for those other projects after every pack release.

**Comment by importhuman** [comment]
@edmorley I'm not too familiar with the terminology, does the playbook refer to the `RELEASE.md`? If so, would it not serve the purposes of this issue that we automate the yaml update instead, which will also eliminate the chance of missing an update? I haven't done something like it before, so I don't know if it's possible or not.

**Comment by edmorley** [comment]
Automation would be even better, yes! Though it's perhaps worth doing both (first adding a quick item to RELEASE.md, then later when someone has more time, automating it). I'm not a maintainer though, so I can't comment as to what would be accepted.

**Comment by importhuman** [comment]
Ah, I see. I'd be happy to work on either/both parts if decided by the maintainers.

**Comment by jromero** [comment]
This sounds like a great idea! The automation shouldn't be too difficult to implement. We currently do this for the [buildpacks/docs](https://github.com/buildpacks/docs) repo.

The dispatch is done [here (in buildpacks/pack)](https://github.com/buildpacks/pack/blob/main/.github/workflows/delivery-release-dispatch.yml#L13) and then captured [here (in buildpacks/docs)](https://github.com/buildpacks/docs/blob/main/.github/workflows/main.yml#L10-L12).

I would propose that the action taken when the dispatch is captured by the pack-orb and github-action repos to be a pull request to update the pack version. Then maintainers will get notified, simply need to merge it, and publish a new released. 

We do similar things in the registry-index. See [update-version-on-release-ga.yaml](https://github.com/buildpacks/registry-index/blob/main/.github/workflows/update-version-on-release-ga.yaml)

Hope this all helps @importhuman

**Comment by importhuman** [comment]
Thanks @jromero, this definitely helps!

**Comment by jromero** [comment]
Really nice set of changes @importhuman! Thank you!

I'm assuming there's an upcoming PR for `buildpacks/github-actions` to close out this issue.

**Comment by importhuman** [comment]
@jromero yup, just wanted to confirm if the code needed any changes. Will do it for the other repo now.

**Comment by importhuman** [comment]
This can be closed now.

**Comment by edmorley** [comment]
@importhuman Thank you for implementing this! :-D
