### ISSUE TITLE
Can no longer provide alternative implementations of ImageFetcher

### ISSUE THREAD

**Issue by briandealwis** [buildpacks/pack#1245]
### Summary
PR #1216 changed `ImageFetcher.Fetch()` to use an internal `FetchOptions` type from `pack/internal/image`.  This prevents providing alternative `ImageFetcher implementations`as that `pack/`internal/image` package can't be imported from other modules.

This change prevents Skaffold from updating to use pack v0.20.0 as Skaffold provides [an alternative implementation of `ImageFetcher`](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/buildpacks/fetcher.go#L46).

---

##### Steps

1. create `fetcher.go`:
```golang
package main
import "context"
import "github.com/buildpacks/pack"
import "github.com/buildpacks/pack/internal/image"
import "github.com/buildpacks/imgutil"
type fetcher struct {}
func (f *fetcher) Fetch(_ context.Context, _ string, _ image.FetchOptions) (imgutil.Image, error) { return nil, nil }
var _ pack.ImageFetcher = (*fetcher)(nil)
```
2. `go mod init example.com/fetch`
2. `go mod tidy`
3. `go build .`

##### Current behavior

Build fails:
```
$ go build
package example.com/fetcher
	fetch.go:4:8: use of internal package github.com/buildpacks/pack/internal/image not allowed
```

##### Expected behavior

Build should succeed.

**Comment by briandealwis** [comment]
This affects other types in `client.go` too:
- the `Downloader` interface's `Download()` returns `internal/blob.Blob`
- the `BuildpackDownloader` interface's `Download()` returns `internal/dist.Buildpack`

**Comment by aemengo** [comment]
@briandealwis Thanks for creating this issue.

How do we prefer to resolve this? In general, I'm in favor of making options public. Perhaps an `./options.go` file at the root of the repository.

Any others have thoughts?

**Comment by jromero** [comment]
Tried a few things and this is going to require a bit more elbow grease (restructuring). Sorry but it may take one more release before we can ship this out. :/
