### ISSUE TITLE
`pack` should respect 'XDG Base Directory' and not create .dotfiles inside `$HOME`

### ISSUE THREAD

**Issue by aSemy** [buildpacks/pack#1272]
### Summary

I'd like to install pack zsh completion. I'd also like to keep my `$HOME` clean of dot files. 

A summary of the XDG Base Directory is available here: https://wiki.archlinux.org/title/XDG_Base_Directory

I've set the correct environment variable.

```shell
> echo $XDG_CONFIG_HOME
/home/adam/.config
```

### Reproduction

When I run `pack completion --shell zsh`, it creates a `.pack` directory inside `~`.

```shell
> pack completion --shell zsh
/home/adam/.pack/completion.zsh
```

##### Expected behavior

I'm expecting it to create and use a directory inside `XDG_CONFIG_HOME`, e.g. `/home/adam/.config/pack/`

I tried experimenting with `PACK_HOME` after a [quick look through the code](https://github.com/buildpacks/pack/search?q=PACK_HOME&type=code) but it didn't make a difference.

```shell
> echo $PACK_HOME
/home/adam/.config/pack
```

Maybe there's another way of configuring the config directory? :)

### Environment

I'm using Windows 10, WSL2, Debian 10, `zsh 5.7.1 (x86_64-debian-linux-gnu)`

##### pack info

```shell
> pack report
Pack:
  Version:  0.20.0+git-66a4f32.build-2668
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.11.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6

Config:
(no config file found at /home/adam/.pack/config.toml)
```

**Comment by aemengo** [comment]
Thank you for raising this issue. A clarifying question: how are you experimenting with `PACK_HOME`? Are you saying that the following didn't work for you?

```shell
$ PACK_HOME=/home/adam/.config/pack pack completion --shell zsh
...
```

**Comment by aSemy** [comment]
Ah thanks, that command works. It's strange that when I set the `PACK_HOME` as an environment variable it doesn't work...


```sh
# all-in-one command works correctly
> PACK_HOME=/home/adam/.config/pack pack completion --shell zsh
/home/adam/.config/pack/completion.zsh

# the env-var is set as XDG_CONFIG_HOME/pack
> echo $PACK_HOME
/home/adam/.config/pack

# but pack cli doesn't read the env-var?
> pack completion --shell zsh
/home/adam/.pack/completion.zsh
```

**Comment by jromero** [comment]
How did you set `PACK_HOME`? Did you `export` it?

You can check your env vars by running:

```shell
export | grep PACK_HOME
```

**Comment by aSemy** [comment]
I've been struggling setting environment variables in WSL - it seems it's an ongoing issue ([example](https://askubuntu.com/questions/1046253/http-proxy-not-showing-up-with-printenv-on-wsl)). I've exported `PACK_HOME` in `.zshrc`

```bash
export PACK_HOME="${XDG_CONFIG_HOME}/pack"
```

and now I get the expected result!

```shell
> pack completion --shell zsh
/home/adam/.config/pack/completion.zsh
```

**Comment by jromero** [comment]
@aSemy, glad this worked out. I'm going to close this as resolved unless you think there's more here to uncover/discuss.
