### ISSUE TITLE
Hardlinks are dereferenced in generated archives increasing buildpack and app image sizes

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#1286]
### Summary
If a local buildpack contains files that are hardlinks of each other, the hard links are not preserved in the `.cnb` file or OCI image created by `pack buildpack package`, and instead the file contents is duplicated, increasing the size of the buildpack.

This affects compiled buildpacks that use a single hard-linked binary for detect/build (where the binary determines which mode it is being run in, based on its filename; such as in [libcnb.rs](https://github.com/Malax/libcnb.rs/blob/c502c73b0b586acd3cd45e39947b015dcd60f088/src/runtime.rs#L64-L84) and the [Go libcnb](https://github.com/buildpacks/libcnb/blob/d893d2a8defa3a61a6eb22d20b6fbe018f50ff9d/main.go#L45-L53)). 

This contrasts to using Docker natively, which preserves hardlinks both in the build context, and in layers created by `RUN`  commands.

---

##### Steps
1. `pack buildpack new test-buildpack`
2. `dd if=/dev/urandom of=test-buildpack/large-file count=$((100 * 1024)) bs=1024` (a 100MB file)
3. `ln test-buildpack/large-file test-buildpack/large-file2` (a hard link)
4. `pack buildpack package --verbose --path test-buildpack/ --format file test-buildpack.cnb`
5. `pack buildpack package --verbose --path test-buildpack/ --format image test-buildpack`
6. `ls -lh test-buildpack.cnb`
7. `docker images | rg test-buildpack`

##### Current behavior
Both the `test-buildpack.cnb` file and the `test-buildpack` OCI image are ~200MB each, since the hardlink wasn't preserved.

For the `.cnb` file:
```
$ ls -lh test-buildpack.cnb
-rw-r--r-- 1 emorley staff 201M Sep 16 16:00 test-buildpack.cnb
```

For the OCI image:
```
$ docker images | rg test-buildpack
test-buildpack                            latest    0f41579f403c   41 years ago   210MB
```

##### Expected behavior
Both the `test-buildpack.cnb` file and the `test-buildpack` OCI image are only ~100MB in size each, since the content of the hardlinked file is only included once.

For the `.cnb` file:
```
$ ls -lh test-buildpack.cnb
-rw-r--r-- 1 emorley staff 101M Sep 16 16:00 test-buildpack.cnb
```

For the OCI image:
```
$ docker images | rg test-buildpack
test-buildpack                            latest    0f41579f403c   41 years ago   105MB
```

### Additional Context
Compare this to the Docker behaviour...

```Dockerfile
FROM ubuntu:20.04
COPY . /
```

1. Create `Dockerfile` with above contents
2. `dd if=/dev/urandom of=large-file count=$((100 * 1024)) bs=1024`
3. `ln large-file large-file2`
4. `docker build -t test-docker .`
5. `docker images | rg '(ubuntu|test-docker)'`

As can be seen from the logs, only 100MB is transferred in the build context, and the resultant image is also only 100MB larger than the base Ubuntu 20.04 image:

```
$ docker build -t test-docker .
[+] Building 0.8s (7/7) FINISHED                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                            0.0s
 => => transferring dockerfile: 69B                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                               0.0s
 => => transferring context: 232B                                                                                                                                                               0.0s
 => CACHED [1/2] FROM docker.io/library/ubuntu:20.04                                                                                                                                            0.0s
 => [2/2] COPY . /                                                                                                                                                                              0.2s
 => exporting to image                                                                                                                                                                          0.5s
 => => exporting layers                                                                                                                                                                         0.5s
 => => writing image sha256:488b0bd9f029e11c15fcdb30b40ec6257f3967dbe63a5c525bc3b8415935d2bb                                                                                                    0.0s
 => => naming to docker.io/library/test-docker                                                                                                                                                  0.0s

$ docker images | rg '(ubuntu|test-docker)'
test-docker                               latest    488b0bd9f029   4 seconds ago        178MB
ubuntu                                    20.04     fb52e22af1b0   2 weeks ago          72.8MB
```

---

##### pack info
```
$ pack report
Pack:
  Version:  0.20.0+git-66a4f32.build-2668
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.11.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6

Config:
  default-builder-image = "[REDACTED]"
  experimental = true
  
  [[trusted-builders]]
    name = "[REDACTED]"
```

##### docker info
```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 27
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: [REDACTED]
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by edmorley** [comment]
Hard links are also not preserved either (a) if they existed in the app source provided in the workspace to Pack, (b) if the buildpack creates them during `bin/build`. I can file these separately if needed, but for now I thought I'd start with just the `pack buildpack package` case, since it's the one affecting us - and the fix for this might fix the others (I haven't looked at the implementation).

**Comment by edmorley** [comment]
I've morphed the title to reflect the fact that this issue affects not only the output of `pack buildpack package`, but also generated app images too (both files in the app source provided as input to the build, and files created by the buildpack during the build).

So far I can see two tar file implementations in CNB related repositories:
https://github.com/buildpacks/lifecycle/blob/917c1acd25299b8c49f97ca6805ca13563d7d630/archive/archive.go
https://github.com/buildpacks/pack/blob/b9be13ac1e8e2393c2ae1d1ca1ff21ae3c0d3c1c/pkg/archive/archive.go

Neither of these have specific provision for hard links, which explains why they the contents are dereferenced/duplicated.

Compare to the moby archive implementation, which does handle hard links:
https://github.com/moby/moby/blob/c6872980bb0b32d2f30f70c6761501a9cd31a94f/pkg/archive/archive.go#L592-L608

**Comment by jjbustamante** [comment]
I going to try to reproduce this issue with the steps mentioned by @edmorley and then I will move it to *ready* status

**Comment by jjbustamante** [comment]
I just executed the reproductions steps with the latest pack version 0.30.0 and the issue is still reproducible 

![Screenshot 2023-08-17 at 3 51 49 PM](https://github.com/buildpacks/pack/assets/1181799/beefbdf7-0378-40dd-8fcc-031d27c16412)

**Comment by jjbustamante** [comment]
I was working on this today. I think I managed to fix it.

This is what I have:

Following the reproduction steps and with the docker file, this is the output when we dive into the image:

![Screenshot 2023-09-08 at 5 54 06 PM](https://github.com/buildpacks/pack/assets/1181799/1b5a5f3f-dc69-423c-bdc2-6324d185d554)

After doing the changes, this is how the buildpack package image looks like 

![Screenshot 2023-09-08 at 5 54 38 PM](https://github.com/buildpacks/pack/assets/1181799/2f2db6f9-10c9-43db-8a4f-5195d4e2c9bd)

I  will try to keep working on this and create the PR next week. but I believe it was a productive day 😄

**Comment by jjbustamante** [comment]
I just created a draft PR that fixes the problem for `pack buildpack package` command, I will need to take a look for the other cases:
- `pack build <my-app>`
   - With hardlinks provided by the application source code
   - With hardlinks provided by the buildpacks applied
