### ISSUE TITLE
forward bin/detect stderr for non standard exit codes

### ISSUE THREAD

**Issue by hone** [buildpacks/pack#1292]
### Description

`pack` should display the error messages for unexpected exit codes during `bin/detect`. Without the verbose flag, the errors are hidden and it makes it look like the buildpack is operating normally returning a failed detection.

According to the [Buildpack API spec](https://github.com/buildpacks/spec/blob/main/buildpack.md#detection), the only normal exit codes are `0` for Pass and `100` for Fail. For any other exit code, `pack` should display the error output like it does when the verbose flag is set.

**Comment by rdanielwetan** [comment]
Hi @hone  I'm new to this repo. Can you please guide me to appropriate code part? and a bit of explanation about the issue would be really helpful!

**Comment by natalieparellano** [comment]
Digging into this a bit, it seems the lifecycle will emit buildpack errors as info-level messages (https://github.com/buildpacks/lifecycle/pull/351) so I'm surprised these aren't showing up in the pack logs. @hone do you have an example?

@rdanielwetan apologies for missing your earlier message. We'd be grateful to have your help - though as this issue may require further research, another one of our [good first issues](https://github.com/buildpacks/pack/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) might be better.

**Comment by ryanmoran** [comment]
I can confirm that this behavior already seems to be happening. We have an issue filed against one of our buildpacks where its being too chatty in the detect output because it is emitting an error when it should be failing: https://github.com/paketo-buildpacks/node-run-script/issues/180.
