### ISSUE TITLE
BOM label doesn't play nice with containerd (> 1.5.6) label limits

### ISSUE THREAD

**Issue by jimmykarily** [buildpacks/pack#1309]
### Summary

Originally opened here: https://github.com/paketo-buildpacks/full-builder/issues/415 (partly copied here).

I'm building an image using the full-builder (which is using `pack`). I'm doing this through [Epinio](https://github.com/epinio/epinio/). The cluster I'm using is [k3d](https://k3d.io/v5.0.0/) using the image `rancher/k3s:v1.22.2-k3s2`. That image is running containerd `v1.5.7` in it.

When containerd tries to start a container which was built with the `paketobuildpacks/builder:full` image, it fails with an error:

```
label key and value greater than maximum size (4096 bytes), key: io.buildpa: invalid argument 
```

This seems to originate here: https://github.com/jessvalarezo/containerd/blob/18c4322bb3ddcb8f8b4eea2f3c027a06194041b4/labels/validate.go

Everything works fine on containerd `v1.4.11`. I had a look at changelogs and I think it's this one (introduced in [1.5.6](https://github.com/containerd/containerd/releases/tag/v1.5.6)):

https://github.com/containerd/containerd/issues/5938
https://github.com/containerd/containerd/pull/6012/files

`pack` is writing the full BOM inside a label and depending on the size of that list, that label can be too big for containerd.
Is there a reason why BOM has to be a label?
There have been similar issues in the past: https://github.com/paketo-buildpacks/full-builder/issues/191

---

##### Steps

See description above

##### Current behavior

Image built with pack (through the full builder image) doesn't start in containerd

##### Expected behavior

Image should work

---

##### pack info

hard to run because it's running inside the full builder image. I can try to re-produce using only `pack` if you want but I think the problem is already clear.

##### docker info

No docker, just containerd running as the runtime in k3d.

**Comment by samj1912** [comment]
I have created a fix at https://github.com/containerd/containerd/pull/6124. However I am not sure if that will be accepted as it is.
