### ISSUE TITLE
`pack build --buildpack` doesn't overwrite existing buildpacks in the builder correctly

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#1322]
### Summary
When `pack build` is run using the `--buildpack` argument, and the provided buildpack ID and version match a buildpack already in the builder image, pack claims to overwrite the existing buildpack, however actually only overlays the imported buildpack on top of it, leaving any stray files intact.

ie: The resultant buildpack in the ephemeral builder used for the build ends up being a hybrid of both the old and new buildpack files.

This is presumably because there is no "remove existing buildpack" step in here, only "unpack tar directly into layer":
https://github.com/buildpacks/pack/blob/339b49e8c10978bb80a899fe8668741d9f730aba/internal/builder/builder.go#L409-L448

---

##### Steps

1. `git clone https://github.com/buildpacks/samples && cd samples`
2. `touch buildpacks/java-maven/buildpack-in-builder`
3. `pack builder create testcase --config builders/alpine/builder.toml`
4. `rm buildpacks/java-maven/buildpack-in-builder && touch buildpacks/java-maven/buildpack-local`
5. `echo -e '#!/usr/bin/env bash\nls -al "${CNB_BUILDPACK_DIR}"\nexit 1' > buildpacks/java-maven/bin/detect`
6. `pack build sample-app --builder testcase --buildpack buildpacks/java-maven/ --path apps/java-maven/ --verbose`

##### Current behavior
- Pack reports `buildpack samples/java-maven@0.0.1 already exists on builder and will be overwritten`
- However as can be seen in the `ls` output, files from the buildpack that was in the builder have been left behind (the file `buildpack-in-builder` should no longer exist).

```
$ pack build sample-app --builder testcase --buildpack buildpacks/java-maven/ --path apps/java-maven/ --verbose
...
Downloading buildpack from URI: file:///Users/emorley/src/samples/buildpacks/java-maven
Adding buildpack samples/java-maven version 0.0.1 to builder
Setting custom order
Creating builder with the following buildpacks:
-> samples/java-maven@0.0.1
-> samples/kotlin-gradle@0.0.1
-> samples/hello-universe@0.0.1
-> samples/hello-world@0.0.1
-> samples/hello-moon@0.0.1
-> samples/java-maven@0.0.1
buildpack samples/java-maven@0.0.1 already exists on builder and will be overwritten
  - existing diffID: sha256:ba3075c5689ac3a324105cd6690650f34decfd4536f167c05cb552944c850a08
  - new diffID: sha256:b036c35ff97ec7dff1f2ae1bc323085b056c0e4d55727be86234cdd1b2ea8e74
Adding buildpack samples/java-maven@0.0.1 (diffID=sha256:b036c35ff97ec7dff1f2ae1bc323085b056c0e4d55727be86234cdd1b2ea8e74)
...
[detector] ======== Output: samples/java-maven@0.0.1 ========
[detector] total 20
[detector] drwxr-xr-x    1 root     root          4096 Jan  1  1980 .
[detector] drwxr-xr-x    1 root     root          4096 Jan  1  1980 ..
[detector] -rw-r--r--    1 root     root           342 Jan  1  1980 README.md
[detector] drwxr-xr-x    1 root     root          4096 Jan  1  1980 bin
[detector] -rw-r--r--    1 root     root             0 Jan  1  1980 buildpack-in-builder
[detector] -rw-r--r--    1 root     root             0 Jan  1  1980 buildpack-local
[detector] -rw-r--r--    1 root     root           477 Jan  1  1980 buildpack.toml
```

##### Expected behavior
- Pack reports `buildpack samples/java-maven@0.0.1 already exists on builder and will be overwritten`
- The `ls` output shows that files from the buildpack that was in the builder have been removed (ie: the file `buildpack-in-builder` should no longer exist).

---

##### pack info
```
Pack:
  Version:  0.22.0+git-26d8c5c.build-2970
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.11.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6

Config:
  default-builder-image = "[REDACTED]"
  experimental = true

  [[trusted-builders]]
    name = "[REDACTED]"
```

##### docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: REDACTED
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by jromero** [comment]
If I'm not mistaken we have two options here:

1. Create a new image with the old buildpack layer excluded from the layers list.
2. Append a ["whiteout" layer](https://github.com/opencontainers/image-spec/blob/main/layer.md#whiteouts) before appending the new buildpack layer.

I don't have much experience with the whiteout method to know whether that would work in all cases but I would assume that appending layers would be more performant than constructing a new image.

**Comment by edmorley** [comment]
Repeating the steps to reproduce with pack CLI v0.24.0 shows that #1362 successfully fixed the issue :-)
