### ISSUE TITLE
Add support for platform 0.7 and 0.8

### ISSUE THREAD

**Issue by samj1912** [buildpacks/pack#1333]
### Description

Add support for platform 0.8 for sbom support 

### Additional context
- [ ] This feature should be documented somewhere

**Comment by samj1912** [comment]
Related kpack PR for migration steps https://github.com/pivotal/kpack/pull/889

**Comment by aemengo** [comment]
I believe that @mboldt is already making headway on adding support for platform `0.7`. After that is completed, we (_or anyone interested_) can focus on the support for platform `0.8`.
