### ISSUE TITLE
Add support for downloading sbom via the platform 0.8 interface

### ISSUE THREAD

**Issue by samj1912** [buildpacks/pack#1335]
### Description

Platform 0.8 in lifecycle uploads new sboms to a separate layer instead of a label. We should add support in pack to download this layer as a tarball. 

### Additional context
- [ ] This feature should be documented somewhere

**Comment by aemengo** [comment]
As of [v0.23.0](https://github.com/buildpacks/pack/releases/tag/v0.23.0), pack can now display the [file-system](https://github.com/buildpacks/pack/pull/1326) of the build container. I think this would be a great feature, and workflow, to have as part of the terminal UI. What do you think?

**Comment by samj1912** [comment]
That sounds great, but I think we will still need to have a replacement for pack inspect-image --bom which works for both remote images and local images

**Comment by basit9958** [comment]
I would like to solve this issue. I am a beginner. Please give me some pointers as well as to what to implement and where

**Comment by dfreilich** [comment]
@basit9958 thanks for expressing interest! There is also already a PR open for solving this at the moment (#1351) , though, so we should be fine here

**Comment by natalieparellano** [comment]
Closing as #1351 was merged.
