### ISSUE TITLE
Detect docker endpoint from docker context

### ISSUE THREAD

**Issue by jylin** [buildpacks/pack#1346]
When using [Docker rootless](https://docs.docker.com/engine/security/rootless/#client), the endpoint that should be used is not the default `/var/run/docker.sock` location. Instead docker CLI can be pointed to a different (context)[https://docs.docker.com/engine/security/rootless/#client]), which defaults to another location like `unix:///run/user/1000/docker.sock`.

The Docker CLI uses context for defaults, so there is no need to set DOCKER_HOST variable if you run `docker context use rootless` first. Can `pack` lookup the default endpoint from docker context if DOCKER_HOST is not set? This would make it consistent with the docker CLI.

**Comment by jromero** [comment]
Thanks @dmikusa-pivotal , you provided answers to questions that immediately come to my mind. It seems like this is a docker CLI specific implementation. I'd be okay with integrating with it.

@matejvasek does postman have something similar?

**Comment by holyjak** [comment]
I too am running into this problem (with Docker Desktop for Mac), where `pack build ...` fails to connect b/c I have no `/var/run/docker.sock` - but the `docker` CLI itself works just fine. Thhe docker context explains why it is the case:

```bash
$ docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                 KUBERNETES ENDPOINT                                 ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                     https://kubernetes.docker.internal:6443 (default)   swarm
desktop-linux *     moby                                                          unix:///Users/me/.docker/run/docker.sock
$ docker context show
desktop-linux
```

so the `default` context uses the standard socket but is not active and the socket does not exist. Instead, the active context is `desktop-linux`, which uses a socket in the user's home dir (which does exist).

**Comment by jjbustamante** [comment]
Duplicated of #1830

**Comment by jjbustamante** [comment]
Closing this one in favor of #1830
