### ISSUE TITLE
Override UID for container

### ISSUE THREAD

**Issue by jylin** [buildpacks/pack#1347]
`pack` supports a `--gid` flag, but why does it not support a `--uid` flag?

I would like to override the default UID that's used  because in docker rootless mode, the mappings are different (the 0 uid maps to the user running the docker daemon).

**Comment by aemengo** [comment]
Perhaps we could collapse the fields like docker does

```man
$ docker run --help
...
 -u, --user string                    Username or UID (format: <name|uid>[:<group|gid>])
...
```
