### ISSUE TITLE
Buildpacks are not aarch64?

### ISSUE THREAD

**Issue by Xantios** [buildpacks/pack#1374]
### Summary
I run a Ubuntu VM through Vmware on a Apple M1 machine. i run Docker inside that VM and want to use pack. however when i try to run pack lifecycle dies with the error `standard_init_linux.go:228: exec user process caused: exec format error`

---

##### Steps

1. Install vmware Fusion Tech Preview
2. install ubuntu & docker VM
3. make pack from source because aarch64 is not yet availbe out of the box

##### Current behavior
`standard_init_linux.go:228: exec user process caused: exec format error`

##### Expected behavior
To grep aarch64 available images when available, use the --platform option otherwise? of maybe spit out an error? 

---

##### pack info
```Pack:
  Version:  0.0.0+git-79a40b7
  OS/Arch:  linux/arm64

Default Lifecycle Version:  0.13.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8

Config:
  default-builder-image = "[REDACTED]"```

##### docker info
```
Containers: 33
 Running: 5
 Paused: 0
 Stopped: 28
Images: 123
Server Version: 20.10.12
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
 userxattr: false
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
runc version: v1.0.2-0-g52b36a2
init version: de40ad0
Security Options:
 apparmor
 seccomp
  Profile: default
 cgroupns
Kernel Version: 5.13.0-28-generic
Operating System: Ubuntu 21.10
OSType: linux
Architecture: aarch64
CPUs: 8
Total Memory: 15.59GiB
Name: dockerdoos
ID: ECPX:TOLJ:KBUO:QEET:2OAR:ZIPW:BEVR:NJNB:32G7:A5MB:2T7J:6B25
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**Comment by natalieparellano** [comment]
@Xantios do you need to run `pack` inside the VM? `pack build` should work on Apple M1s if you are using emulation.

**Comment by natalieparellano** [comment]
Closing as the lifecycle has linux-arm64 support for some time and there is a (limited) set of linux-arm64 buildpacks available. For more information on our multi-arch efforts, please see https://github.com/buildpacks/pack/issues/1570
