### ISSUE TITLE
Feature Request: Support exporting images to a `containerd` socket

### ISSUE THREAD

**Issue by spkane** [buildpacks/pack#1393]
### Description
It is more and more common not to have a local Docker daemon available and during certain testing cycles pushing to a registry is not always easy or desirable.

It would be great if you could easily create a buildpack and then export the results directly into a containerd namespace.

### Proposed solution
Extend `pack` and the underlying `creator` command so that it is possible to pass in something like `-containerd k8s.io`, which will then tell the `export` step to push the results into that containerd namespace instead of into a Docker registry or daemon.

### Describe alternatives you've considered
Many hacks that require running Docker, exporting to docker, pull out the image, and then re-pushing it into containerd.

**Comment by spkane** [comment]
Cross-posted here: https://github.com/buildpacks/lifecycle/issues/829

Feel free to close one or the other, but I wasn't sure which location was best, and whether both tools would need related changes.

**Comment by spkane** [comment]
It looks like some discussion about adding this will be included in the RFCs that are mentioned here:
https://github.com/buildpacks/lifecycle/issues/829#issuecomment-1069624845

**Comment by jromero** [comment]
Closing this one in favor of conversations happening in https://github.com/buildpacks/lifecycle/issues/829
