### ISSUE TITLE
[RFC #0081] Display process working directory

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1397]
When buildpack api >= 0.8, the process working directory is configurable. This information is in the `io.buildpacks.build.metadata`, so it could be displayed when running `pack inspect`.

**Comment by jromero** [comment]
@natalieparellano do you have references to any additional documentation? Curious how this is a Buildpack API change as oppose to Distribution or Platform regarding the changes to labels.

**Comment by natalieparellano** [comment]
@jromero this is a platform change - but the information will only show up for buildpacks that are on the newer api.

**Comment by jromero** [comment]
Sorry, I created a duplicate here: https://github.com/buildpacks/pack/issues/1422

Closing this one.
