### ISSUE TITLE
[Windows] fails to export while backing up cache due to rename

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#1423]
### Summary

Unable to build sample app with sample builder on Windows containers.

See [output.txt](https://github.com/buildpacks/pack/files/8496703/output.txt)

---

##### Steps

```
pack build sample-app --path . --builder cnbs/sample-builder:dotnet-framework-2004 --trust-builder -v
```

Where `--path .` is https://github.com/buildpacks/samples/tree/main/apps/aspnet

##### Current behavior

Container is built and saved to daemon.

##### Expected behavior

```
===> EXPORTING
...
ERROR: failed to export: saving image: failed to commit cache: backing up cache: rename c:\launch-cache\committed c:\launch-cache\committed-backup: The system cannot find the path specified.
ERROR: failed to build: executing lifecycle: failed with status code: 62
```

---

##### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 120
  Running: 1
  Paused: 0
  Stopped: 119
 Images: 351
 Server Version: 20.10.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2009 (OS Build 19043.1586)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.81GiB
 Name: DRAKE
 ID: 3VBS:BAXF:RH4W:GZ3H:3DGP:5OFB:3OCO:UPD5:XDF7:67ZW:IA6K:KMIC
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by jromero** [comment]
Unable to reproduce on:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/475559/163845482-82b7b1f3-feca-49e9-aac2-4ab615031946.png">

Command:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/475559/163845519-df388ee4-4ee2-42b6-9e45-a91b6a757a08.png">

Ending Output:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/475559/163845680-0dad0e2f-6ddb-424a-9a4f-e740e872b5b9.png">

**Comment by jromero** [comment]
@macsux we're still unable to reproduce this issue. Is there anything you can think of that might help us here?

**Comment by macsux** [comment]
No, but another SE with same version of windows got exact same error when I asked him to try

**Comment by jromero** [comment]
After some deep diving, we found this to be an issue that's plagued Windows containers for quite some time. See https://github.com/moby/moby/issues/38256.

It's worth noting that this was only reproducible using `--process=isolation` and not hyper-v (on very specific Windows versions). At this point in time, enabling hyper-v support is out of the scope of our expertise. 

As a workaround, [the lifecycle is graciously changing its implementation of how it handles caching](https://github.com/buildpacks/lifecycle/pull/850) but we understand that this is a band-aid solution until either Windows resolves its underlying issue or `pack` can support hyper-v.
