### ISSUE TITLE
Option for relaxing the constraint that the stack id for the builder, run, and build image must all match

### ISSUE THREAD

**Issue by spew** [buildpacks/pack#1440]
### Description
We have pre-existing run images, each with a different stack id, that we would like to use with a single builder. Since a builder can only have a single stack id it is impossible for us to use all of the run images with pack's `--run-image` parameter.

### Proposed solution
The proposed solution is to add a new parameter, something like, `--run-image-stack-policy` with options like:
  * `must-match`: the run image must match the builder image's stack id (the current behavior)
  * `allow-any`: the run image's stack does not need to match

### Describe alternatives you've considered
It may be that we would want the parameter to be even more general purpose and name it `--stack-policy` with more options.

**Comment by natalieparellano** [comment]
This may be obsoleted by https://github.com/buildpacks/rfcs/blob/main/text/0096-remove-stacks-mixins.md when implemented.

**Comment by natalieparellano** [comment]
@hone @dfreilich I marked this one as blocked, but feel free to pull it in for discussion if you feel differently

**Comment by natalieparellano** [comment]
Closing now that stack removal has been implemented and shipped in lifecycle 0.17.0 and pack 0.30.0
