### ISSUE TITLE
pack 0.27 identified as Trojan:Script/Wacatac.B!ml on Windows 11 by Microsoft defender

### ISSUE THREAD

**Issue by Langohr23** [buildpacks/pack#1454]
Hello,

I just tried to download pack on my windows 11 PC. Here Microsoft Defender is thinking to detect the Virus Trojan:Script/Wacatac.B!ml. Screenshot is in German, but I hoe the important information can be extracted:
![image](https://user-images.githubusercontent.com/33636936/173225692-2074895e-0c3e-4f61-9d3e-c848ecd61378.png)
 
Thank you and best regards

Thomas

**Comment by jromero** [comment]
Hi @Langohr23, I noticed that you pulled the latest rc version. Are you seeing this on other versions as well? For example, [v0.26.0](https://github.com/buildpacks/pack/releases/tag/v0.26.0)?

While we investigate, this particular report we will be removing the reported artifact from the release. Thank you for the report.

**Comment by jromero** [comment]
@Langohr23 Could you verify the checksum of the file you downloaded? The command on PowerShell or CMD should be:

```
certutil -hashfile pack-v0.27.0-rc1-windows.zip sha256
```

**Comment by jromero** [comment]
After investigating our pipelines and the reported asset we believe this to be a false-positive. _Unless you can confirm that the checksum is different, in which case, it may have been a man-in-the-middle attack/injection._

We ran the reported asset through VirusTotal to have it [scanned via multiple tools](https://www.virustotal.com/gui/file/0f60358168021239a72fd1e3659a02e5da8432a5df264b37730efba952056ad2/detection) and although it did indeed pick up 2 potential threads they appear to be very likely false-positives as discussed [here](https://github.com/lian/msfs2020-go/issues/14#issue-686881175) and documented [here](https://go.dev/doc/faq#virus). We further confirmed that none of our pipelines or GH accounts had been compromised.

As a result, we will be putting the asset back on the release and continue forward with the next release of [pack 0.27.0](https://github.com/buildpacks/pack/milestone/40).

Please feel free to reply with any additional comments, information or concerns.
