### ISSUE TITLE
It would be nice to support easily creating a manifest list packages and builders

### ISSUE THREAD

**Issue by dmikusa** [buildpacks/pack#1460]
### Description

If I am building, for example, `paketo-buildpacks/java` and I want to support multiple os/architectures I would like those to be supported under the same image name. This requires support for a manifest list. I would like pack to handle this for me, rather than needing additional tools.

This is not strictly dependent on #1459 but as it becomes easier to create images for different os/architectures it'll be more apparent that we need the ability to have pack create a manifest list.

### Proposed solution

I feel like there are some options here.

1. I could see a command that's run which when given multiple images produces a single manifest list image. That would require you to independently `pack buildpack package` each os/arch buildpack image, then combine them together. This would be a little tedious, but it would be easy to consume. A buildpack author could a.) compile their buildpack, b.) package it with pack, c.) repeat as needed, d.) call `pack buildpack manifest` (or something like that).

2. I could see this being more closely integrated with #1459. That when you pass multiple `--arch` flags (or whatever flag), or when you have multiple architectures listed in package.toml (or where ever), then pack would know to generate a manifest image. I think this would be convenient in that you could possibly get away with only one call to `pack buildpack package`. It would be a little different to consume though. A buildpack author would need to a.) compile their buildpack for every architecture , b.) call `pack buildpack package` and somehow tell pack where each compiled buildpack resides. Right now there's a single `uri` in package.toml to do this, so you'd presumably need something that's architecture-specific or need some other way to pass that along.

### Describe alternatives you've considered

I have heard via @jromero that it is possible to use 3rd party tools to combine different images into a manifest image, but I haven't tried this or found any documented steps for doing it.

### Additional context
- [x] This feature should be documented somewhere

**Comment by zeus2611** [comment]
Hi @jjbustamante @jpena-r77  I'm very interested in this project for lfx mentorship '23. I learned about buildpacks from CNCF's LFX idea list, which I think is a higher-level abstraction of container image. It just so happens that the technology stack of the project fits me pretty well. i have been working with golang for sometime now. And, I think this would give me a perfect opportunity for getting started with open source and expanding my knowledge and skillset.
