### ISSUE TITLE
pack should support `pack extension *` commands

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1470]
`pack extension --help` should show (analogously to `pack buildpack --help`):

```
  inspect     Show information about an extension
  package     Package an extension in OCI format. <- made a separate issue, please see https://github.com/buildpacks/pack/issues/1489
  new         Creates basic scaffolding of an extension.
  pull        Pull an extension from a registry and store it locally
  register    Register an extension to a registry
  yank        Yank an extension from a registry
```

We should probably make a separate issue for each one of these commands, as they could be implemented separately.

Edit: Made a separate issue (https://github.com/buildpacks/pack/issues/1489) for `pack extension package`.

**Comment by natalieparellano** [comment]
Ah - this is to provide similar functionality to what you get with `pack buildpack package` (for distribution purposes). It is less important than #1468 but I added it for completeness.

**Comment by natalieparellano** [comment]
Blocking on https://github.com/buildpacks/rfcs/pull/173 getting approved and merged.

**Comment by oovk** [comment]
Hi @natalieparellano I'm new to this repo. Can you please guide me to appropriate code part? and a bit of explanation about the issue would be really helpful!

**Comment by natalieparellano** [comment]
@oovk it would be awesome to get your help on this! At a high level, this is about creating a `pack extension package` command that is analogous to `pack buildpack package`, except for "extensions" - a new experimental CNB component described in https://github.com/buildpacks/rfcs/pull/173.

From a `pack` perspective, extensions are very similar to buildpacks, except they have an extension.toml (instead of a buildpack.toml). The output of `pack extension package` should be either a .cnb file or an OCI image, just like `pack buildpack package`. A good place to start might be [here](https://github.com/buildpacks/pack/blob/main/internal/commands/buildpack_package.go).

How does that sound? Let us know if you'd like this issue assigned to you!

**Comment by itsdarshankumar** [comment]
@natalieparellano can you please assign me issue #1470 or #1489 or similar to pack extension, i'm guessing they would be a good first issue for me

**Comment by itsdarshankumar** [comment]
@natalieparellano can you please open up an issue for the implementation of inspect command, I'll now try my hands to implement it

**Comment by natalieparellano** [comment]
Reopening as we now have `--help` but still need:

```
pack extension package
pack extension new
```

(We can skip the registry stuff for now - that requires further thought)

**Comment by natalieparellano** [comment]
`pack extension package` was implemented in https://github.com/buildpacks/pack/issues/1635

`pack extension new` can be tracked in https://github.com/buildpacks/pack/issues/1636

Closing this meta issue in favor of the individual issue.
