### ISSUE TITLE
Allow setting a folder prefix for volumes created automatically

### ISSUE THREAD

**Issue by NathanJAdams** [buildpacks/pack#1481]
### Description
Allow buildpacks to work on BitBucket pipelines on BitBucket's runners. Currently they error out with
`ERROR: failed to build: executing lifecycle: failed to create 'creator' container: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories`

### Proposed solution
Allow setting a folder prefix for volumes created automatically

### Describe alternatives you've considered
Running on an on-prem runner. This does work as on-prem has no security concerns that add restrictions

### Additional context
None

**Comment by jromero** [comment]
@NathanJAdams thank you for filling this issue. This issue should be resolved as part of [ongoing work](https://github.com/buildpacks/pack/issues/1077) that will be released in the next version of pack.

More specifically, these issues:
- https://github.com/buildpacks/pack/issues/1473
- https://github.com/buildpacks/pack/issues/1474


Closing this as covered by https://github.com/buildpacks/pack/issues/1077.
