### ISSUE TITLE
Build packs seems to be detecting my app as PHP today instead of Node

### ISSUE THREAD

**Issue by philipwigg** [buildpacks/pack#1482]
### Summary

Build packs seems to be detecting my application as a PHP app when it's a NodeJS application.

I'm deploying a NodeJS Cloud Run application from source. To deploy it, I use:-

```
gcloud run deploy my-app-nane \
  --source . \
  --project my-project \
  --platform managed \
  --allow-unauthenticated \
  --region europe-west2
```

It's been working fine for months. I've only made minor changes to the code.

However, build packs seem to be detecting my node application as a PHP app and not Node anymore and my app fails with FastCGI errors (which I should not have installed).

See the comparison (today vs about 11 days ago)

![nodephp](https://user-images.githubusercontent.com/244059/179957676-b49151ee-12fa-4422-986e-d5e939c8f252.png)

---

##### Steps
I'm not sure how you can reproduce this without handing over my source code, but this must be happening to others?

**Comment by dfreilich** [comment]
That's an issue not with the `Pack` CLI, but instead with the buildpacks used (which, as you can see, are Google's). The repo for that can be found here: https://github.com/GoogleCloudPlatform/buildpacks. I'm closing this issue in favor of opening an issue there

**Comment by philipwigg** [comment]
I really appreciate the swift response, @dfreilich. Hope opened an issue in the GCP buildpacks. Thanks!
