### ISSUE TITLE
`pack inspect` when image built with extensions should show the extensions

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1486]
This output should include `Extensions` if extensions were used:

```
$  pack inspect hello-extensions
Inspecting image: hello-extensions

REMOTE:
(not present)

LOCAL:

Stack: io.buildpacks.samples.stacks.alpine

Base Image:
  Reference: 17eeba339127d21e62348fe7692bc6ba04f988be690d0cecd249e940efb90141
  Top Layer: sha256:ee08c026c070425ca3aa6e49e07338ab4eee589f7ce35bb921832b6013d39f49

Run Images:
  cnbs/sample-stack-run:alpine

Buildpacks:
  ID                              VERSION        HOMEPAGE
  samples/hello-extensions        0.0.1          https://github.com/buildpacks/samples/tree/main/buildpacks/hello-extensions

Processes:
  TYPE                  SHELL        COMMAND        ARGS
  curl (default)                     curl           --version
```

**Comment by jalajk24** [comment]
hey @natalieparellano, i am interested to contribute in this issue could you plz drop some insight as i am new to open source and this will be my first project

**Comment by natalieparellano** [comment]
@jalajk24 it would be awesome to get your help here!

At a high level, when inspecting the image, pack:
* Reads the `io.buildpacks.build.metadata` label from the image
* Parses the data from that label - see [here](https://github.com/buildpacks/pack/blob/558ae9a3c7e51f1e4e15aaa54bf90e9ca7f164a8/pkg/client/inspect_image.go#L180) for how it is done for buildpacks
* Renders the data - see [here](https://github.com/buildpacks/pack/blob/558ae9a3c7e51f1e4e15aaa54bf90e9ca7f164a8/internal/inspectimage/info_display.go#L131) for how we update buildpack info and [here](https://github.com/buildpacks/pack/blob/558ae9a3c7e51f1e4e15aaa54bf90e9ca7f164a8/internal/inspectimage/writer/human_readable.go#L119) for how we display it in a "readable" format

I think the changes required here would largely involve copying what we have for buildpacks and updating it so that it's valid for extensions.

It's worth noting - this [open PR](https://github.com/buildpacks/pack/pull/1547) for platform 0.10 support introduces some changes to the way inspect image is working (updating the lifecycle library code that is imported) and you probably want those changes to land before introducing others. I'm actively working to fix up the open PR today and hopefully it will be merged soon. If you wanted to branch off `platform-0.10` for now I think that would be okay as the remaining stuff that I'm fixing won't intersect with the inspect image code.

Thanks again for your help and please don't hesitate to reach out with any further questions!

**Comment by Abhi149209** [comment]
hey , can I contribute to this issue ? 
I am begineer but I can resolve this

**Comment by Abhi149209** [comment]
tell me the setup , as I could not find that

**Comment by natalieparellano** [comment]
@jalajk24 were you still interested in taking this up? Please let us know... otherwise @Abhi149209 you are welcome to claim it - https://github.com/buildpacks/pack/blob/main/DEVELOPMENT.md will have useful information for configuring your setup.

**Comment by jalajk24** [comment]
@natalieparellano yes i am interested in this plz assign it to me.
