### ISSUE TITLE
`pack builder inspect` should show extensions if they are present

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1488]
It should show `Extensions:` and `Detection Order (Extensions):`

**Comment by theVJagrawal** [comment]
Can i work on this one?

**Comment by natalieparellano** [comment]
@theVJagrawal that would be awesome! You might want to work off of https://github.com/buildpacks/pack/pull/1478 or wait for that to be merged (it's currently blocked on a few small changes, I'll fix it up shortly!). 

https://github.com/buildpacks/pack/blob/main/internal/builder/inspect.go should be a nice trailhead - but please don't hesitate to reach out if you have any questions.

**Comment by Abhi149209** [comment]
can I work on this ?

**Comment by Abhi149209** [comment]
tell me the setup , as I could not find that

**Comment by natalieparellano** [comment]
@ @theVJagrawal were you still interested in taking this up? Please let us know... otherwise @Abhi149209 you are welcome to claim it - https://github.com/buildpacks/pack/blob/main/DEVELOPMENT.md will have useful information for configuring your setup.

**Comment by Abhi149209** [comment]
@natalieparellano i cannot get the setup process , I need to run this project on my laptop . Can you guide .

**Comment by natalieparellano** [comment]
@Abhi149209 I think the link I provided will have everything you need (details for installing git, go, docker, and make, etc). Alternatively, you can use Gitpod (also linked on the referenced page) to develop in the browser - I just checked the setup and it seems to be working fine, although it seems a little slow.

**Comment by Abhi149209** [comment]
@natalieparellano please assign me

**Comment by harikannan512** [comment]
Hi @natalieparellano, 

Can I have a go at this issue? I can see in the main branch that the `inspect` method has not been changed, I was wondering if it was still being worked on. If not, can you please assign this issue to me?

Thnanks

**Comment by Gauravkumar2701** [comment]
@natalieparellano Dear natalieparellano I am interested in working on this issue so could you please guide me with more information.

**Comment by natalieparellano** [comment]
May be closed by https://github.com/buildpacks/pack/pull/1581
