### ISSUE TITLE
x86_64 lifecycle installed on arm64 builder created by pack

### ISSUE THREAD

**Issue by jpena-r7** [buildpacks/pack#1518]
### Summary

When creating a builder on an arm64 host using the arm64 release of pack (0.27.0) the x86_64 lifecycle is installed.

---

##### Steps

I have a multi-arch amazonlinux:2 stack that I created for testing support for non-ubuntu stacks. Feel free to use it for testing as well.

https://github.com/jericop/amazonlinux-stack

Below are the steps to reproduce the issue. The same issue occurred when I omitted the lifecycle from the custom-builder.toml file.

```
$ cat << EOF > custom-builder.toml
description = "Amazon Linux 2 base builder with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.14.1"

[stack]
  build-image = "jericop/amazonlinux-build:base-cnb"
  id = "io.buildpacks.stacks.amazonlinux"
  run-image = "jericop/amazonlinux-run:base-cnb"
EOF
$ 

$ pack builder create local-arm-builder --config custom-builder.toml 
Warning: builder configuration: empty order definition
base-cnb: Pulling from jericop/amazonlinux-run
Digest: sha256:f4e33a89725f6a9aa47dc28ae36ed32595db78d1eef28155fd75511199eb2238
Status: Image is up to date for jericop/amazonlinux-run:base-cnb
base-cnb: Pulling from jericop/amazonlinux-build
f5371f42f94d: Already exists 
4a8b058dc96d: Already exists 
3f3de78de879: Pull complete 
53f4abc6edad: Pull complete 
Digest: sha256:d775ff59e9b4a4a8e9e0c2449114fafe5b183be68115263679940c1782984589
Status: Downloaded newer image for jericop/amazonlinux-build:base-cnb
Successfully created builder image local-arm-builder
Tip: Run pack build <image-name> --builder local-arm-builder to use this builder

$ docker run -it --rm --entrypoint /cnb/lifecycle/lifecycle local-arm-builder
exec /cnb/lifecycle/lifecycle: exec format error
$ 
```

This fixes the issue by copying the lifecycle from the lifecycle image (on the correct architecture).

```
$ cat << EOF > Dockerfile
FROM local-arm-builder
COPY --from=buildpacksio/lifecycle:0.14.1 /cnb/ /cnb/
EOF
$ 

$ docker build -t updated-local-arm-builder .
Sending build context to Docker daemon    549MB
Step 1/2 : FROM local-arm-builder
 ---> 80c1d1fbd6f6
Step 2/2 : COPY --from=buildpacksio/lifecycle:0.14.1 /cnb/ /cnb/
 ---> 2e9a6d685f3f
Successfully built 2e9a6d685f3f
Successfully tagged updated-local-arm-builder:latest
$ 

$ docker run -it --rm --entrypoint /cnb/lifecycle/lifecycle updated-local-arm-builder
ERROR: failed to parse arguments
$ 

```

##### Current behavior

x86_64 lifecycle is added to the builder

##### Expected behavior

arm64 lifecycle should be added to the builder

---

##### pack info

```
Pack:
  Version:  0.27.0+git-f4f5be1.build-3382
  OS/Arch:  linux/arm64

Default Lifecycle Version:  0.14.1

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9

Config:
(no config file found at /root/.pack/config.toml)
```

##### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 15
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.209-116.367.amzn2.aarch64
 Operating System: Alpine Linux v3.16 (containerized)
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 30.95GiB
 Name: testing-system
 ID: M3OT:ITKC:4QLS:ADKA:7JNS:CWVW:H4XD:I7LA:U33Q:DAZK:POC2:BREN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine


```

**Comment by jpena-r7** [comment]
This is related to the following PR, which was not able to be fully tested due to limited access to an arm machine.
https://github.com/buildpacks/pack/pull/1216

**Comment by edmorley** [comment]
So the issue appears to be that #1216 only fixed the untrusted builder case, whereas in the happy case (trusted builder), the lifecycle used is the lifecycle added during builder image creation. 

That lifecycle binary is pulled via the URL generated here:
https://github.com/buildpacks/pack/blob/2138b9f70d36aa7ecd81f8c0c3a402d6cd61d6ae/pkg/client/create_builder.go#L266-L272

...which is called from:
https://github.com/buildpacks/pack/blob/2138b9f70d36aa7ecd81f8c0c3a402d6cd61d6ae/pkg/client/create_builder.go#L173-L186

It seems that `fetchLifecycle` and `uriFromLifecycleVersion()` need to gain an additional `arch` argument (alongside the existing `os` arg), which is determined by `baseImage..Architecture()` in `createBaseBuilder()` - similar to what's done for the untrusted case.

In the linux arm64 case, the URL would then need to map to:
`https://github.com/buildpacks/lifecycle/releases/download/v%s/lifecycle-v%s+linux.arm64.tgz`

Instead of:
`https://github.com/buildpacks/lifecycle/releases/download/v%s/lifecycle-v%s+linux.x86-64.tgz`

**Comment by jericop** [comment]
Thanks for shedding more light on why this is happening. It is helpful context, especially for someone new to the project. I plan to put together a PR for this, unless someone beats me to it. 😄

**Comment by jpena-r7** [comment]
Thanks for shedding more light on why this is happening. It is helpful context, especially for someone new to the project. I plan to put together a PR for this, unless someone beats me to it. 😄
