### ISSUE TITLE
Pack build silently ignores `--lifecycle-image` if the builder is trusted

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#1540]
### Summary
The `--lifecycle-image` argument to `pack build` allows for specifying a custom `lifecycle` image to use.

However, this argument is silently ignored if the builder is trusted.

Whilst the usage text hints that the option is mainly intended for untrusted builders, the fact it (a) doesn't work for trusted builders, (b) there is no warning or error about the fact it's ignored if used, was surprising.

This caused confusion when trying to debug a potential lifecycle regression, when I was using `--lifecycle-image` in an attempt to try different lifecycle versions to find a regression range.

---

##### Steps

1. `pack config trusted-builders add heroku/builder-classic:22`
2. `touch requirements.txt`
3. `pack build --verbose --builder heroku/builder-classic:22 --lifecycle-image buildpacksio/lifecycle:0.14.3 testapp`

##### Current behavior

`--lifecycle-image` is ignored, and the build is performed using the default lifecycle version instead, with no indication of this (eg a warning or error) being shown in the build logs.

##### Expected behavior

Either:
- `--lifecycle-image` still works if the builder is trusted (and so the build is performed using the requested lifecycle version)
- Or, using `--lifecycle-image` with a trusted builder results in an warning that it's being ignored.
-  Or, using `--lifecycle-image` with a trusted builder results in an error that explains the combination of trusted + `--lifecycle-image` is not permitted.

---

##### pack info
```
Pack:
  Version:  0.27.0+git-f4f5be1.build-3382
  OS/Arch:  darwin/arm64

Default Lifecycle Version:  0.14.1

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9

Config:
  default-builder-image = "[REDACTED]"
  experimental = true

  [[trusted-builders]]
    name = "[REDACTED]"
```

##### docker info
N/A

**Comment by natalieparellano** [comment]
A warning seems appropriate and would be easy to add

**Comment by dfreilich** [comment]
Good catch! PRs are welcome 😄

**Comment by cgoxo** [comment]
Can I work on this issue? I don't know a lot about how to proceed with this.

**Comment by natalieparellano** [comment]
@cgoxo it would be awesome to get your help here! Here are a few code links that might be helpful:
* https://github.com/buildpacks/pack/blob/8f8cdb3b912a667e13cc9174d0f0dbcaa2594478/internal/commands/build.go#L103 is where we determine if the builder is trusted
* https://github.com/buildpacks/pack/blob/8f8cdb3b912a667e13cc9174d0f0dbcaa2594478/internal/commands/build.go#L124-L131 is where we read the user-provided lifecycle image
* https://github.com/buildpacks/pack/blob/8f8cdb3b912a667e13cc9174d0f0dbcaa2594478/internal/commands/build_test.go#L213 is a test that verifies a warning is printed

**Comment by cgoxo** [comment]
Thank you @natalieparellano!
