### ISSUE TITLE
Getting started guide did not get me started

### ISSUE THREAD

**Issue by githubcdr** [buildpacks/pack#1558]
### Summary

As a news user I can't get the sample to work

### Reproduction

Follow the getting started guide

##### Steps

pack build my-app --buildpack paketo-buildpacks/nodejs \                                   ✔
  --builder heroku/buildpacks:20

ERROR: failed to build: invalid builder heroku/buildpacks:20: builder index.docker.io/heroku/buildpacks:20 missing label io.buildpacks.builder.metadata -- try recreating builder

##### Current behavior

I would expect to have valuable info what is going wrong, is this my fault, is this a bug?

##### Expected behavior

---

**Comment by natalieparellano** [comment]
@githubcdr I think this may be due to mixing Paketo buildpacks with the Heroku builder. Can you try `pack build my-app --buildpack paketo-buildpacks/nodejs --builder paketobuildpacks/builder:base`?

**Comment by natalieparellano** [comment]
Potentially related to: https://cloud-native.slack.com/archives/C033DV8D9FB/p1669661365879809

@githubcdr could you please also provide your pack info and docker info?

**Comment by natalieparellano** [comment]
Potentially related to: https://github.com/buildpacks/pack/issues/1519

From Slack: disabling experimental containerd image store may fix the "missing label" problem

**Comment by githubcdr** [comment]
Thanks, I will give this a try

**Comment by githubcdr** [comment]
As mentioned in the other issue, it works when disabling the containerd flag in Docker on Mac!
