### ISSUE TITLE
run pack CLI in container without docker daemon/podman

### ISSUE THREAD

**Issue by yilims** [buildpacks/pack#1559]
### Description
Currently pack CLI requries docker daemon/podman, it's very different to use it to build OCI image in container environment.

### Proposed solution
pack CLI can be run in container envrionment without docker daemon/podman

### Describe alternatives you've considered
I have tried to run pack CLI in a public cloud container environment  via [Docker in Docker](https://shisho.dev/blog/posts/docker-in-docker/) , unfortunately the cloud platform doesn't support run container in privileged mode or mount host file for "/var/run/docker.sock".
It looks like buildpacks [lifecycle](https://github.com/buildpacks/lifecycle) uses [go-containerregistry](https://github.com/google/go-containerregistry) which doesn't depends on docker daemon. If pack cli remove the docker daemon dependency, it can be deployed in container easily.

**Comment by dfreilich** [comment]
For users who want to build in environments where docker daemons isn't available, we recommend just using the lifecycle directly. You can see how we invoke it in our `Tekton` task definition [here](https://github.com/buildpacks/tekton-integration/blob/main/task/buildpacks/0.4/buildpacks.yaml#L125-L150)

**Comment by yilims** [comment]
@dfreilich: Awesome, that's what I was looking for, Really appreciated for your help!
