### ISSUE TITLE
Multi arch image build support

### ISSUE THREAD

**Issue by Rajpratik71** [buildpacks/pack#1570]
### Description
Support to specify arch and build images for multiple arches

### Describe alternatives you've considered
I wanted to build a spring boot application as a container image for "arm64", I used pack cli, which built the image but only for "x86" i.e "amd64" arch.

So, I used "docker buildx" as an alternative to build multi-arch images. 

### Additional context
- [x] This feature should be documented somewhere

**Comment by jjbustamante** [comment]
Hi, @Rajpratik71 thanks for creating this issue! I think they are related to #1460 and #1459 

Also, recently Aidan present the following [talk](https://www.youtube.com/watch?v=Sdr5axlOnDI) at Kubecon US where he actually mentioned the ideas behind the multi-architecture we want to explore. Also, will be great if you can join the ARM slack [channel](https://cloud-native.slack.com/archives/C032LNSMY0P)

**Comment by Rajpratik71** [comment]
Sure thanks @jjbustamante

**Comment by jjbustamante** [comment]
I am marking this issue as `in-progress` because the following open [RFC](https://github.com/buildpacks/rfcs/pull/283) also we have a [PR](https://github.com/buildpacks/pack/pull/1705) on pack to support these commands, even this is not the final solution, it is the first step to start working on the idea to support multi-arch buildings

**Comment by Jay179-sudo** [comment]
Hi! I'd like to work on this for the upcoming LFX term😀! Could you please guide me on how to get started with this issue?

**Comment by jjbustamante** [comment]
With the release of `0.34.x` we included:
- [Manifest commands|https://github.com/buildpacks/pack/pull/1705]
- [Support](https://github.com/buildpacks/pack/pull/2086) for creating multi-platform builders and buildpacks
- New `--platform` [flag](https://github.com/buildpacks/pack/pull/2162) when running `pack build` for users on M1 machines to be able to create amd64 and arm64 images. We are experimenting with Buildkit to see how far we can go with it. 
Supporting multi-platform buildpacks is a task on Buildpack Authors, [Paketo](https://paketo.io/) already started publishing their buildpacks for amd64 and arm64 architecture.
