### ISSUE TITLE
Replace directive break command install

### ISSUE THREAD

**Issue by AidanDelaney** [buildpacks/pack#1574]
### Summary
Installing pack using `go install github.com/buildpacks/pack/cmd/pack@latest` fails due to the `replace` directives in `go.mod`

---

##### Steps

1. Run `go install github.com/buildpacks/pack/cmd/pack@latest`
  ```
  go: github.com/buildpacks/pack/cmd/pack@latest (in github.com/buildpacks/pack@v0.28.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
  ```
3. Notice the same failure with `go install github.com/buildpacks/pack/cmd/pack@v0.28.0`
  ```
  go: github.com/buildpacks/pack/cmd/pack@v0.28.0 (in github.com/buildpacks/pack@v0.28.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
  ```
4. However, `go install github.com/buildpacks/pack/cmd/pack@v0.27.0` succeeds

##### Current behavior
The installation fails with an error that mentions "replace directives"

##### Expected behavior
The expected behavior is the same as the behavior in `go install github.com/buildpacks/pack/cmd/pack@v0.27.0`

---

##### pack info
N/A

##### docker info
N/A

**Comment by natalieparellano** [comment]
Sadly I don't think there's an easy way to work around this; this thread has more: https://github.com/golang/go/issues/44840#issuecomment-1267360628

Can we install pack using an alternate method in the docs CI?

**Comment by hone** [comment]
@natalieparellano in order to remove the replace directives, do we have to not user kaniko?

**Comment by natalieparellano** [comment]
@hone I believe so, yes

**Comment by samj1912** [comment]
I see docker has now moved to a vendor.mod file which doesn't have any replace directives. If kaniko were to update its versions, would we be able to get rid of the replacements?

**Comment by natalieparellano** [comment]
> I see docker has now moved to a vendor.mod file which doesn't have any replace directives. If kaniko were to update its versions, would we be able to get rid of the replacements?

Looks like those changes haven't been released yet - let's keep an eye on it...

**Comment by natalieparellano** [comment]
Let's check on this one after https://github.com/buildpacks/pack/pull/1696 is merged. Hopefully `go get` will work again and we can close it.

**Comment by jjbustamante** [comment]
I checked locally the following command:

``` bash
go install github.com/buildpacks/pack/cmd/pack@v0.30.0-rc2
```

We will close this issue once 0.30 is released

**Comment by jjbustamante** [comment]
Pack **0.30.0** was released! closing this one
