### ISSUE TITLE
Failure: (ID: 838926df) did not find any jar files with a Main-Class manifest entry

### ISSUE THREAD

**Issue by robin-varghese** [buildpacks/pack#1578]
Dear Team, 

I am trying to build a simple Spring MVC web application and deploy it into GKE. This web application is developed in Eclipse (Windows 10) and is a Maven project. It works as a normal web application and is running in Tomcat 10.1. In my local machine.

In order to Dockerize this application, I moved the app folder into GCP VM (Linux). I installed Docker, then Pack.
Then set the default builder as Google -> pack config default-builder  gcr.io/buildpacks/builder:v1
Then run Pack -> pack build <image-name>
I am getting below error message

Kindly help me to fix this issue. 

v1: Pulling from buildpacks/builder
Digest: sha256:b653eca355fda172df43fad3f04bd7be45bd5608092fbf8f3e012066886a121f
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:ea9b5b1e0fd5680b20b44323155c4648650768424a2194a7671807c86e6dc8b0
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
===> DETECTING
4 of 5 buildpacks participating
google.java.runtime    0.9.1
google.java.maven      0.9.0
google.java.entrypoint 0.9.0
google.utils.label     0.0.2
===> ANALYZING
Previous image with name "jsp-restclient-ui" not found
===> RESTORING
===> BUILDING
=== Java - Runtime (google.java.runtime@0.9.1) ===
Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
2022/12/21 10:14:39 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Installing  v11.0.17+8.
2022/12/21 10:14:39 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.17_8.tar.gz
=== Java - Maven (google.java.maven@0.9.0) ===
Installing Maven v3.6.3
--------------------------------------------------------------------------------
Running "bash -c curl --fail --show-error --silent --location --retry 3 https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar xz --directory /layers/google.java.maven/maven --strip-components=1"
Done "bash -c curl --fail --show-error --silent --location --retry..." (492.855612ms)
--------------------------------------------------------------------------------
Running "/layers/google.java.maven/maven/bin/mvn clean package --batch-mode -DskipTests -Dhttp.keepAlive=false -f=pom.xml --quiet"
Done "/layers/google.java.maven/maven/bin/mvn clean package --batc..." (44.437291969s)
=== Java - Entrypoint (google.java.entrypoint@0.9.0) ===
Failure: (ID: 838926df) did not find any jar files with a Main-Class manifest entry
--------------------------------------------------------------------------------
Sorry your project couldn't be built.
Our documentation explains ways to configure Buildpacks to better recognise your project:
 -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
If you think you've found an issue, please report it:
 -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
--------------------------------------------------------------------------------
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51

**Comment by dfreilich** [comment]
Thank you for reporting it! As you can see from the logs, that is an issue you're having with particular buildpacks (in this case, the Google buildpacks available for comment at https://github.com/GoogleCloudPlatform/buildpacks), and not with the pack cli. If you want further help, please open an issue on their repo and ask them for assistance, or try some of the other buildpacks (like the Paketo project or Heroku).
