### ISSUE TITLE
Support running pack Docker image on Cloud Build

### ISSUE THREAD

**Issue by mhoran** [buildpacks/pack#1579]
### Description
Currently it is not possible to run the `pack` Docker image on Cloud Build. This is because `/var/run/docker.sock` is owned and only accessible by root (and unnamed group 997) whereas the `pack` image runs as non-root.

A Skaffold version of a `pack` image, `gcr.io/k8s-skaffold/pack`, is often used to run `pack` on Cloud Build. Also, the Skaffold community is looking to deprecate this image: https://github.com/GoogleContainerTools/skaffold/issues/7146.

### Proposed solution
I have worked around this by adding a very clumsy build step to my `cloudrun.yaml`:
```
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/workspace:/workspace', '--user', 'root', 'buildpacksio/pack', 'build', '${_IMAGE_NAME}', '--builder', 'paketobuildpacks/builder-jammy-base', '--run-image', 'run', '-e', 'BP_GO_TARGETS=./cmd/server'] 
```

However, if there were some way to run the image as root, or better yet with a group that has access to the Docker socket, that would be better. I'm not sure what the best course of action would be here, though.

I did try to `chmod` the `docker.sock` in my `cloudbuild.yaml`. Unfortunately that did not work as `/var/run` is a read-only filesystem.

I'm not sure if the group `997` that I see in my Cloud Build is the universal group with access to the Docker socket. I'm also not sure how best to make that available to the `pack` Docker image.

One option would be to also distribute another `root` version of the `pack` image for this use case. It's not great, but it would at least unblock use of the image on Cloud Build as well as the deprecation of the Skaffold image.

### Describe alternatives you've considered
It's possible to run the `pack` Docker image manually with a `--user` flag, however this is not the best way to run steps in Cloud Build and makes debugging a bit more difficult.

**Comment by natalieparellano** [comment]
@dfreilich any thoughts here?

**Comment by jjbustamante** [comment]
Hi @mhoran 

Did you manage to workaround this issue or is it still valid?

**Comment by mhoran** [comment]
This is still an issue, and it looks like the work in Skaffold is still stalled. It would be great to have a proper solution for this in some way so I can get back on an up to date `pack` image.

**Comment by jjbustamante** [comment]
Hi @mhoran 

Is it possible for you to test the latest `0.30.0` pack version? I asked because I noticed the following, checking the *User* associated with the image, starting from this version, we are not setting it anymore. See the following

```bash
➜  ~ docker inspect buildpacksio/pack:0.28.0 | jq '.[] | .Config.User'
"1000:1000"
➜  ~ docker inspect buildpacksio/pack:0.29.0 | jq '.[] | .Config.User'
"1000:1000"
➜  ~ docker inspect buildpacksio/pack:0.30.0 | jq '.[] | .Config.User'
""
```
Maybe this should help when the pack container is executed on Cloud Build?

**Comment by mhoran** [comment]
I gave the latest version a try but it's now failing due to #1875.

**Comment by jjbustamante** [comment]
> I gave the latest version a try but it's now failing due to #1875.

Thanks @mhoran, we are taking a look on this!!

**Comment by jjbustamante** [comment]
@mhoran 

Could you also try [this](https://github.com/buildpacks/pack/issues/1875#issuecomment-1693417426) workaround?

**Comment by mhoran** [comment]
With `/tmp` mounted in this works now! So long as the `pack` image isn't modified to run as non-root again, this should work (and the Skaffold `pack` image can be deprecated.)

**Comment by jjbustamante** [comment]
Closing this issue, it should be fine once pack 0.30.1 version is released
