### ISSUE TITLE
`pack sbom download` should be able to retrieve the SBoM from remote images

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/pack#1615]
### Description

When a user tries to download an `SBoM` from an image BUT the image is not present in the docker daemon, pack throws an error similar to `ERROR: image 'image' cannot be found: not found`. The user is forced to download the image to the docker daemon to be able to extract the SBoM information. 

This behavior is a little weird, but I am not sure if it is because some technical limitation or pack could retrieved the SBoM from the registry.

### Proposed solution

1. Investigate why the SBoM is only retrieved from the docker daemon
2. In case the SBoM can be retrieved from the registry then download the file
3. If the image can't be found in a registry or in the daemon, then show the `can not be found` error

### Describe alternatives you've considered

No other alternatives considered

### Additional context
- No documentation required
- This issue is related to #1614

**Comment by bhavyastar** [comment]
Hey @natalieparellano and @jjbustamante, I want to work on this issue. Can you please assign this to me?

**Comment by jjbustamante** [comment]
Hi @bhavyastar!  we are very happy to see you are interest on contributing to CNB project!! I was planning to work on this, but, I will assign this issue to you.

**Comment by bhavyastar** [comment]
Hey @jjbustamante, Thanks for assigning me. When I clone this repo, After cloning, is there any way to install it in my local system how can I see the changes and all? "
Can you please guide me through it?
I am also writing blog on buildpacks so it will be good thing for me.

**Comment by jjbustamante** [comment]
Hi @bhavyastar didi you follow the development [guide](https://github.com/buildpacks/pack/blob/main/DEVELOPMENT.md)?

**Comment by bhavyastar** [comment]
Yup, I follow it and @jjbustamante Can you help me a little I try to read some documentation and also try to understand the code but don't find any way to directly download the SBoM without the docker daemon. It will be good if you can help me and share some resources so that I can research more on my side any maybe find a way to do this.
Till then Is there any more issues for me on which I can work if you can recommend me it will be great!!

**Comment by jjbustamante** [comment]
Hi @bhavyastar , let me try to give you some ideas.

- The entry point for the `pack sbom download` command is [here](https://github.com/buildpacks/pack/blob/main/internal/commands/download_sbom.go). This is the code that parses the user inputs (flags, configuration, etc). Here we call the client code (see above)
- The code responsible for downloading the SBOM is [here](https://github.com/buildpacks/pack/blob/6219ee5a3a912e3a9d1ad75e1c1c65500064f50d/pkg/client/download_sbom.go#L38).  As you can see it is using a [Fetcher](https://github.com/buildpacks/pack/blob/6219ee5a3a912e3a9d1ad75e1c1c65500064f50d/pkg/image/fetcher.go#L77) implementation, this class is taking care of the heavy lifting for downloading an image from a Daemon or a Registry. It's behavior is configured thought the `FetchOptions`.

In this issue, if you see this line:

```golang
img, err := c.imageFetcher.Fetch(context.Background(), name, image.FetchOptions{Daemon: options.Daemon, PullPolicy: image.PullNever})
```
I just realized that `pack sbom download` already has a `--remote` flag for downloading the SBOM from the registry. If you check the help command

```bash
> pack sbom download --help
Download layer containing Structured Bill of Materials (SBoM) from specified image

Usage:
  pack sbom download <image-name> [flags]

Examples:
pack sbom download buildpacksio/pack

Flags:
  -h, --help                Help for 'download'
  -o, --output-dir string   Path to export SBoM contents.
                            It defaults export to the current working directory. (default ".")
      --remote              Download SBoM of image in remote registry (without pulling image)

Global Flags:
      --no-color     Disable color output
  -q, --quiet        Show less output
      --timestamps   Enable timestamps in output
  -v, --verbose      Show more output
``` 

I think you can fix this issue very quickly. On this issue #1614 I added a warning message to the user, but I  think the message is not accurate. Yo can just modify the message to suggest the user to use `--remote` flag if the SBOM is available in the registry instead of suggesting `docker pull` as I put.

**Comment by bhavyastar** [comment]
Ya thanks for this!! For sure, I will make a pull request for that by today itself.
I thought it was something else but yes thanks for your help.
Happy to contribute more here.

**Comment by jjbustamante** [comment]
Don't worry, I also thought this was going to be more complicated, but trying to help you make me noticed the `--remote` flag was already there!

**Comment by bhavyastar** [comment]
Yup, I also noticed this thing in the documentation that the remote thing
is also there but then I thought it was not related to that which we were
discussing. No worries. Thank you!!

**Comment by Phantsure** [comment]
This issue should be closed if [this PR](https://github.com/buildpacks/pack/pull/1648) gets merged?

**Comment by jjbustamante** [comment]
Hi @Phantsure. Yes, but I've being asking @bhavyastar to run `make format` on her branch to be ready

**Comment by bhavyastar** [comment]
Hey @jjbustamante Sorry I was a little inactive. Will do this by today. Actually, I have to clone this again.
Will do this by tomorrow.

**Comment by jjbustamante** [comment]
Hi @bhavyastar, are you able to take a look on this?

**Comment by sarthaksarthak9** [comment]
@jjbustamante is this issue still up?

**Comment by natalieparellano** [comment]
I think https://github.com/buildpacks/pack/pull/1648 could be closed at this point if we get an alternate PR. The implementation would probably look pretty similar to what is in https://github.com/buildpacks/pack/pull/1648/files

**Comment by sarthaksarthak9** [comment]
Yah, i'm planning to raise a duplicate pr for the above
