### ISSUE TITLE
[RFC #0105] pack should support build image extension with Docker

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1623]
RFC: https://github.com/buildpacks/rfcs/blob/main/text/0105-dockerfiles.md

### Description

`pack` enables build image extension by calling the `extender`. However, this is sub-optimal. While enabling users to play with the feature, it is not performant, using `kaniko` under the hood.

### Proposed solution

As `pack` already has access to a daemon, it can apply the dockerfiles directly, saving the extended build base image in the daemon. Thus it will not need to use the `extender`.

### Additional context

In the build image case, having this feature will allow us to drop the requirement that the image being extended is published to a registry (because we are not using kaniko, we don't need a manifest).

### Acceptance criteria

`pack build` with image extensions should complete N ms faster compared to `pack build` with image extensions now.

**Comment by cubxxw** [comment]
I want to implement this function. How should I prepare? Are there any detailed reference steps?

**Comment by natalieparellano** [comment]
@cubxxw thank you for your interest! This issue is actually intended for the Google Summer of Code mentorship project (I've marked it blocked for now). If you're just interested in getting involved with `pack`, I'd suggest checking out one of our "good first issues". Or, if you are interested in applying to GSoC, here is some additional background about this issue that might be helpful:

Dockerfiles in the CNB spec is a relatively new and rather niche feature, but it unlocks a lot of use cases. Some prior knowledge of buildpacks will be useful in the implementation. See the tutorial here: https://buildpacks.io/docs/extension-author-guide/create-extension/ and the RFC here: https://github.com/buildpacks/rfcs/blob/main/text/0105-dockerfiles.md

**Comment by samyakjain10** [comment]
Hey @natalieparellano, I am Samyak Jain, a final year student pursuing B.Tech in Mathematics and Computing from Delhi Technological University. I find this project really interesting for GSOC'23. Could you help me out in getting started?

**Comment by Nandini99-git** [comment]
Hey @natalieparellano , I am Nandini, a second year student pursuing B.E in Information and Technology and I am interested in this project for GSOC 2023. I want to work on this. I am familiar with the technology that is required for this project.

**Comment by y-ykcir** [comment]
Hi @natalieparellano, I am a master from Zhejiang University, familiar with cloud native, kubernetes, docker and Go, I am also interested in this project and hope to participate in the community through this issue.

**Comment by riticksingh** [comment]
Hi @natalieparellano , currently I am doing my research on cloud securtiy (specifically for conatainer security) , let me know if I can use my skill in contributing this issue.

for now I am going through the  https://github.com/buildpacks/rfcs/blob/main/text/0105-dockerfiles.md
Please share if something else requires to be done beforehand

**Comment by david990917** [comment]
Dear team, I am a master student from Shanghai Jiao Tong Unversity and TUM. I have great interests in this project. Do you still accept student to apply GSoC with this project? Should we solve the  `good first issue` and then we can apply? Thank you very much.

**Comment by natalieparellano** [comment]
Closing this issue as our findings from https://github.com/buildpacks/pack/pull/1791 showed that the added complexity from this change may not be worth the performance benefit
