### ISSUE TITLE
Fix hidden broken tests merged by mistake because CI failure

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/pack#1654]
### Description

As I reported on #1653 we merged a PR that added `tee` command to save the result of the test execution in a file. Once we merged this PR the CI stopped notifying when the tests were broken

See the history:

![Screenshot 2023-03-01 at 4 05 55 PM](https://user-images.githubusercontent.com/1181799/222265411-c9929661-e2e2-4b6e-ba9a-9061896bdd91.png)

Because of this, after we merged the commits (on the red square above) the CI broke

![Screenshot 2023-03-01 at 4 19 58 PM](https://user-images.githubusercontent.com/1181799/222267541-ae8d3fa0-588e-4c46-b133-00014100b28a.png)

Locally I verified before all the tests are fine, and after merging this one, we started having the following tests broken

![Screenshot 2023-03-01 at 4 22 53 PM](https://user-images.githubusercontent.com/1181799/222267922-7c8824a6-9e1a-451c-9bb1-dad9d9f3c320.png)

### Proposed solution

We need to fix these broken tests.

### Additional context

See the [PR 1611](https://github.com/buildpacks/pack/pull/1611)

**Comment by jjbustamante** [comment]
@itsdarshankumar by any chance do you want to work on this?

**Comment by itsdarshankumar** [comment]
> @itsdarshankumar by any chance do you want to work on this?

Yes sure @jjbustamante, always anytime:)
