### ISSUE TITLE
pushing cache image to registry

### ISSUE THREAD

**Issue by saturnism** [buildpacks/pack#166]
currently, when using `pack build ...`, it [generates the cache image name](https://github.com/buildpack/pack/blob/master/cache/cache.go#L28) w/ the format of `pack-cache-....`.

I'd like to push this image to a registry for longer term storage.

one thought is to allow `pack build` take a cache image name, which i can provide, and later pushed to a registry.

**Comment by ekcasey** [comment]
@saturnism I agree that if we were going to do this, allowing users to supply the cache image tag with a flag would be the best way to do it. Users would need to be careful though. Right now, the cache name is generated from the image reference, ensuring that rebuilds of an image get the same cache, and that a clean cache is provided for a new image build.

In the mean time, you can always tag and push the cache image to a registry after the build completes.

**Comment by ekcasey** [comment]
hey @saturnism we are actually moving away from an image cache to a docker volume b/c it dramatically improves the performance of `pack build` (https://github.com/buildpack/pack/issues/178). I'm curious about your use case. I think we want `pack` to be performant by default, but we could add flags to allow a users to configure a cache image if that would be useful to folks.

**Comment by izaakschroeder** [comment]
Hey @ekcasey 👋 I'm also kinda curious about the caching options available! Docker volume seems fine to me, I'm just curious how one populates/saves the contents of that volume? I'm not lucky enough to have access to volume-based NAS in my setup right now… kind of stuck with gzipping the contents and sending them to storage over HTTP (and fetching them the same way).

Although I can unzip/zip a directory just fine, are there hooks in the lifecycle that allow me to run those commands before the cache is checked and after the cache is finalized?

Unless I'm misunderstanding the purpose of this particular cache. 😄

**Comment by jromero** [comment]
Moving to `status/ready` as there seems to be consensus that we should enable a `--cache-image` flag.

1. When `--cache-image` flag **IS** is present and `--publish` is **true**, the cache image **SHOULD** be pushed to the registry.
1. When `--cache-image` flag **IS** present and `--publish` is **false**, the cache image **SHOULD NOT** be pushed to the registry.
1. When `--cache-image` flag **IS NOT** present and `--publish` is **true**, the cache image **SHOULD NOT** be pushed to the registry.
1. When `--cache-image` flag **IS NOT** present and `--publish` is **false**, the cache image **SHOULD NOT** be pushed to the registry.

We can later, upon request, discuss adding a seperate flag to control the pushing of the cache-image independently.
