### ISSUE TITLE
Pack cli on ECS not reading custom settings.xml file for maven builds

### ISSUE THREAD

**Issue by bala151187** [buildpacks/pack#1681]
### Summary
Trying to set custom settings.xml file for maven builds

On my local machine setup
========================
Pack version 0.28.0
Pack cli works on my mac for this command 
_pack build pack-gatreg  --volume /Users/bj/eks/paketo/java/maven/binding:/platform/bindings/my-maven-settings_

We have a CI/CD environment
==========================
Jenkins(master)--> agent runs on AWS ECS (Centos 7) --> pack version 0.28.0

I'm running below command inside the ECS
                ```
                mkdir -p java/maven/binding
                echo -n "maven" > java/maven/binding/type
                cp ./settings.xml java/maven/binding/settings.xml
                ls -lrth ${script.env.WORKSPACE}
                ls -lrth ${script.env.WORKSPACE}/java/maven/binding
                pack --version
                cat ${script.env.WORKSPACE}/java/maven/binding/type
                cat ${script.env.WORKSPACE}/java/maven/binding/settings.xml

                pack config default-builder paketobuildpacks/builder:base
                pack build ${name} --volume ${script.env.WORKSPACE}/java/maven/binding:/platform/bindings/my-maven-settings:rw
```

It's unable to read custom settings.xml file 
`17:08:46  Digest: sha256:4a2fbf87a81964ef1a95445f343938ed19406fffda142586a35c9e20904a3315
17:08:46  Status: Downloaded newer image for paketobuildpacks/run:base-cnb
17:08:53  ===> ANALYZING
17:08:53  Previous image with name "gateway-registration" not found
17:08:53  ===> DETECTING
17:08:54  ======== Output: paketo-buildpacks/git@1.0.4 ========
17:08:54  failed to load bindings from '/platform/bindings': failed to read binding 'my-maven-settings': missing 'type'
17:08:54  err:  paketo-buildpacks/git@1.0.4 (1)
17:08:54  ======== Output: paketo-buildpacks/git@1.0.4 ========
17:08:54  failed to load bindings from '/platform/bindings': failed to read binding 'my-maven-settings': missing 'type'

When i did ls command i see all necessary info
17:08:08  -rw-rw-r-- 1 jenkins jenkins    5 Mar 23 21:08 type
17:08:08  -rw-rw-r-- 1 jenkins jenkins 2.6K Mar 23 21:08 settings.xml
17:08:08  0.28.0+git-b10e41f.build-3729
17:08:08  maven

`
Please let me know wat am i doing wrong

**Comment by natalieparellano** [comment]
Hi @bala151187 thanks for the issue - it seems it may relate to this thread in the [Paketo Slack instance](slack.paketo.io): https://paketobuildpacks.slack.com/archives/CU8RVQZ1R/p1674689520460699?thread_ts=1674688737.990889&cid=CU8RVQZ1R. I would suggest checking with the Paketo folks to help you troubleshoot as I don't believe the issue relates to pack.

**Comment by bala151187** [comment]
@natalieparellano Will you be able to invite me to that slack workspace .. my email id balamurugan151187@gmail.com

**Comment by bala151187** [comment]
One of my friend helped me with sign in thanks
