### ISSUE TITLE
pack buildpack downloader should support extension packages

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1684]
### Summary
Once https://github.com/buildpacks/pack/pull/1661 is merged the buildpack downloader should handle extension packages instead of returning nil [here](https://github.com/buildpacks/pack/blob/9e9b7ba1f197656a83c4daf7ee8e6d9e6648a6d9/pkg/buildpack/downloader.go#L201).

We should probably add an acceptance test that uses extension packages in a builder to ensure that things are working end-to-end.

**Comment by itsdarshankumar** [comment]
would like to continue this @natalieparellano once my PR is merged

**Comment by natalieparellano** [comment]
Thank you @itsdarshankumar! I'll assign you the issue
