### ISSUE TITLE
Run images are not pulled when using extensions

### ISSUE THREAD

**Issue by mhdawson** [buildpacks/pack#1686]
### Summary
We've been working on a Node.js extension to support ubi.  We have been able to
build an extension and a builder that uses it and its in https://github.com/nodeshift/ubi-nodejs-extension,
along with instructions on how to try it out.

One issue which I came across which I `think` is a bug in pack is that the run images that
an exention switches to are not automatically pulled by pack. This means that the user needs
to pull them in advance ( step 7 in https://github.com/nodeshift/ubi-nodejs-extension/blob/main/README.md#usage).
I don't think the user should have to know the full set of possible images for the run image and have
to pull them all down in advance. 

##### Steps
Follow the steps in https://github.com/nodeshift/ubi-nodejs-extension/blob/main/README.md#usage and omit step 7.

##### Current behavior
An error is returned indicating the top level app image is empty (which was confusing to me)

##### Expected behavior
The run image is automatically pulled and the application builds successfully.

##### pack info
```shell
user1@fedora testit]$ pack report
Pack:
  Version:  0.28.0+git-b10e41f.build-3729
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.15.2

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10

Config:
  default-builder-image = "[REDACTED]"
```

##### docker info

```
[user1@fedora testit]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 12
  Running: 1
  Paused: 0
  Stopped: 11
 Images: 43
 Server Version: 20.10.21
 Storage Driver: btrfs
  Build Version: Btrfs v6.0
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.0.7-301.fc37.x86_64
 Operating System: Fedora Linux 37 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.663GiB
 Name: fedora
 ID: DEET:EZQI:TY36:OJ3S:CYPH:H4JR:JQAJ:XO7S:GTNM:EZTL:GDXE:DZBX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mhdawson
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  localhost:5000
  172.17.0.1:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by natalieparellano** [comment]
@mhdawson thanks for the issue - I think the solution you are describing makes sense. `pack` should check for the run image in analyzed.toml after the `extend` phase and pull the run image prior to `export`.

**Comment by natalieparellano** [comment]
Should be fixed when https://github.com/buildpacks/pack/pull/1730 lands

**Comment by mhdawson** [comment]
@natalieparellano thanks for the update.

**Comment by mhdawson** [comment]
@natalieparellano validate that it now works and submitted PR to update instructions for extension to remove step that said to pull the images - https://github.com/paketo-community/ubi-nodejs-extension/pull/2
