### ISSUE TITLE
Turborepo and BuildPacks Pack Support

### ISSUE THREAD

**Issue by arkmech** [buildpacks/pack#1695]
### Description
Getting TurboRepo to work with `pack build` command.

### Proposed solution
`pack build` new option to support Turborepo. Currently can only use `--path` to specify single directly app files.

### Additional context
- I'm getting missing dependencies because missing shared dependencies from root `node_modules`. I am pointing to `apps/web` web is a Next.js app.
- Also its looking for `package-lock.json`, but thats in root as well.
- I am using pnpm, so would actually need `pnpm-lock.json`

### Describe alternatives you've considered
I am thinking I can create a customer builder to solve the pnpm issue, but haven't looked deep yet. But not sure how to resolve files in different paths.

```bash
	pack build web \
		--path apps/web \
		--builder paketobuildpacks/builder:base
```

**Comment by jjbustamante** [comment]
Hi @arkmech 

> ```shell
> pack build new option to support Turborepo. Currently can only use --path to specify single directly app files.
> ```

Currently `--path` flag can only be used to specify a single application directory.  Could you elaborate a little bit more on your particular use case?

For what I can understand you have a complex directory structure for your source code, you may want to check how to configure your buildpack with your provider, for example, paketo team has something like [this](https://paketo.io/docs/howto/nodejs/#build-an-app-from-source-in-a-subdirectory) for nodejs buildpack

**Comment by jjbustamante** [comment]
@arkmech 

Closing this issue as we think the CNB ecosystem has ways to workaround this, if you think we need to change the way we are doing some stuff, I just you to open an [RFC](https://github.com/buildpacks/rfcs) with a new proposal and we are more than happy to discuss it during our Working group meetings or through our slack channel
