### ISSUE TITLE
Extract internal/cache package to public

### ISSUE THREAD

**Issue by inspirit941** [buildpacks/pack#1709]
### Description
from v0.28, pack cli support --cache options to define cache technique for build process.
- https://github.com/buildpacks/pack/pull/1477/files

but it seems that cacheOpts struct used for --cache options is in internal package, which is not possible to import from external project.

<img width="595" alt="스크린샷 2023-04-05 오후 1 15 04" src="https://user-images.githubusercontent.com/26548454/230240788-9380dc7f-3a5e-4f90-93b9-1e1f1ed58309.png">

### Proposed solution

the code within [internal/cache](https://github.com/buildpacks/pack/tree/10f5f0a357ccc0b8cc4cabf7ee9a70814386f0cd/internal/cache) is part of a public package that others can consume.

Thanks!

**Comment by natalieparellano** [comment]
@buildpacks/platform-maintainers any thoughts on this one?

**Comment by jkutner** [comment]
I'm supportive
