### ISSUE TITLE
Add command `pack manifest inspect` to display a manifest list

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/pack#1722]
### Context

We've been working on the idea to enable multi-arch support on CNB. A mentorship [project](https://mentorship.lfx.linuxfoundation.org/project/ee387e1b-de4e-4c1e-9bef-0239a2e9ca40) was created on LFX and this feature is part of the efforts to build the Minimal Viable Product (MVP) during the program duration.

More information can be found:
- [Notes](https://docs.google.com/document/d/1nrMmz8ZFOdEwzlzQYS963BfSqCvfoyhbk5FvExueuM4/edit?usp=sharing)
- Meeting [recording](https://www.youtube.com/watch?v=B-rg5SQQ7tA)

### Additional context
- [ ] This feature should be documented somewhere

**Comment by nitishfy** [comment]
Hi, I'd like to take this up!

**Comment by jjbustamante** [comment]
Hi @nitishfy! Sorry, we already have a PR open for this one
