### ISSUE TITLE
Support docker desktop on Linux

### ISSUE THREAD

**Issue by cjsewell** [buildpacks/pack#1759]
### Description
By default it appears `build pack` only checks `/var/run/docker.sock`
Docker desktop for Linux creates the socket in `$HOME/.docker/desktop/docker.sock`

When running pack build on Linux with Docker desktop installed I get the error: 
`ERROR: failed to build: failed to fetch builder image 'gcr.io/buildpacks/builder:latest': Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

### Proposed solution
It should check if `$HOME/.docker/desktop/docker.sock` exists and use that if it does

### Describe alternatives you've considered
Creating a symlink works for me as a work around, but this may not work for everyone  
`sudo ln -s $HOME/.docker/desktop/docker.sock /var/run/docker.sock`

**Comment by jjbustamante** [comment]
Hi @cjsewell, thanks for creating this issue!

Just for curiosity, is your env `DOCKER_HOST` set?

I think, if you set

```
export DOCKER_HOST=unix://$HOME/.docker/desktop/docker.sock

```
it should also work without the symlink

**Comment by jjbustamante** [comment]
Hi @cjsewell 

We just released a [RC](https://github.com/buildpacks/pack/releases/tag/v0.31.0-rc1) pack version, it will be great if you can give it a try and confirm the issue was solved

**Comment by pellizzetti** [comment]
It works for me, @jjbustamante

Thanks a lot! <3
