### ISSUE TITLE
`pack inspect <app-image>` should show if the image is rebasable or not

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#1799]
### Description
When image extensions are used to extend the run image, the `io.buildpacks.rebasable` label on the exported app image may be `false`. An app image is rebasable IFF the label is `true` or unset.

### Proposed solution
`pack inspect <app-image>` should show if the image is rebasable or not

### Describe alternatives you've considered
Do nothing, users can inspect the label themselves (this is a poorer UX)

### Additional context
- [x] This feature should be documented somewhere

**Comment by dlion** [comment]
I'd like to start working on it :) @natalieparellano
