### ISSUE TITLE
How to add resources to the pack?

### ISSUE THREAD

**Issue by trenta3** [buildpacks/pack#183]
Is it currently possible to add resources (mongodb, postgresql, etc.) to the packs?
I couldn't find any documentation on this nor any mention of it to be possible.

**Comment by Zanadar** [comment]
@trenta3 Can you say a bit more about the usecase here? Are you trying to bind services to your app you're building? Or is that you want to produce images for eg. `postgresql`?

**Comment by trenta3** [comment]
@Zanadar Yes, I'm trying to bind a database service to my app, so that my users can run the app without having to take care of setting up a local database.

**Comment by natalieparellano** [comment]
@trenta3 see related [RFC](https://github.com/buildpacks/rfcs/blob/2c6ac8da87d3f6daddbbb859f258925047f15179/text/0012-service-binding.md) and [spec document](https://github.com/buildpacks/spec/blob/50fd6470694ea118eae2f48b997415ef68102418/extensions/bindings.md) - these have been finalized but to my knowledge, pack does not currently support them.

@nebhale could you comment further?

**Comment by nebhale** [comment]
Yep, we've got an RFC and spec, but `pack` doesn't yet support it. It's looking like, given the other things stacking up, that it won't make it until `0.10` or later though.

**Comment by natalieparellano** [comment]
See https://github.com/buildpacks/pack/issues/504 for the work to implement this in pack.

I'm going to go ahead and close this issue, but feel free to circle back if there are further outstanding questions.
