### ISSUE TITLE
Timestamp decision causes issue with zlib

### ISSUE THREAD

**Issue by Skraelingjar** [buildpacks/pack#184]
In my app I'm getting an error from zlib 'ZIP does not support timestamps before 1980' which seems odd because all the dates are 1980. I saw #130 and understand why that decision was made. 

Would it be possible to add an option to modify the timestamps when building?

**Comment by jchesterpivotal** [comment]
One approach would be to add support for `SOURCE_DATE_EPOCH`: https://reproducible-builds.org/docs/source-date-epoch/

**Comment by ekcasey** [comment]
@Skraelingjar which version of `pack` are you using?

**Comment by Skraelingjar** [comment]
I'm using v0.1.0

**Comment by ameyer-pivotal** [comment]
@Skraelingjar We now change timestamps to a compatible date, so hopefully you're not seeing this anymore. Furthermore, we're going to address #492, which should also help resolve your issue if you still notice problems. Closing this for now, but feel free to comment or reopen if you have any more concerns. Thanks!
