### ISSUE TITLE
Fix `client.WithKeychain` to use it during the lifecycle

### ISSUE THREAD

**Issue by ernesto-jimenez** [buildpacks/pack#1845]
### Summary

When creating a client using `WithKeychain`, the keychain should be used in the lifecycle.

Right now, the lifecycle executor relies on the global `authn.DefaultKeychain`, rather than the one we set in the client.

---

##### Steps

Create a new `authn.Keychain` and inject it into the client.

##### Current behavior

The keychain is used at first, but the lifecycle still relies on `authn.DefaultKeychain`

##### Expected behavior

The client should inject it's keychain into a new field inside `LifecycleOptions`, and the executor should use the injected keychain rather than the global default.

**Comment by natalieparellano** [comment]
@ernesto-jimenez I opened https://github.com/buildpacks/pack/pull/1872 to fix this - any chance you could test the branch out to verify?

**Comment by jjbustamante** [comment]
Hi @ernesto-jimenez 

We just released a [RC](https://github.com/buildpacks/pack/releases/tag/v0.31.0-rc1) pack version, it will be great if you can give it a try and confirm the issue was solved
