### ISSUE TITLE
Ability to add image labels to buildpacks during `pack buildpack package`

### ISSUE THREAD

**Issue by ForestEckhardt** [buildpacks/pack#1867]
### Description
We would like to be able to add metadata to our buildpacks via image labels at build time but there is no way for us to add custom image labels.

### Proposed solution
Add a flag `--label <label>=<value>` to `pack buildpack package` command that will allow buildpack authors to add custom metadata to the buildpack image at build time.

### Describe alternatives you've considered
This can be achieved with `crane mutate` but that requires you to upload the image without metadata to a registry and then mutate the file. This also means that image labels cannot be added to the `.cnb` files at all which feels bad as the OCI image in registry and in `.cnb` file format should be identical.

**Comment by hone** [comment]
@ForestEckhardt is this something you'd like to do at build time dynamically, or should is it ok to encode this statically like in `buildpack.toml`?

**Comment by hone** [comment]
@ForestEckhardt I think those labels make sense. If I understand, you can use a buildpack today to solve what you're trying to do. I still think giving buildpack authors the flexibility makes sense and if we want to standardize things in lifecycle, we can do that after the fact.

**Comment by ForestEckhardt** [comment]
> If I understand, you can use a buildpack today to solve what you're trying to do.

@hone 

To be clear. This would be for adding labels to a buildpackage and an image built by a buildpack. If there is already a way to do this as part of the buildpack packaging process then I would be more than happy to use that but as far as I could find there is no mechanism to add the labels to the buildpackage itself.

**Comment by jjbustamante** [comment]
This could also be useful for `pack builder create` command. See this [thread](https://cloud-native.slack.com/archives/C0331B61A1Y/p1692112371262099)

cc @matejvasek

**Comment by jjbustamante** [comment]
Here are my thoughts on this.

We have 3 commands that outputs OCI artifacts 
- `pack buildpack package`
- `pack builder create`
- `pack build <app-image>`

The idea will be to include a new flag `--label <label>=<value>` to allow users to add custom labels on those artifacts.
Under the hoods pack creates an [imgutil.Image](https://github.com/buildpacks/imgutil/blob/main/image.go) instance, this interface already exposes a [method](https://github.com/buildpacks/imgutil/blob/main/image.go#L53) to add labels, in my opinion, adding those labels to `buildpackage` and `builders` is easy (we don't deal with the lifecycle here). 

For `pack build <app-image>` I think could be similar, but in such as case, lifecycle is responsible for creating the imgutil.Image so we will need to passthrough  the values to it. Maybe we should create a ticket in the lifecycle side first, and once that is defined we can create a ticket on pack to expose the proper user interface

**Comment by ForestEckhardt** [comment]
@jjbustamante 

I am not particular concerned with getting image labels built into the `pack build <app-image>` as that is something that I see supported by buildpacks. I would personally prefer that concern could be separated from this issue as I would like to see the `pack buildpack package` feature path not have to be tied to this being a universal option.

**Comment by jjbustamante** [comment]
This one seems like a very straight forward feature, and it seems valid to me, I will just put under *needs-discussion* to double check during working group if it doesn't require an RFC, I don't think so, but just want to validate it with the community. After that, we can label this one as *status-ready* to be work on

**Comment by jjbustamante** [comment]
For working group discussion:
- I want to confirm the idea is adding labels to the [config file](https://github.com/opencontainers/image-spec/blob/main/config.md) in the OCI image
- I do not think this requires an RFC
- What about labels with key `org.opencontainers.*` should we do any validation? (I don't think so)
