### ISSUE TITLE
Gitea support. Not just: gitlab, github

### ISSUE THREAD

**Issue by mmm8955405** [buildpacks/pack#1907]
Gitea support. Not just: gitlab, github

**Comment by jjbustamante** [comment]
Hi @mmm8955405, 

Thank you for your request. 

I just added [Gitea](https://about.gitea.com/) to the issue #515 as a potential platform to integrate with. It is actually interesting but we will need some help form the community to push forward the initiative. 

Closing this issue in favor of 515, We can open a new with the description and scope once someone jumps in on this.

Duplicates #515
