### ISSUE TITLE
Add pack cli support for IBM s390x

### ISSUE THREAD

**Issue by dilipgb** [buildpacks/pack#1943]
### Description
Build pack CLI for s390x architecture. 

### Proposed solution
pack command line interface is currently supported for amd and arm architectures. We need to enable the pack on s390x architecture as well. We have buildpacks/lifecycle enabled for s390x and looking for pack cli support.

### Describe alternatives you've considered
I have compiled pack cli locally and used it on s390x. I'm looking to enable it and available generally on s390x.

**Comment by dilipgb** [comment]
@natalieparellano @jabrown85 can you please help me how to enable support on s390x?

**Comment by jabrown85** [comment]
@dilipgb I'm not a maintainer on `pack` (I don't think Natalie is officially one either - but could be mistaken). You may want @jkutner @hone or @jjbustamante as your `pack` CI guide. I am assuming most of the work is similar to `lifecycle` and that the biggest uplift is GitHub actions work to compile `pack` on s390x.

**Comment by dilipgb** [comment]
thanks @jabrown85.

@jkutner @hone @jjbustamante can you please guide me how can I approach enabling pack cli on s390x?

**Comment by jjbustamante** [comment]
Hi @dilipgb 

Thank you very much for working so hard on adding support for s390x!, I will start suggesting:

- Adding a new *build additional architecture* [here](https://github.com/buildpacks/pack/blob/main/.github/workflows/build.yml#L169-L175)
- Adding a new *package artifact* for linux/s390x like the one [here](https://github.com/buildpacks/pack/blob/main/.github/workflows/build.yml#L227-L232)

I haven't check the whole process for releasing pack, that is something I need to familiarize with! but I will try to work along side with you to push this issue forward!

**Comment by jjbustamante** [comment]
Also, @dilipgb I am not familiar with s390x architecture, but is there any package manager where we want the binary to be deploy for later installation? because in such as case, we will need to do more stuffs. but if we just want the binary to be compiled and ready for download, I think the steps I mentioned above are enough.

The other thing, is to run the test suite in a s390x environment. that will also require something else to be done.

**Comment by dilipgb** [comment]
@jjbustamante s390x uses standard linux operating system (RHEL/Ubuntu based). So it use yum/apt package manager depending on Linux flavours.

 If other arch build publish to these package manager repos then we should be good and it's not hard requirement though. We can ask users to download compiled binaries as well from github release page.

 I will run test cases in our cloud environment and see if I face any challenges. What test suites you will running for additional archs?
