### ISSUE TITLE
lifecycle image not available when --trust-builder flag is not passed with pack build command

### ISSUE THREAD

**Issue by sgavathe** [buildpacks/pack#1947]
### Summary
Hello, what is the relation between --trust-builder  and lifecycle image not available when that flag is not passed with pack build command?
With the below command there is an error
`pack build --pull-policy never sample-python-builder --path app-tests/sample-python-app --builder local/buildpack-builder:latest --verbose && docker run -it --rm sample-python-builder`

> ERROR: failed to build: fetching lifecycle image: image buildpacksio/lifecycle:0.17.2 does not exist on the daemon: not found

---

##### Steps
1. `pack build --pull-policy never sample-python-builder --path app-tests/sample-python-app --builder local/buildpack-builder:latest --verbose && docker run -it --rm sample-python-builder`

##### Current behavior
It produce an error and it never finished building an image and it returns with the error
> ERROR: failed to build: fetching lifecycle image: image buildpacksio/lifecycle:0.17.2 does not exist on the daemon: not found

##### Expected behavior
per @natalieparellano which makes sense.
`This looks like a bug in pack, we should just download the lifecycle image if it’s not in the daemon`

---

### Environment
`
docker --version
Docker version 20.10.17, build 100c701
  `

##### pack info
`
$ pack --version
0.27.0
`

**Comment by jjbustamante** [comment]
Closing this issue based on the following [comments](https://cloud-native.slack.com/archives/C033DV8D9FB/p1698342548509309?thread_ts=1698341631.106539&cid=C033DV8D9FB)
