### ISSUE TITLE
pack build ：[analyzer] ERROR: failed to parse arguments: received 9 arguments, but expected 1

### ISSUE THREAD

**Issue by comevback** [buildpacks/pack#1965]
After upgrading my macOS to Sonoma, running the pack build command with Cloud Native Buildpacks started resulting in an error. The command I used is:

pack build test --path . --builder paketobuildpacks/builder:base
The output ends with:

===> ANALYZING [analyzer] ERROR: failed to parse arguments: received 9 arguments, but expected 1 ERROR: failed to build: executing lifecycle: failed with status code: 3
I'm unsure which arguments the analyzer is referring to, as I only provided the name, path, and builder in my command. How can I determine which arguments are being passed incorrectly to the pack build command?

I tested the same file and same version of pack on other PC (windows and linux)
they all work well
I guess there maybe some problem of new MacOS.
but I cannot fix it.

**Comment by jjbustamante** [comment]
Hi @comevback 

Could you also add to the ticket the output of `pack report` command, and run you `pack build` with `--verbose` flag and share with us the output similar to this one:

```bash
Running the creator on OS linux with:
Container Settings:
  Args: /cnb/lifecycle/creator -daemon -launch-cache /launch-cache -log-level debug -app /workspace -cache-dir /cache 
  System Envs: CNB_PLATFORM_API=***
  Image: ****
  User: root
  Labels: map[author:pack]
Host Settings:
  Binds: ***
  Network Mode:
Starting creator...
Parsing inputs...
Ensuring privileges...
Executing command...
===> ANALYZING
```

**Comment by jjbustamante** [comment]
Also `docker info` will be great to include in the ticket description

**Comment by comevback** [comment]
> Hi @comevback
> 
> Could you also add to the ticket the output of `pack report` command, and run you `pack build` with `--verbose` flag and share with us the output similar to this one:
> 
> ```shell
> Running the creator on OS linux with:
> Container Settings:
>   Args: /cnb/lifecycle/creator -daemon -launch-cache /launch-cache -log-level debug -app /workspace -cache-dir /cache 
>   System Envs: CNB_PLATFORM_API=***
>   Image: ****
>   User: root
>   Labels: map[author:pack]
> Host Settings:
>   Binds: ***
>   Network Mode:
> Starting creator...
> Parsing inputs...
> Ensuring privileges...
> Executing command...
> ===> ANALYZING
> ```



Hi @jjbustamante, Thank you for seeing, today I update MacOS to 14.1.1 (23B81), and this bug disappeared, So I think the problem comes from the OS
but I can still provide the previous log file of the error:

```shell
Using build cache volume pack-cache-library_test_latest-e9d5f5abcb34.build
===> ANALYZING
Running the analyzer on OS linux with:
Container Settings:
  Args: /cnb/lifecycle/analyzer -log-level debug -daemon -stack /layers/stack.toml -run-image index.docker.io/paketobuildpacks/run:base-cnb -launch-cache /launch-cache test
  System Envs: CNB_USER_ID=1000 CNB_GROUP_ID=1000 CNB_PLATFORM_API=0.11
  Image: buildpacksio/lifecycle:0.16.5
  User: root
  Labels: map[author:pack]
Host Settings:
  Binds: /var/run/docker.sock:/var/run/docker.sock pack-cache-library_test_latest-e9d5f5abcb34.launch:/launch-cache pack-layers-gddaceodoq:/layers pack-app-rmviedsuoc:/workspace
  Network Mode: 
[analyzer] ERROR: failed to parse arguments: received 11 arguments, but expected 1
ERROR: failed to build: executing lifecycle: failed with status code: 3
```
