### ISSUE TITLE
platform mismatch during pack build / pack builder create

### ISSUE THREAD

**Issue by robdimsdale** [buildpacks/pack#1968]
### Summary
When running `pack build` 0.32.0 wih the paketo builder/buildpack images, we see the following error:

```
fetching image: image with reference gcr.io/paketo-buildpacks/dotnet-core:0.41.0 was found but does not match the specified platform: wanted linux/amd64, actual: linux
```

This is true for all our images - it's nothing specific to the dotnet-core buildpack.

---

### Reproduction

`pack build` or `pack builder create` with the paketo builders.

e.g. pick a [Paketo Samples](https://github.com/paketo-buildpacks/samples) app and try to `pack build` it.

**Comment by c0d1ngm0nk3y** [comment]
This is kind of a big deal, isn't it? Should we add some integration test to make sure that `pack build` works with paketo?

**Comment by natalieparellano** [comment]
> Should we add some integration test to make sure that pack build works with paketo?

We should definitely add an acceptance test. Our current suite didn't catch this because all the tests that do `pack build --buildpack <image>` use daemon images. A test that uses a registry image would have caught this.
