### ISSUE TITLE
`Exec format error`: Pack on WSL

### ISSUE THREAD

**Issue by ericis** [buildpacks/pack#199]
[Installing `./pack`](https://buildpacks.io/docs/install-pack/) on Windows 10 Pro Subsystem for Linux (WSL), 
`-bash: ./pack: cannot execute binary file: Exec format error`

**Comment by natalieparellano** [comment]
Hi @ericis - apologies for the long delay without a response. We did just try installing WSL with Ubuntu, and were able to see `pack` install successfully by following the instructions for Linux here: https://buildpacks.io/docs/install-pack/#linux.

Could you provide some further details about what you are trying to accomplish?

![Screen Shot 2020-02-06 at 4 28 04 PM](https://user-images.githubusercontent.com/6894483/73980288-ec80a100-48fd-11ea-9caa-a771514eb60b.png)

**Comment by natalieparellano** [comment]
I'm going to go ahead and close this issue, but feel free to circle back if there are further outstanding questions.
