### ISSUE TITLE
Pack tries to use HTTP proxies running on localhost

### ISSUE THREAD

**Issue by benmoss** [buildpacks/pack#1998]
### Summary
I run https://github.com/williambailey/pacproxy locally to automatically proxy requests to the right proxy server (confusing, I know).

When I run `pack build` it tries to use `127.0.0.1` as a proxy from **inside the container**, since that's what I have set as the `http_proxy` environment variable.

This doesn't work since the container is running on a virtual network.

---

##### Steps

1. Run a proxy on localhost
2. Use `pack build`

##### Current behavior
```
[builder] failed to fetch dependency: failed to make request: Get "https://artifactory.corp.com/artifactory/golang-release/go1.21.3.linux-amd64.tar.gz": proxyconnect tcp: dial tcp 127.0.0.1:8888: connect: connection refused
```

##### Expected behavior
It should just work!

---

**Comment by benmoss** [comment]
https://github.com/benmoss/pack/compare/main...no-localhost-proxying fixes the problem for me, but not sure it's how it should really be fixed

**Comment by benmoss** [comment]
@jjbustamante then I can't access other machines on my VPN. I rely on the `PROXY` env variables to tell tools to connect over a proxy, but for Docker those settings are configured at the VM level.

![Screenshot 2024-02-05 at 2 24 38 PM](https://github.com/buildpacks/pack/assets/239754/ac403b32-59f0-47a9-af11-52f93883661e)

**Comment by benmoss** [comment]
Maybe there isn't a universal solution to this, what works for me may break someone else's workflow.

**Comment by AidanDelaney** [comment]
This is the correct behaviour.  If you set `https_proxy` and run `pack` then we expect `pack` to use that proxy to access resources.  You can try setting `no_proxy` to avoid `pack` using the `https_proxy` for specific domains.
