### ISSUE TITLE
More Clear Info on Buildpacks

### ISSUE THREAD

**Issue by jamesward** [buildpacks/pack#200]
It should be clear where the buildpacks in a builder image come from so that people know where to file bugs / find the source.

**Comment by ahmetb** [comment]
Specifically https://hub.docker.com/r/heroku/pack & https://hub.docker.com/r/heroku/buildpacks.

**Comment by sclevine** [comment]
CC: @hone @jkutner for Heroku images.

(For CF, see: https://hub.docker.com/r/cloudfoundry/cnb)

**Comment by ekcasey** [comment]
One possible path forward would be to allow builder authors to optionally supply links to the buildpack source as part of the builder configuration. That way `pack inspect-builder` could display that information.

**Comment by hone** [comment]
I'm 👍 on having buildpacks being able to specify this along with description and other metadata that is important. The registry will take advantage of this data too.

**Comment by Zanadar** [comment]
Do we think this might need an RFC or would it be a platform specific thing?

**Comment by jromero** [comment]
Given buildpack authors from various avenues would provide this information I believe this should be spec'd. 

My initial thought is that this could live in a `buildpack.toml` similar to how `project.toml` has [source and documentation urls](https://github.com/buildpacks/rfcs/blob/master/text/0019-project-descriptor.md#what-it-is).

**Comment by jromero** [comment]
Closing this as an RFC has been filed. Once that is accepted we can implement that as a feature which would satisfy this issue.

RFC: https://github.com/buildpacks/rfcs/pull/55
