### ISSUE TITLE
Flake: `An existing connection was forcibly closed by the remote host` still occurs in CI

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#2021]
### Summary

A few weeks ago we started seeing this flake: `An existing connection was forcibly closed by the remote host` ([example](https://github.com/buildpacks/pack/actions/runs/7397184415)). It occurs only on the LCOW worker. We added a retry to make it go away, but it still pops up enough to be a pain.

---

### Environment

Our self-hosted LCOW worker. Maybe the worker is running into resource limits and perhaps we can make this error go away by beefing up our worker. But, perhaps there is some underlying problem that we need to fix.

**Comment by natalieparellano** [comment]
@itsdarshankumar expressed an interest in this one :)

**Comment by natalieparellano** [comment]
A small update here: this seems to no longer be occurring. We didn't change anything. So 🤷🏼 and also 🎉

**Comment by jjbustamante** [comment]
I am closing this issue, we don't know actually why it stopped happening.
