### ISSUE TITLE
Support Platform API 0.13

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#2066]
### Description

See spec milestone: https://github.com/buildpacks/spec/milestone/27

* [Platform API changes for image extension build contexts](https://github.com/buildpacks/spec/pull/384)
  * This [function](https://github.com/buildpacks/pack/blob/ded78f30bd5a0f0658f68f65b9532d2594ab3797/internal/build/lifecycle_execution.go#L889-L899) can no longer rely on the presence of a "build" directory to indicate build extensions - instead, we must traverse the directory and look for a `<dir>/<buildpack-id>/build.Dockerfile` 
* [Making builpack image extensions feature non-experimental](https://github.com/buildpacks/spec/issues/378)
  * Let's remove the [guard](https://github.com/buildpacks/pack/blob/ded78f30bd5a0f0658f68f65b9532d2594ab3797/pkg/client/build.go#L473-L475) in `pack build`
  * We don't have to set the env var [here](https://github.com/buildpacks/pack/blob/ded78f30bd5a0f0658f68f65b9532d2594ab3797/internal/build/lifecycle_execution.go#L427), [here](https://github.com/buildpacks/pack/blob/ded78f30bd5a0f0658f68f65b9532d2594ab3797/internal/build/lifecycle_execution.go#L721), [here](https://github.com/buildpacks/pack/blob/ded78f30bd5a0f0658f68f65b9532d2594ab3797/internal/build/lifecycle_execution.go#L742), and [here](https://github.com/buildpacks/pack/blob/ded78f30bd5a0f0658f68f65b9532d2594ab3797/internal/build/lifecycle_execution.go#L778) anymore
* [[RFC #0111] Support insecure registries](https://github.com/buildpacks/spec/issues/364) - see other [issue](https://github.com/buildpacks/pack/issues/1916)
* [[RFC 0125] Lifecycle parallel export](https://github.com/buildpacks/spec/issues/379) - maybe it doesn't make sense to expose this in pack just set; we might wait until this feature is requested

### Proposed solution

See above

**Comment by sarthaksarthak9** [comment]
I would love to work on this issue @natalieparellano

**Comment by sarthaksarthak9** [comment]
@natalieparellano do we have to implement all changes in a single pr ?

**Comment by natalieparellano** [comment]
@sarthaksarthak9 it could be done in separate PRs. Happy to provide further guidance if you're still interested in working on this.
