### ISSUE TITLE
Pack 0.33.2 GitHub release changelog doesn't match diff between Git tags

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#2070]
Pack 0.33.2 was just released:
https://github.com/buildpacks/pack/releases/tag/v0.33.2

In the GitHub release description the changes are listed as only:

> Changelog
>
> * Fixing CVEs (https://github.com/buildpacks/pack/issues/2009 by @jjbustamante )

However, if I use the compare release dropdown from that release entry page, and compare the `v0.33.2` tag to the previous release's tag (`v0.33.1`):
https://github.com/buildpacks/pack/compare/v0.33.1...v0.33.2

...then the list of commits includes many more changes.

It seems that either:
1. The changelog is correct, in that this was a successful branch release that only included CVE fixes, but the wrong Git commit was tagged with the `v0.33.2` tag - and the Git tag just needs to be moved to the correct commit.
2. Or, it was meant to be a branch deploy, but actually all of the changes on `main` got released in the generated binaries, and it's the GitHub release description that isn't accurate (rather than the Git tag)?

**Comment by jjbustamante** [comment]
Hi @edmorley 

Yes, I noticed that yesterday. the tag was created against the main branch.

- binaries are fine
- tag is wrong

**Comment by edmorley** [comment]
@jjbustamante Could you manually move the tag to fix it?

**Comment by jjbustamante** [comment]
Done. 

See [this](https://github.com/buildpacks/pack/compare/v0.33.1...v0.33.2)
