### ISSUE TITLE
Documenting known issue: pack 0.33.0 has breaking change for library users

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#2071]
### Description

This was reported in Slack: https://cloud-native.slack.com/archives/C033DV8D9FB/p1708014910021369

Previously, `build.LifecycleOptions.UID` didn't exist as a field / options for the "lifecycle executor".

When we merged https://github.com/buildpacks/pack/pull/2017 we didn't realize that in order for the "lifecycle executor" to work properly the `l.opts.UID` must be set intentionally, to either:
* The CNB_USER_ID or some other positive value
* A negative value to avoid providing `-uid` to the lifecycle
* 0 if you really want to run the lifecycle as root (this will not work)

If `l.opts.UID` is unset (0) then a number of issues can occur:
* (trusted flow) The creator will error out at the detect phase, refusing to run as root
* (untrusted flow) The analyzer will chown the /layers directory to be root-owned, and the detector will fail to write group.toml there
* ...

### Proposed solution

When upgrading to 0.33.0, pack library consumers MUST set `build.LifecycleOptions.UID` to either a positive or negative value. It cannot be 0.

### Describe alternatives you've considered

We could roll back https://github.com/buildpacks/pack/pull/2017. But, a similar requirement has already existed for some time for `build.LifecycleOptions.GID`.

**Comment by edmorley** [comment]
xref https://github.com/superfly/flyctl/pull/3396

**Comment by natalieparellano** [comment]
Closing as there is nothing to be done here, but the issue remains for info purposes.
