### ISSUE TITLE
When creating a buildpack with `docker buildx --platform linux/arm64` pack does not set the architecture

### ISSUE THREAD

**Issue by jericop** [buildpacks/pack#2079]
### Summary
The following occurs when running pack from a dockerfile using `docker buildx build`. When creating a buildpack with `pack buildpack package` the architecture is always an empty string, regardless of the architecture you run on.

This issue is similar to https://github.com/buildpacks/pack/issues/1958, except that it affects `pack buildpack package` instead of `pack builder create`.

### Reproduction

Note that docker needs to be configured to build multi-arch images for this to work as described [here](https://docs.docker.com/build/building/multi-platform/).

##### Steps

1. Create the following dockerfile in a directory.
```
FROM buildpacksio/pack as pack

FROM bitnami/git
USER root
WORKDIR /workspace

COPY --from=pack /usr/local/bin/pack /usr/local/bin/pack

RUN <<RUN_EOF

image_arch=amd64
if [ $(arch) = "aarch64" ]; then
  image_arch=arm64
fi

git clone --depth 1 --branch main https://github.com/buildpacks/samples.git

pack buildpack package ttl.sh/jericop-hello-world-buildpack:${image_arch} --publish \
  --path samples/buildpacks/hello-world

RUN_EOF

```
2. Run the following `docker buildx` command to create and publish buildpacks to ttl.sh, an ephemeral registry.
```
docker buildx build --platform linux/amd64,linux/arm64 .
```
3. Inspect the image config with crane to confirm the architecture is an empty string.
```
➜  pack-arch-issue crane ls ttl.sh/jericop-hello-world-buildpack
amd64
arm64
➜  pack-arch-issue crane config ttl.sh/jericop-hello-world-buildpack:amd64 | jq .architecture
""
➜  pack-arch-issue crane config ttl.sh/jericop-hello-world-buildpack:arm64 | jq .architecture
""
➜  pack-arch-issue 
```

##### Current behavior

The architecture is empty, which prevents building multi-arch images without modifying the image or doing some `docker manifest` magic.

##### Expected behavior

The architecture should match the architecture that pack is running on.

---

##### pack info

```
Pack:
  Version:  0.33.2+git-f2cffc4.build-5562
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.18.5

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12
```

##### docker info

```
Client:
 Version:    25.0.3
Server:
 Server Version: 25.0.3

```

**Comment by jericop** [comment]
I believe this fix also addresses https://github.com/buildpacks/pack/issues/1968, which was fixed by adding retry logic.

**Comment by WYGIN** [comment]
I will take this issue, as I already did some changes in imgutil related to it :)

**Comment by jericop** [comment]
@WYGIN I have a pull request with changes and unit tests already [here](https://github.com/buildpacks/pack/pull/2080). Maybe we can figure out how to merge the changes together.

**Comment by jjbustamante** [comment]
@jericop 

We are working to include #2086 into pack 0.34.0 that PR should fix this issue! I think we can close @2080 in favor on that one.

**Comment by jjbustamante** [comment]
With the implementation of RFC 0128 you don't need to use `docker buildx` to create a multi-platform buildpack package. 

From your Dockerfile configuration, you just need to do is:

```bash
pack buildpack package ttl.sh/jericop-hello-world-buildpack:${image_arch} --publish \
  --path samples/buildpacks/hello-world \
  --target linux/amd64 \
  --target linux/arm64 
``` 

and `pack` will create the manifests with the correct `os` and `architecture`.

Using the binary from the open PR I did this:

```bash
> $PACK_BINARY buildpack package ttl.sh/jjbustamante-hello-world-buildpack:${image_arch} --publish --path samples/buildpacks/hello-world --targe
t linux/amd64 --target linux/arm64
Successfully pushed manifest list ttl.sh/jjbustamante-hello-world-buildpack: to registry
Successfully published package ttl.sh/jjbustamante-hello-world-buildpack: and saved to registry

# Inspect the Index
> crane manifest  ttl.sh/jjbustamante-hello-world-buildpack | jq .
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 402,
      "digest": "sha256:46ee213ae13e9e33a486f95780bdd09cda71955bcb55d4ceffe423265c752e3f",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 402,
      "digest": "sha256:11d69032ed77c74be777d081321af19617fb1acd660f02b01f7ec46b85481130",
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

# Inspecting each digest

> crane config ttl.sh/jjbustamante-hello-world-buildpack@sha256:11d69032ed77c74be777d081321af19617fb1acd660f02b01f7ec46b85481130 | jq .architecture
"arm64"

> crane config ttl.sh/jjbustamante-hello-world-buildpack@sha256:46ee213ae13e9e33a486f95780bdd09cda71955bcb55d4ceffe423265c752e3f | jq .architecture
"amd64

```

I think this is the expected output, right? `docker buildx` was used to deal with the Image Index creation 😄
