### ISSUE TITLE
Add pack cli support for IBM ppc64le

### ISSUE THREAD

**Issue by valen-mascarenhas14** [buildpacks/pack#2084]
### Description
Build pack CLI for ppc64le architecture.

### Proposed solution
pack cli is currently supported for amd, arm and s390x architectures. We need to enable the pack on ppc64le architecture as well. We have buildpacks/lifecycle enabled for ppc64le and looking for pack cli support.

**Comment by jjbustamante** [comment]
Just to confirm, You don't need the binaries to be available in some package manager use with `ppc64le` right?, you just need the binaries compiled for that architecture.
