### ISSUE TITLE
Add credential helpers for publishing

### ISSUE THREAD

**Issue by poy** [buildpacks/pack#212]
The github.com/buildpack/lifecycle repo has a `UseCredHelpers` concept that enables simpler usage within an automated environment. This would be helpful for the `create-builder` command.

**Comment by ekcasey** [comment]
@poy Interesting that you bring this up. We were actually discussing remove the credential helper support from the lifecycle https://github.com/buildpack/lifecycle/issues/121.

The idea is that the docker `config.json` is respected, and users can add cred helpers there if they wish.

**Comment by poy** [comment]
That makes sense. How would users in things like buildtemplates set that up?

**Comment by ekcasey** [comment]
@poy sorry for the delayed response. If we are talking about build templates running in a k8s context, I believe a `docker-registry` type secret should serve most use cases.

We haven't gotten around to removing credential helper support from the lifecycle yet, so let us know if you think this will cause problems for you.

**Comment by Zanadar** [comment]
`pack create-builder` now supports publishing to a remote registry . 
 via the `--publish` flag See: https://github.com/buildpacks/pack/blob/master/create_builder.go#L21

AFAIK, that accomplishes what you need @poy Let me know if I'm wrong.
