### ISSUE TITLE
Installation of pack-cli on Ubuntu 24.04 LTS fails

### ISSUE THREAD

**Issue by gergoistvannagy** [buildpacks/pack#2152]
### Summary
Following the instruction here:
https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/ for Linux/Ubuntu
sudo add-apt-repository ppa:cncf-buildpacks/pack-cli fails to complete.

The repository is added to the source list, though as there is no Release file for Ubuntu 24.04 LTS the subsequent `sudo apt update` command fails to run.

---

##### Steps
1. use Ubuntu 24.04 LTS 
2. in a bash run `sudo add-apt-repository ppa:cncf-buildpacks/pack-cli`
3. see the output

##### Current behavior
PPA repository is added to the repository list though during the `add-apt-repository` this is the output (relevant part is copied only)

`Ign:5 https://ppa.launchpadcontent.net/cncf-buildpacks/pack-cli/ubuntu noble InRelease
Err:6 https://ppa.launchpadcontent.net/cncf-buildpacks/pack-cli/ubuntu noble Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
E: The repository 'https://ppa.launchpadcontent.net/cncf-buildpacks/pack-cli/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

##### Expected behavior
`ppa:cncf-buildpacks/pack-cli` is added as repository and with proper Release file there is no need to relax security check for `apt update`

---

### Environment
# System Details Report
---

## Report details
- **Date generated:**                              2024-05-13 15:27:03

## Hardware Information:
- **Hardware Model:**                              Hewlett-Packard HP ProBook 4340s
- **Memory:**                                      8,0 GiB
- **Processor:**                                   Intel® Core™ i3-3120M × 4
- **Graphics:**                                    Intel® HD Graphics 4000 (IVB GT2)
- **Graphics 1:**                                  AMD TURKS
- **Disk Capacity:**                               500,1 GB

## Software Information:
- **Firmware Version:**                            68IRR Ver. F.60
- **OS Name:**                                     Ubuntu 24.04 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-31-generic

##### pack info

I haven't reach this point to actually run that.

##### docker info

Not needed for the fix.

**Comment by jjbustamante** [comment]
We hope next pack `0.34.0` version will be available for Ubuntu `Noble Numbat`

**Comment by gergoistvannagy** [comment]
It's working using `0.34.0` as described here:
https://launchpad.net/~cncf-buildpacks/+archive/ubuntu/pack-cli
