### ISSUE TITLE
Publishing wrong architecture for `macos` intel binaries

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/pack#2167]
### Description
Once we released pack [0.34.0-rc1](https://github.com/buildpacks/pack/releases/tag/v0.34.0-rc1) I noticed the binaries for macos intel machine is actually a `arm64` binary, the reason is because the latest macos runner from github is now `macos14` and than runner is based on arm64 architecture.  Github [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) 

- When CI runs, we build binaries for linux, macos and windows 
- When a Release is created, build binaries for other architectures, like: linux-arm64, darwin-arm64, linux-s390x

The problem was that we were expecting the darwin binary built during CI to be based on amd64 and since the runner was updated this not true. We ended up shipping the same binary (arm64) twice

### Proposed solution

The easiest way to fix it, is to build by default the `arm64` binary during CI, and build the `amd64` when a release is done. The problem with this solution is that sometimes we ask people from the community to download binaries from a PR and in this case, if they running macos on intel, we will not have binaries available.

**Comment by natalieparellano** [comment]
Could we maybe cut an rc2 to allow more folks to try out the binary?
