### ISSUE TITLE
Creation of non-functional multi-arch buildpackage file when target is not specified.

### ISSUE THREAD

**Issue by ForestEckhardt** [buildpacks/pack#2176]
## Summary

When creating a buildpackage file that is a multi-arch buildpack there is no feedback that a target must be set through the `--target`. Instead a file is created that throws an error at build time.

### Steps

1. Clone https://github.com/paketo-buildpacks/procfile
2. Create temporary bin directory for the packaging tool `cd procfile && mkdir .bin`
3. Install the packaging tool `GOBIN="$PWD/.bin" go install -ldflags="-s -w" "github.com/paketo-buildpacks/libpak/cmd/create-package@v1.70.0"`
4. Create a multi-arch buildpack directory `.bin/create-package --destination build --version 1.2.3`
5. Create the buildpackage without specifying the target `pack buildpack package buildpackage.cnb --path build --format file`
6. Use buildpackage with relevant application. I used this Paketo sample https://github.com/paketo-buildpacks/samples/tree/main/procfile/procfile-sample. `pack build profile --path path/to/sample --buildpack buildpackage.cnb`

### Current behavior

During `pack buildpack package` I receive this message:
```
Successfully created package buildpackage.cnb and saved to file
```
During `pack build` I receive this error:
```
ERROR: failed to build: downloading buildpack: extracting from registry buildpackage.cnb: fetching image: image buildpackage.cnb does not exist on the daemon: not found
```

---

### Expected behavior

I expect that the artifact either fails to be created or that it works the same as multi-arch buildpack image. The latter would be a preferable interaction as it would allow for ease of local integration testing of buildpacks as the Paketo testing infrastructure is already configured to do so and as it would be difficult to maintain any reasonable type of buildpack testing registry. 

---

##### pack info
```
Pack:
  Version:  0.34.1+git-98f0eb4.build-5997
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.19.6

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13

Config:
  default-builder-image = "[REDACTED]"
```

**Comment by jjbustamante** [comment]
When running steps 5. from the reproduction steps

- `pack buildpack package buildpackage.cnb --path build --format file`

`pack` exports two *.cnd files

```bash
	buildpackage-linux-amd64.cnb
	buildpackage-linux-arm64.cnb
```

**Comment by jjbustamante** [comment]
Closing this issue, as we discussed in [slack](https://cloud-native.slack.com/archives/C0333LG1E68/p1717533184073549) we were probably using an old `pack` binary, new issue [2177](https://github.com/buildpacks/pack/issues/2176) was created to explore the idea of exporting just one .cnb files inside of it.
