### ISSUE TITLE
What does this error message mean

### ISSUE THREAD

**Issue by jasonkuhrt** [buildpacks/pack#222]
I am working on a custom build-pack but hitting this error when trying to run the built app:

```
❯ docker run --rm hello-k8s
Error: failed to launch: modify env: add layer env: readdirent: not a directory
```

Its not clear to me what the issue is 🤔

**Comment by jasonkuhrt** [comment]
Something in this build bash is causing this error:

```sh
# Install Poetry
layer_name="poetry"
poetry_version=0.12.16

export PATH="$layers_dir/poetry/bin":$PATH
if [ "$(get-layer-metadata "$layer_name" 2>/dev/null)" = "${poetry_version}" ]; then
  log "Reusing Poetry $poetry_version"
else
  log "Installing Poetry $poetry_version"
  rm -rf "$layers_dir/$layer_name"
  setup-layer "$layer_name" 'cache = true' 'build = false' 'launch = true' "metadata = \"$poetry_version\""
  curl --location --silent --show-error https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py --output get-poetry.py
  python get-poetry.py --version "$poetry_version" 1>/dev/null
  mv ~/.poetry/* "$layers_dir/$layer_name/"
fi
```

**Comment by sclevine** [comment]
What’s the structure of the `<layers>` directory populated by your buildpack? Does one of your layers happen to have a file (not a directory) called `env` in it?

The error you’re running into is from a [lifecycle](https://github.com/buildpack/lifecycle) component called the launcher that is able to dynamically modify the runtime environment.

See [here](https://github.com/buildpack/spec/blob/master/buildpack.md#build) for a summary of the buildpack-to-lifecycle interface.

**Comment by jasonkuhrt** [comment]
And within that, the offending line is:

```
  mv ~/.poetry/* "$layers_dir/$layer_name/"
```

**Comment by jasonkuhrt** [comment]
The contents of `~/.poetry` are

```
[builder] bin
[builder] env
[builder] lib
```

and in order to make poetry available to the app we move it to `"$layers_dir/poetry`

**Comment by jasonkuhrt** [comment]
@sclevine thanks for that info, yup `env` is a file there. Example from my machine:

```
❯ stat -F ~/.poetry/env
-rw-r--r-- 1 jasonkuhrt staff 37 Feb  4 14:04:20 2019 /Users/jasonkuhrt/.poetry/env
```

So a file called `env` in a layer causes problems? I'll check the links you sent

**Comment by jasonkuhrt** [comment]
I think a simple solution is to nest and isolate poetry content one folder down.

**Comment by sclevine** [comment]
> I think a simple solution is to nest and isolate poetry content one folder down.

If you still need the `bin/` and `lib/` directories automatically added to `$PATH` and `$LD_LIBRARY_PATH` respectively at runtime, you'll need to keep those directories in place. (Alternatively, you could use symlinks or set those env vars manually via `profile.d` or `env.launch/`.)

> it seems this is particular to the implementation and not in the spec. Unless I missed something while reading (skimming) it.

The [Build](https://github.com/buildpack/spec/blob/masteer/buildpack.md#build) section of the summary documents this with:

Output | Description
-- | --
`<layers>/<layer>/env/` | Env vars for launch and/or subsequent buildpacks
`<layers>/<layer>/env.launch/` | Env vars for launch (after env, before profile.d)

And there's a full specification of the behavior in the [Environment](https://github.com/buildpack/spec/blob/master/buildpack.md#provided-by-the-buildpacks) section.

**Comment by jasonkuhrt** [comment]
I meant move poetry env not the one expected by Buildpack.

I saw that part of the doc but it’s folders not files....?

**Comment by sclevine** [comment]
Not totally sure I understand your question, but for example:

The file:
```
${1}/poetry/env/SOME_POETRY_VAR
```
with contents:
```
/my/special/path
```
would set `SOME_POETRY_VAR` to `/my/special/path` in the environment for both subsequent buildpacks and the image at runtime.

Alternatively, if you put the file in `env.launch`:
```
${1}/poetry/env.launch/SOME_POETRY_VAR
```
then the env var would only be set at runtime.

Alternatively, if you need to modify the runtime environment based on other environment variables that might change after the image is built, you could use a profile.d (source-able, not executable) script:
```
${1}/poetry/profile.d/setup-poetry.sh
```
with contents:
```
export SOME_POETRY_VAR=${SPECIAL_RUNTIME_VAR}-${SOMETHING_ELSE}
```

**Comment by jasonkuhrt** [comment]
@sclevine oh just saying I'm not sure I follow the conflict in this case as `env` was a file from poetry, so why can't it exist with an env folder technically? Not saying its desirable (would be confusing) but just don't understand why its not possible.

**Comment by sclevine** [comment]
Are you asking if we could implement a feature in the lifecycle to ignore `env` when it's a file?

Or are you asking why the current lifecycle implementation blows up when it encounters an `env` file? (i.e., what line of code in the launcher results in the current behavior?)

**Comment by jasonkuhrt** [comment]
> Or are you asking why the current lifecycle implementation blows up when it encounters an env file? (i.e., what line of code in the launcher results in the current behavior?)

I think more this, as I think it would be confusing anyways to have env files allowed from user next to reserved-name env folders.

**Comment by sclevine** [comment]
> env was a file from poetry, so why can't it exist with an env folder technically?

Just to be totally clear, filesystems do not generally allow a file and a directory with the same name to co-exist in the same directory. I'm assuming you're asking whether a file called `env` could exist instead of a directory called `env` in cases where the directory would otherwise be empty.

> confirming that its technically not in the spec right?

You are correct: the spec does not explicitly say that creating `<layers>/<layer>/env` as a file will result in a build failure. But it does strongly suggest that `<layers>/<layer>/env` is reserved for a directory. We could certainly document that all files and directories mentioned are reserved for their intended purposes.

> I think it would be confusing anyways to have env files supported from user next to reserved-name env folder...

I agree 😄

**Comment by jasonkuhrt** [comment]
So, converting this thread into something actionable, I think if a file called `env` is present it should raise a descriptive error and link to the docs/spec. Assuming there is a reliable way to differentiate between file/dir which I always thought there was but you mentioned:

> Just to be totally clear, filesystems do not generally allow a file and a directory with the same name to co-exist in the same directory. 

But the error above says `not a directory` so pretty sure we should be able to do this... :)

**Comment by sclevine** [comment]
We can definitely differentiate between a file and a directory. Just pointing out (in case it wasn't obvious) that it's not possible for the buildpack to create an `env` file and an `env` directory in the same layer at the same time. We should always fail the build when an `env` file is created in a layer by mistake (and not generate an image at all).

If you're interested in contributing, it would be great if the lifecycle did more validation on layers created by buildpacks.

**Comment by natalieparellano** [comment]
Closing this issue as it seems resolved.
