### ISSUE TITLE
--cache flag does not respect case sensitivity

### ISSUE THREAD

**Issue by AbdullahWali** [buildpacks/pack#2229]
### Summary

When calling `pack build` using the `--cache` flag to bind a directory containing uppercase letters, `pack` incorrectly converts the directory to lowercase

ie, passing in `--cache type=build;format=bind;source=/tmp/MYTEMPDIR` results in pack binding to `/tmp/mytempdir`

I believe this is due to this line when parsing the `--cache` flag: https://github.com/buildpacks/pack/blob/f6b450fc1ae5c3706cd5359a688cb80266950171/pkg/cache/cache_opts.go#L89

---

##### Steps

1. Call `pack build` with a cache flag such as `--cache type=build;format=bind;source=/tmp/MYTEMPDIR`

##### Current behavior

Build cache ends up being stored under `/tmp/mytempdir`

##### Expected behavior

Build cache should be stored under `/tmp/MYTEMPDIR` 

---

##### pack info

Pack:
  Version:  0.24.0+git-79a40b7.build-3148
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.13.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8

Config:
(no config file found at /home/awali6/.pack/config.toml)

**Comment by keshavdalmia10** [comment]
Hi, I would like to work on this. This will be my first issue.

**Comment by natalieparellano** [comment]
@keshavdalmia10 we'd love to have your help here! Feel free to comment here if you would like any guidance around the implementation

**Comment by natalieparellano** [comment]
I am guessing that in the code linked above, you will only want to call `strings.ToLower` on the key, and not the value. You'll want to add a test in https://github.com/buildpacks/pack/blob/f6b450fc1ae5c3706cd5359a688cb80266950171/pkg/cache/cache_opts_test.go

**Comment by keshavdalmia10** [comment]
Thanks @natalieparellano for your guidance. Will start working on it.

**Comment by keshavdalmia10** [comment]
Hi @natalieparellano, I have raised the pull request for this. Please tell me if you find any changes required. Looking forward to contribute more!
