### ISSUE TITLE
Warn when volume mounting into `/workspace`

### ISSUE THREAD

**Issue by dmikusa** [buildpacks/pack#2237]
### Description

This isn’t a super common problem, but we do occasionally see people mount into workspace.

a.) It doesn’t make a ton of sense. /workspace is your app files, so if you want it there, just include it with your app files.
b.) Buildpacks can delete files in /workspace. For example, if you do a source build it’s common to delete all the source code so it’s not in the production image. Well, if you volume map into /workspace, your mapped files might get deleted too.

### Proposed solution
Warn so users know it's not a good idea

**Comment by CodeWreckPro** [comment]
Is anyone currently contributing to this issue?, I would like to pick up the issue.

**Comment by anthonydahanne** [comment]
yes, already submitted a PR #2238
