### ISSUE TITLE
Integration with knative?

### ISSUE THREAD

**Issue by jasonkuhrt** [buildpacks/pack#228]
It was recently [announced that knative-build is going away](https://groups.google.com/forum/#!topic/knative-users/zd5Ni5cCcvg). Now other builders can be brought in. Is buildpacks a clear choice here and why wouldn't it be the obvious one? Should a docs section be added about how to setup the integration on a system?

**Comment by Zanadar** [comment]
@ekcasey @sclevine Care to weigh in here?

**Comment by ekcasey** [comment]
@jasonkuhrt `knative-build` and it's spinoff `tekton` both essentially provide a way to template and run arbitrary tasks. For both, we have provided buildpack task templates. Here is a link to the tekton task https://github.com/tektoncd/catalog/blob/master/buildpacks/buildpacks-v3.yaml.

https://github.com/pivotal/kpack provides a different model for executing buildpacks on k8s. Wiring `kpack` and `knative` together should be straightforward. It's currently being done by [riff](https://projectriff.io/). I suppose we could provide some documentation or guidance here.

Of course, if anyone wants to discuss native support for builpacks in knative I'm happy to chat ;)

**Comment by natalieparellano** [comment]
Is there any action to be generated from this issue? If not, could we go ahead and close it?

**Comment by natalieparellano** [comment]
It seems like the initial question has been answered. Closing this issue as it's technically not applicable to `pack`.
