### ISSUE TITLE
Show buildpack's order in `inspect-builder` output

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpacks/pack#253]
**Given** a buildpack TOML includes an `order` field with references to one or more other buildpacks
**And** that buildpack is included in builder X
**When** I run `pack inspect-builder X`
**Then** I see the ID and version for each nested buildpack in the output
```
...
Buildpacks:
  ID                  VERSION
  some.nested.1
  some.buildpack.a    v0.0.2-RC3
    Group #1:
      some.nested.1   v0.0.1
      some.nested.2   v0.0.2
    Group #2:
      some.nested.3   v0.0.3
  some.buildpack.b    v0.0.0-RC2
  some.nested.3       v0.0.3
  some.buildpack.c    v1.0.19
  some.nested.2       v0.0.2
    Group #1:
      some.nested.4   v0.0.4
  some.nested.4       v0.0.4
...
```

Notes:
- Nested buildpacks also appear in top-level list. If they have further nested buildpacks, they will be shown under their top-level entry
- Order of nested buildpacks as they appear in top-level list is randomized in the output above, just to make it clear that they don't necessarily have to appear before or after their parents (they just need to exist)

**Comment by sclevine** [comment]
See https://github.com/buildpack/pack/issues/251 for metadata format. By default, just show the top-level order. That structure will let you pass a `--depth` flag to resolve it further.

**Comment by Zanadar** [comment]
It would also be useful to see group labels in this output (not sure if that's still a thing?)

**Comment by ekcasey** [comment]
@Zanadar labels are going away per the distribution spec

**Comment by jromero** [comment]
@Zanadar what's the reason this was closed?

**Comment by Zanadar** [comment]
@jromero misread the comments above! Reopening.

**Comment by natalieparellano** [comment]
Possible way forward: change the way `Detection Order` is presented and incorporate a `--depth` flag. We are not exactly sure how this will play out so this probably requires some spiking and experimentation.

**Comment by dwillist** [comment]
Taking a look at this
