### ISSUE TITLE
Expose a way to control labels on all built and intermediate images

### ISSUE THREAD

**Issue by josegonzalez** [buildpacks/pack#258]
In the @dokku project, I plan on replacing our existing herokuish setup with `pack` (or some derivative of it for the sake of modifying the output to be a bit more... user-friendly?). It would be great if we could expose a way to control labels for a `pack build` call, such that we can include custom labels.

The dokku project would add the following labels:

```
LABEL com.dokku.app-name $APP
LABEL org.label-schema.schema-version 1.0
LABEL org.label-schema.vendor dokku
LABEL dokku
```

These are used for scoping intermediate container and image cleanup.

**Comment by Zanadar** [comment]
@josegonzalez We've discussed this and related issues a couple times in WG. Would you be amenable to opening an RFC on the subject?

**Comment by natalieparellano** [comment]
Closing this for now as it would require an RFC for further discussion into how to implement it.
