### ISSUE TITLE
Buildpackage layers label format

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#289]
### Based on work from #251

**Given** I have buildpack `bp.one@1.2.3` with `buildpack.toml`:
```
[buildpack]
  id = "bp.one"
  version = "1.2.3"

[[order]]
[[order.group]]
  id = "bp.nested"
  version = "2.3.4"
```
**When** I create a buildpackage with the following configuration:
```
[default]
id = "bp.one"
version = "1.2.3"

[[buildpacks]]
uri = "https://example.com/bp.one_1.2.3.tgz"

[[packages]]
ref = "package/bp.nested_2.3.4"

[[stacks]]
id = "some.stack.id"
```
**Then** the buildpackage contains the following labels:
-  `io.buildpacks.buildpack.layers`:
```json
{
  "bp.one": {
    "1.2.3": {
      "layerDiffID": "8abc...",
      "order": [
        {"group": [{"id": "bp.nested", "version": "2.3.4"}]}
      ]
    }
  },
  "bp.nested": {
    "2.3.4": {
      "layerDiffID": "9acc..."
    }
  }
}
```

**Comment by ekcasey** [comment]
@sclevine In the above schema for `io.buildpacks.buildpack.layers` are you imagining the `layerDigest` value as the the digest of the compressed layer or the uncompressed layer?

**Comment by sclevine** [comment]
Compressed

**Comment by ekcasey** [comment]
That makes sense to me from an API perspective. It will slow things down in the daemon case. We don't currently compress layers for any reason when creating a builder against the daemon.

**Comment by ekcasey** [comment]
Sorry I meant to ask this question on #251. buildpackages and the daemon are another can of worms.

**Comment by ameyer-pivotal** [comment]
This works for non-meta buildpacks. For a metabuildpack (one with an `order` but no stacks), I get an error like:

```<buildpack> must support at least one stack```

**Comment by ameyer-pivotal** [comment]
Noticed that this will result in a `stacks: null` field for a meta-buildpack, rather than the key being omitted. Other than that, this passes acceptance.

**Comment by jromero** [comment]
> Noticed that this will result in a `stacks: null` field for a meta-buildpack.

This doesn't seem to be a true violation given that a `null` value and missing value represent the same thing.

**Comment by ameyer-pivotal** [comment]
Agreed that it's not illegal or invalid per se. Just calling out that it's different from the ACs. I don't think it's important to fix at the moment as there's no functional impact.
