### ISSUE TITLE
Allow additional buildpacks to be added to default builder during pack build

### ISSUE THREAD

**Issue by sclevine** [buildpacks/pack#304]
Example with git-ssh buildpack:
```
pack build myapp --buildpacks-from-builder --buildpack ~/workspace/buildpacks/git-ssh-buildpack -e GIT_SSH_KEY
```

**Comment by jromero** [comment]
Is there more context to this request? Trying to understand how it ties into order(s). Would the additional buildpack be added to every order group as the last entry?

**Comment by sclevine** [comment]
`--buildpacks-from-builder` would behave just like `--buildpack`, but where the whole `order.toml` inside of the builder is treated as a meta-buildpack. So any buildpacks specified with `--buildpack` are placed before or after it depending on the flag order.

**Comment by jromero** [comment]
Can't seem to find a built-in way in `cobra` (our current cli lib) to determine the position of a flag relative to another flag.


For example the commands below are treated the same.
```
pack build myapp --buildpacks-from-builder --buildpack ../ssh-buildpack
pack build myapp --buildpack ../ssh-buildpack --buildpacks-from-builder
```

From a UX perspective it's a little awkward to think that the order of two different flags impact each other.

We can determine positions based on the same flags.  (This works currently).

For example:
```
pack build myapp --buildpack ../ssh-buildpack --buildpack ../git-buildpack
pack build myapp --buildpack ../git-buildpack --buildpack ../ssh-buildpack
```

### Alternatives

Some possible low level effort solutions that _might_ make for a cleaner UX:

1. Add a format for a buildpack to represent "embedded" buildpacks.
```
# keyword
pack build myapp --buildpack ../ssh-buildpack --buildpack embedded

# git style
pack build myapp --buildpack ../ssh-buildpack --buildpack --

# kubectl style
pack build myapp --buildpack ../ssh-buildpack --buildpack from=builder
```

2. Add information to flag for placement. Con: not as flexible as option 1.
```
pack build myapp --buildpack ../ssh-buildpack --buildpacks-from-builder=before
pack build myapp --buildpack ../ssh-buildpack --buildpacks-from-builder=after
```
