### ISSUE TITLE
How do you not include "/workspace" in the final image?

### ISSUE THREAD

**Issue by loosebazooka** [buildpacks/pack#313]
So for a java application image, built by maven: all the maven sources and build outputs and everything in-between exist (and presumably should) in the `/workspace` directory during build.

However, if I'm trying to build a minimal java app, I don't want this stuff, it's kind of useless to me.
I know I'm building a jar, so I take it and put it in a layer `$layerdir/app` or something and that's all i want.

The only solution I can think of is a `rm -rf *` while in workspace, but that sounds crazy.

It's either this or I'm writing my buildpack wrong, and the normal way to write a buildpack is to assume that everything that happens in workspace is meant to be there.

I would think there was an exclusion mechanism similar to `${layersdir}/layer.toml`, so something like `${layersdir/workspace.toml}`. or maybe just `workspace.toml`, I don't know.

**Comment by sclevine** [comment]
Currently, the only mechanism for this is to have the buildpack remove any files from the `/workspace` directory that you don't want in the final image. I agree that this is less than ideal.

However, there's an (unimplemented) feature called [slices](https://github.com/buildpack/spec/blob/master/buildpack.md#launchtoml-toml) that's intended to give buildpack authors more control over the layerization of `/workspace`. Eventually, each item in the `[[slices]]` list could take an `exclude = true` directive that excludes the slice from the final image. Would be great to see an RFC for this!

**Comment by loosebazooka** [comment]
Sorry, I read go embarrassingly slow. From what I can gather, taking a quick glance at the [code](https://github.com/cloudfoundry/build-system-cnb/blob/master/runner/runner.go#L46):
1. build the app
2. clean the approot
3. expand the final artifact into approot (not sure what is being expanded yet)
which makes sense.

What's hard to handle I guess is something that is a multistep build involving multiple buildpacks. From what I understand, and please correct me if I'm wrong, the workspace is copied from local disk to a docker volume **once** so cleaning up the workspace has to happen as a final step -- while using knowledge from earlier steps?

@sclevine I haven't thought too much about slices, but I would like something like:

I would think there would be conventions on slicing of a workspace
1. Different buildpacks can contribute to the "slice plan"/`workspace-slices.toml`
1. Slices are finalized in some sort of pack step after all buildpacks have run
1. There some sort of standard wildcarding
1. If `workspace-slices.toml` exists, all files not included in the config are not included in the final image
1. if no `workspace-slices.toml` then all files go into the final image

Conventions I feel less confident about
1. Slice config is limited to files in `/workspace`: This makes it hard to access build artifacts outside the application dir like `~/.m2/repository` or `~/.gradle/caches` or whatever other languages do that I'm not aware of.
1. slice config can determine a final location for its files. Either we specify a `dest` or we just mark those files for "saving". This again depends on how much "saving" we allow, if only in the `/workspace` dir then it makes it harder to save resources outside the workspace (like dependencies for example).

`workspace-slices.toml` (chrooted(? or whatever) at `/workspace`)
```toml
[[slices]]
name = "application"
uri = "/workspace/target/my-app.jar" # uri or path or src
# dest = "/app/my-app.jar"

[[slices]]
name = "dependencies"
uri = "./workspace/target/copied-dependencies/*.jar" # uri or path or src
# dest = /app/.
```

**Comment by ameyer-pivotal** [comment]
@loosebazooka There are a lot of great ideas here. This should go through an RFC, as mentioned by @sclevine, where we can continue the discussion more concretely and with a more targeted audience. As it stands, it's more of a spec concern, and any implementation would likely be handled by the [`lifecycle`](github.com/buildpacks/lifecycle) and/or buildpacks, rather than `pack`.
