### ISSUE TITLE
Add labels to pack volumes (to help association/purging)

### ISSUE THREAD

**Issue by josegonzalez** [buildpacks/pack#317]
One feature Dokku has is the ability to run `repo:purge-cache`, which effectively deletes the cache for given app. Pack (libbuildpack?) uses a docker volume to store the cache but only exposes a mechanism to delete that cache under the `build` command.

It would be great if either of the following were implemented:

- labels on the volumes so we can associate them with a given app image
- a command that can be run which will purge the cache for a given app image

**Comment by Zanadar** [comment]
`pack build --clear-cache` doesn't satisfy this system use case at the moment.

**Comment by Zanadar** [comment]
This could help with discoverability or attribution of volumes created during an action, if labelling were used for those resources.

**Comment by Zanadar** [comment]
Usecase:
- Purge all volumes that `pack` has ever created
- Print volumes names for *an* image

**Comment by dfreilich** [comment]
Hey @josegonzalez - this has been languishing here for quite a bit. Is this still something that would be helpful? I'd lean towards labelling the volumes, to reduce the number of extra commands we have.

**Comment by josegonzalez** [comment]
Yeah labeling would be more than enough. I think a label for the general "I'm a pack volume" and "I'm a pack volume for this image" would be good. Purging can then be implemented by docker commands.

Yes, I realize that buildpack cache also has a layer cache on the remote registry, but this helps with the local cache use case.
