### ISSUE TITLE
Request: Move to standard config param names

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpacks/pack#322]
For commands like `create-builder -b` and `create-buildpackage -p`, we should unify the config param names to `-c` (short) and `--config` (long).

An alternative is `-f`/`--file` 

To migrate over to the standard, we could deprecate the old param names and maintain compatibility for a release.

**Comment by jromero** [comment]
I vote `-c`/`--config`. 

Here are a few sample of relatable applications that use `--config`:

1. k8s - https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file
2. chef - https://docs.chef.io/ctl_chef.html
3. ansible - https://docs.ansible.com/ansible/latest/cli/ansible-config.html#common-options

**Comment by dfreilich** [comment]
@jromero This has been open for quite a while, and hasn't had so much further discussion. Should this be considered ready?

**Comment by ameyer-pivotal** [comment]
Thought it's been stale, I still think it should be considered. The flags as they are are inconsistent and therefore a bit confusing. :)

**Comment by jromero** [comment]
Are there, or can we foresee any, commands that have more than one "config" input file?
