### ISSUE TITLE
pack build should log lifecycle arguments

### ISSUE THREAD

**Issue by josephlewis42** [buildpacks/pack#335]
It's difficult to debug differences between running pack build locally and a remote build that calls the lifecycle binaries individually. Adding additional debugging info when calling lifecycle steps would be extremely helpful.

For example, the run function could print out the binaries, arguments, and environment variables it uses:

https://github.com/buildpack/pack/blob/master///build/phase.go#L164

**Comment by natalieparellano** [comment]
It looks like alignment is needed around how to print out the environment (if indeed we do want to do that). Tagging for discussion.

Perhaps work to address https://github.com/buildpacks/pack/issues/62 would also help with that pain point here.

**Comment by dfreilich** [comment]
This definitely would have been useful to me, when working with `Tekton`, to get a sense for what arguments to pass into the lifecycle. 👍  from me!

**Comment by jromero** [comment]
Let's break this down into two issues:

1. Provide debug output of binary and arguments. (this issue)
2. Provide debug output of env vars passed to container + env vars in `/platform/env` (deferred)
