### ISSUE TITLE
Local cache of assets downloaded

### ISSUE THREAD

**Issue by drnic** [buildpacks/pack#340]
```
[builder] Go Compiler Buildpack 0.0.29
[builder]   Go 1.13: Contributing to layer
[builder]     Downloading from https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz
```

As a `pack` user, I don't expect to see `Downloading from https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz` more than once. I assume that once `pack` has downloaded an asset, that it will be cached locally, and will be fetched from my local cache in future.

Relates to https://github.com/buildpack/pack/issues/339

**Comment by sclevine** [comment]
Pack provides a volume for caching, but it’s up to the buildpack to use that cache. Are you using the same image tag when you rebuild?

I believe the CF Go CNB does cache Go, but if you see otherwise, please open an issue in that project repo: http://github.com/cloudfoundry/go-CNB

**Comment by drnic** [comment]
I'm asking for an additional caching concept - the downloaded assets being reused across different images being built.

**Comment by sclevine** [comment]
There is no special hook from the buildpack into the lifecycle or pack to accomplish this. Downloading a file is just arbitrary execution of buildpack code and arbitrary network traffic. Something like this could be implemented using a caching proxy and buildpack modifications, but probably wouldn’t make sense in the pack or lifecycle implementions.

**Comment by nebhale** [comment]
Agreed, the more practical way to deal with this without introducing cache-poisoning vulnerabilities is that buildpack package all dependencies for offline usage.  And the buildpacks do, we just continue to be subject to (justified) CFF rules that prevent us from distributing buildpacks in that form.

**Comment by natalieparellano** [comment]
Closing this issue for now. An RFC would be necessary to provide further guidance. Changes to the spec would most likely be necessary making it unsuitable for pack to implement it at this point in time.
