### ISSUE TITLE
pack inspect-builder --json/yaml/toml

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#387]
I'd love to see `pack inspect-builder --format <json/yaml/toml>` so we could machine parse the output (of commands generally)

**Comment by jromero** [comment]
Loosely relates to #378

**Comment by ekcasey** [comment]
How about `--output`  (`-o` short version) instead? The usage will be familiar to users of `kubectl`.

**Comment by Zanadar** [comment]
💥 sounds great!

**Comment by natalieparellano** [comment]
Possible acceptance criteria:

**When** I run `pack inspect-builder --output json` or `pack inspect-builder --o json`
**Then** I see the output in json format

**When** I run `pack inspect-builder --output yaml` or `pack inspect-builder --o yaml`
**Then** I see the output in yaml format

**When** I run `pack inspect-builder --output toml` or `pack inspect-builder --o toml`
**Then** I see the output in toml format
