### ISSUE TITLE
Publicize Goals, Milestones, and Progress of Project

### ISSUE THREAD

**Issue by nebhale** [buildpacks/pack#41]
In order to help the community have visibility into the project, it's important to publicize the goals, milestones (bonus for a non-binding schedule), and progress of the `pack` CLI as it moves towards 1.0.

**Comment by Zanadar** [comment]
@nebhale I _think_ this is satisfied by: https://github.com/orgs/buildpack/projects/1 (w. milestones, etc.)

**Comment by nebhale** [comment]
Concur.

**Comment by mwarkentin** [comment]
@nebhale @zmackie looks like that link is 404 now. I was curious if there was a roadmap to 1.0 for pack and this is what I came across. Anywhere else I should be looking?

**Comment by dfreilich** [comment]
@mwarkentin There is no firm github roadmap, though the roadmap for 2020 is here: https://medium.com/buildpacks/cloud-native-buildpacks-2020-roadmap-b7e43876473a
