### ISSUE TITLE
provide a flag to easily extract image reference/image-id/digest

### ISSUE THREAD

**Issue by cppforlife** [buildpacks/pack#410]
ive added pack support to [kbld](https://get-kbld.io) and had to use a regex to extract image id from output like so: https://github.com/k14s/kbld/blob/8f03c2f4c34c5326d0b4a4a5b5ea5fa1005e8236/pkg/kbld/image/pack.go#L12-L17

ideally there would be another way, may be a flag that takes a file path (tmp file) that would get populated with some json with metadata?

**Comment by jabrown85** [comment]
I wonder if pack should consider having a flag that makes all output JSON messages. Similar to how docker communicates data for pushing images and reporting progress for instance.

**Comment by Zanadar** [comment]
@jabrown85 https://github.com/buildpack/pack/issues/387 related

**Comment by dfreilich** [comment]
@cppforlife @jabrown85 This does seem pretty related to #387, I'll close it in favor of that. If you think that this is a separate concern, feel free to reopen it.
