### ISSUE TITLE
Verbose logging is not applied to analyze phase when publishing

### ISSUE THREAD

**Issue by philwebb** [buildpacks/pack#419]
The `withLogLevel` method is not applied to the "analyzer" phase that is created if `publish` is `true`. I believe that this [this line](https://github.com/buildpacks/pack/blob/ce90e90d25ae2f9aaef1d5f04ca19d927fa6bf16/internal/build/phases.go#L85) should be wrapped in `l.withLogLevel`.

**Comment by philwebb** [comment]
I also just noticed that it's also [not applied](https://github.com/buildpacks/pack/blob/ce90e90d25ae2f9aaef1d5f04ca19d927fa6bf16/internal/build/phases.go#L111) to the `build` phase.

**Comment by natalieparellano** [comment]
Possible acceptance criteria:

**When** I run `pack build` with `--publish`
**And** I inspect the output
**Then** I should see verbose logging from `analyzer` (not sure exactly what verbose logging looks like but we could add it later)
**And** I should see verbose logging from `build`
