### ISSUE TITLE
Add short flag for builder in `pack build`

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#424]
As a developer, I'd like to be able to specify the builder using `-b` when calling `pack build`.

Why `-b` for builder and not buildpack? Most common use case is to specify a builder. Specifying a buildpack is more targeted towards an edge case for testing, troubleshooting or debugging.

**Comment by sclevine** [comment]
> Most common use case is to specify a builder. Specifying a buildpack is more targeted towards an edge case for testing, troubleshooting or debugging.

I'm not sure if this will remain true with the introduction of buildpackage support, especially if we add a `--from-builder` flag that makes `--buildpack` easier to use with the buildpacks on the builder.

**Comment by thephw** [comment]
I am inclined agree with @jromero, but I think that usage may depend on the web frameworks being built. For certain monolithic targets like Ruby on Rails you'll have more than one buildpack typically by default, but for more microservice targets you may have a single buildpack. Specifying the builder work well for both and takes advantage of the detect step.

Whats the context around buildpackage support?

**Comment by jromero** [comment]
RE: @sclevine 

packages don't take away from the fact that pack _needs_ a builder to build with. `--buildpacks` are optional and arguably ideal to omit in most workflows since you want the builder to detect the best option. (I think this leans a little on what @thephw has stated.)

Currently, the fact that you have to use state, by calling `set-default-builder`, is less than ideal IMO. `set-default-builder` can be seen as a nice-to-have feature but not a prerequisite for any workflow.

**Comment by Zanadar** [comment]
What about `-B`? Having a short flag for both (buildpacks and builder) would be nice. I know buildpacks authors frequently use `--buildpack x --buildpack Y --buildpack Z` during testing.

So to summarize:
```bash
-B --builder
-b --buildpack
```

**Comment by jromero** [comment]
@Zanadar Interesting... The thought of case-insensitive Windows did come to mind but [it seems like it might not be an issue](https://en.wikipedia.org/wiki/Command-line_interface#Option_conventions_in_DOS,_Windows,_OS/2). I like the proposal.

**Comment by jromero** [comment]
@sclevine / @jkutner / @hone  We've got a PR (#437) for @Zanadar's proposal to this issue. Any objections to this solution?

**Comment by jkutner** [comment]
I'm fine with `B` and `b`. I agree with @sclevine that the use of `--buildpack` will become more common with buildpackages and a buildpack registry. The builder will usually be set as a default.
