### ISSUE TITLE
Unactionable error during builder validation

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#431]
In debugging #430 I attempted to create a config with duplicate CNBs removed. However this caused issues with versions, I think. 
I got this rather cryptic error:

`ERROR: validating buildpacks: buildpack org.cloudfoundry.node-engine@0.0.124 not found on the builder`. 

It would be nice to have something actionable out of that error. It reads like something for a developer to debug, rather giving the user something to fix.

**Comment by jromero** [comment]
Related to https://github.com/buildpacks/pack/issues/306.

This is UX concern. I am all in favor for it and would like to discuss what the best strategy would be. We could look at them on a case-by-case basis or, preferably, create a strategy for providing _assistive_ text.

Initial ideas: 
1. Create error types that could be asserted against at the `cmd` package and provide additional information there.
2. Create error types that have assistive text built into them that is displayed as part of `error.Error()`.
