### ISSUE TITLE
Chore: Compute previous pack fixtures in CI

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#443]
Remove the `pack_previous` directory and compute the proper fixtures directory from the last pack release's current fixtures.

**Comment by ameyer-pivotal** [comment]
Confirmed works in Concourse: https://ci.buildpacks.io/teams/main/pipelines/pack/jobs/compatibility/builds/117

**Comment by ameyer-pivotal** [comment]
Due to renaming `pack_current` -> `pack_fixtures`, we'll need to follow up after releasing pack 0.7.0 and change Concourse to look for fixtures at `pack_fixtures` rather than `pack_current`. Card created in planning board to remind us.
