### ISSUE TITLE
Remove pack run

### ISSUE THREAD

**Issue by Zanadar** [buildpacks/pack#449]
Now that https://github.com/buildpacks/rfcs/pull/36 is merged, we should remove the `pack run` command.

**Comment by michiboo** [comment]
Hi Can I have a go at this issue?

**Comment by Zanadar** [comment]
@michiboo That'd be great!

**Comment by Zanadar** [comment]
Accepting:
```
± zm |master U:1 ✗| → ./out/pack run
Error: unknown command "run" for "pack"
Run 'pack --help' for usage.
```
