### ISSUE TITLE
Feature: pack can output a `.cnb` file

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#458]
### Description:

The builpacks [distributions spec](https://github.com/buildpacks/spec/blob/master/distribution.md#buildpackage) specifies that buildpackages can be packaged as a `.cnb` file 

>A .cnb file MUST be an uncompressed tar archive containing an OCI image. Its file name SHOULD end in .cnb.

#### standard output
Given I have a buildpack with appropriate package.toml
When I run `pack package-buildpack my/bp -p package.toml -o bp.cnb`
Then I should see a new file `bp.cnb`
And the `bp.cnb` format should be of tar
And the `bp.cnb` contents should match that of the [OCI image layout spec](https://github.com/opencontainers/image-spec/blob/master/image-layout.md)

### Questions

* How do we interop the saving to image vs saving to file while taking into consideration backwards compatibility?

**Comment by zmackie** [comment]
https://github.com/moby/moby/tree/master/image/spec has an overview of the various versions of the spec

**Comment by jromero** [comment]
Should be able to leverage GGCR's image layout package: https://github.com/google/go-containerregistry/tree/master/pkg/v1/layout

**Comment by jromero** [comment]
> How do we interop the saving to image vs saving to file while taking into consideration backwards compatibility?

#### Option 1
We can make it so that the positional argument MUST end in `.cnb` for it to output as 

```shell
pack package-buildpack my/bp -p package.toml
#vs 
pack package-buildpack bp.cnb -p package.toml
```

#### Option 2
We can change the format of the command and remove positional arguments.

```shell
pack package-buildpack --image my/bp -p package.toml
#vs 
pack package-buildpack --file bp.cnb -p package.toml
```

#### Option 3
A new command. (can't think of a name)

```shell
pack package-buildpack my/bp -p package.toml
#vs 
pack package-buildpack-as-file bp.cnb -p package.toml
```

**Comment by zmackie** [comment]
I_think_ I prefer option 2 as being more explicit.

**Comment by kvedurmu** [comment]
I agree with @zmackie. Not a huge fan of positional arguments in general

**Comment by jromero** [comment]
Another option for the UI/UX:

#### Option 4

Format flag with default format `image`.

```
pack package-buildpack my/bp -p package.toml

# same as hence backwards compatible

pack package-buildpack my/bp --format image -p package.toml

# vs 

pack package-buildpack bp.cnb --format cnb -p package.toml
```

_NOTE: This is more inline with `crane pull --format ... <image>` and slightly inline with future work with output [`pack inspect-builder ... --output json`](https://github.com/buildpacks/pack/issues/490)_

Thoughts?

CC: @kvedurmu @zmackie @natalieparellano @simonjjones

**Comment by natalieparellano** [comment]
I like option 4. Being inline with other art is very compelling.

**Comment by sclevine** [comment]
Looks great, only suggestion would be `--format file` instead of `--format cnb`. The on-registry format is still CNB, just not on-disk. We could even select `--format file` automatically when the arg ends in `.cnb` (but no strong opinion about that part).
