### ISSUE TITLE
Remove lifecycle symlink from lifecycle layer creation logic

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#460]
The symlink from `/lifecycle -> /cnb/lifecycle` is no longer needed in builders (after releasing pack 0.8.0), as pack 0.7.0+ will invoke lifecycle from `/cnb/lifecycle`.

### Acceptance Criteria

**Given** a `pack` with this change
**When** I create a builder with `pack create-builder`
**And** I run a container from the builder image
**Then** I should not see a symlink from `/lifecycle` to `/cnb/lifecycle` in the filesystem

### Notes

See below where we are creating the symlink today:

https://github.com/buildpacks/pack/blob/070802169e288f849a9ddd7ad0ce64f5de59ee87/internal/builder/builder.go#L664-L672

**Comment by Zanadar** [comment]
@natalieparellano Ported from a card. Please flesh out.

**Comment by ameyer-pivotal** [comment]
@Zanadar Done :)
