### ISSUE TITLE
pack build --publish does not cache during export

### ISSUE THREAD

**Issue by matthewmcnew** [buildpacks/pack#476]
### Summary

A `pack build` with `--publish` with the lifecycle `0.6.0` will skip exporting the cache. 

```
 Warning: Not exporting cache: no cache flag specified.
Successfully built image gcr.io/cf-build-service-public/asc-fix/controller
Using default tag: latest
```

It appears that the `cache-dir` is only appended to the lifecycle args when not publishing?

https://github.com/buildpacks/pack/blob/c4636375b6a7e4388dd96ed64fd3baebf7d260e8/internal/build/phases.go#L158

---

##### Steps

`pack build my/image --builder <builder/with-lifecycle-0.6.0> --publish`

**Comment by ekcasey** [comment]
I was JUST about to file this myself. This is fairly catastrophic imho

**Comment by jromero** [comment]
- **Impact:**
    - This is an issue on pack >= `0.6.0` and lifecycle = `0.6.0`
    - Any cached layers are not persisted between builds
        - For example, as a Java developer, this would mean that I must download the JDK for every build.
- **Effort**:
    - Minimal. See https://github.com/buildpacks/pack/pull/479
- **Risk:**
    - Based on changes proposed in https://github.com/buildpacks/pack/pull/479 the risk is minor.

**Comment by jromero** [comment]
Resolved by https://github.com/buildpacks/pack/pull/479
