### ISSUE TITLE
pack create-builder should "conform" buildpackages to the target stack

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#484]
### Description

Given the linked [buildpack](https://github.com/buildpacks/samples/blob/hello-universe-validation/buildpacks/hello-universe/buildpack.toml), [buildpackage](https://github.com/buildpacks/samples/blob/hello-universe-validation/buildpacks/hello-universe/buildpack.toml) and [builder.toml](https://github.com/buildpacks/samples/blob/hello-universe-validation/builders/alpine/builder.toml), i received an error, which seem like it might have something to do with the fact that buildpackages are not "conformed" to builders.

```bash
± zm |hello-universe-validation U:1 ✗| → pack create-builder dev.registry.pivotal.io/cnb-contrib/sample-builder:hello-universe-etc --publish -b builders/alpine/builder.toml
Downloading from https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1+linux.x86-64.tgz
25.6 MB/25.6 MB
ERROR: validating buildpacks: buildpack io.buildpacks.samples.ruby-bundler@0.0.1 does not support stack io.buildpacks.samples.stacks.alpine
```

the buildpackage:
```bash
[Current Layer Contents]────────────────────────────────────────────────────────────────
Permission     UID:GID       Size  Filetree
----------         0:0     7.9 kB  └── cnb
----------         0:0     7.9 kB      └── buildpacks
drwxr-xr-x         0:0     1.7 kB          ├── io.buildpacks.samples.hello-moon
drwxr-xr-x         0:0     1.7 kB          │   └── 0.0.1
-rw-r--r--         0:0      429 B          │       ├── README.md
drwxr-xr-x         0:0      922 B          │       ├── bin
-rwxr-xr-x         0:0      489 B          │       │   ├── build
-rwxr-xr-x         0:0      433 B          │       │   └── detect
-rw-r--r--         0:0      317 B          │       └── buildpack.toml
drwxr-xr-x         0:0     1.3 kB          ├── io.buildpacks.samples.hello-universe
drwxr-xr-x         0:0     1.3 kB          │   └── 0.0.1
-rw-r--r--         0:0      494 B          │       ├── README.md
-rw-r--r--         0:0      770 B          │       └── buildpack.toml
drwxr-xr-x         0:0     1.7 kB          ├── io.buildpacks.samples.hello-world
drwxr-xr-x         0:0     1.7 kB          │   └── 0.0.1
-rw-r--r--         0:0      322 B          │       ├── README.md
drwxr-xr-x         0:0     1.0 kB          │       ├── bin
-rwxr-xr-x         0:0      538 B          │       │   ├── build
-rwxr-xr-x         0:0      488 B          │       │   └── detect
-rw-r--r--         0:0      319 B          │       └── buildpack.toml
drwxr-xr-x         0:0     3.3 kB          └── io.buildpacks.samples.ruby-bundler
drwxr-xr-x         0:0     3.3 kB              └── 0.0.1
-rw-r--r--         0:0      220 B                  ├── README.md
drwxr-xr-x         0:0     2.8 kB                  ├── bin
-rwxr-xr-x         0:0     2.2 kB                  │   ├── build
-rwxr-xr-x         0:0      684 B                  │   └── detect
-rw-r--r--         0:0      265 B                  └── buildpack.toml


```

My best stab at explaining the issue:
`hello-universe` contains the `ruby-bundler` buildpack, which only runs on `bionic`. The other buildpacks it contains have both `alpine` and `bionic` stacks. The builder was targeting `alpine`, but saw the extraneous `bionic` buildpack (`ruby-bundler`) when it resolved the child buildpacks.

### Proposed solution

When a builder is created from a buildpackage, the buildpacks or groups that don't apply to the target stack should be ignored. It shouldn't be up to the user to create a buildpackage for a single stack (or if so, we need to have some way of helping them keep track because there's a large remove from where the stack is set and where it matters:

### Describe alternatives you've considered

buildpackages are specific to a stack.

**Comment by zmackie** [comment]
Diagram that describes the disconnect
<img width="1065" alt="stack issue" src="https://user-images.githubusercontent.com/5925347/73492833-78834d80-437f-11ea-8b80-246e9f2e7da5.png">

**Comment by jromero** [comment]
@zmackie I'd like to have someone triage this before considering it a feature request. The spec is very specific as to how this works so if there is a request here it would most likely require a spec change. Otherwise, it might be as simple as making the sample buildpackage work across all sample builders.
