### ISSUE TITLE
pack inspect-image should accept an --output flag

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#490]
### Description
`pack inspect-image --bom` produces a wall of text that is hard to read. We should make it easier to understand the output of this command.

### Proposed solution
Output the data in a format that I want.

### Possible acceptance criteria

**When** I run `pack inspect-image --output json` or `pack inspect-image -o json`
**Then** I see the output in json format (with BOM information)

**When** I run `pack inspect-image --output yaml` or `pack inspect-image -o yaml`
**Then** I see the output in yaml format (with BOM information)

**When** I run `pack inspect-image --output toml` or `pack inspect-image -o toml`
**Then** I see the output in toml format (with BOM information)

Don't break the existing behavior:

**When** I run `pack inspect-image` (without `--bom`)
**Then** I should not see the BOM displayed

**When** I run `pack inspect-image --bom`
**Then** I see the BOM output in json format

### Describe alternatives you've considered
Do nothing. It's fine as it is.

Output the data in a table (this would be very difficult because the data schema is undefined).

### Additional context
* This is to address the pain point described in this issue: https://github.com/buildpacks/pack/issues/378
* The implementation should follow the pattern in this issue: https://github.com/buildpacks/pack/issues/387
* We should announce that `pack inspect-image --bom` is deprecating and will be going away. 
* Create a separate issue for removing `--bom` later.

**Comment by kvedurmu** [comment]
@natalieparellano I wonder if this could instead be a global flag and/or environment variable. This is a fairly common pattern in another CLIs and I could see this flag being valuable in other pack commands (esp. for users automating on top of pack commands)
