### ISSUE TITLE
Allow caching all layers in the remote registry

### ISSUE THREAD

**Issue by burdiyan** [buildpacks/pack#491]
### Description

I probably wrongly was assuming that layers with `cache = true` in their `<layer>.toml` will be cached in the remote registry, in addition to local volume cache. This way rebuilds with empty local cache could be faster by reusing layers from the registry. Looks like currently it's not the case, and with empty local cache all layers are rebuilt from scratch.

### Proposed solution

AFAIK, kaniko is doing exactly that. It's pushing each layer to the registry tagging each layer with its hash. The before building it locally, if the inputs are the same the layer is fetched from the registry instead of rebuilding.

### Additional context

The reason for this is to be able to run CI jobs with ephemeral Docker daemons. If CI is close to the registry, retrieving cached layers from the registry is probably faster than rebuilding them. Maybe it could even be avoided by checking the layers metadata.

I guess this must be implemented in the lifecycle instead of directly in `pack`, or maybe in both. I originally submitted the request to the lifecycle repo but it got no attention so far: https://github.com/buildpacks/lifecycle/issues/245

**Comment by simonjjones** [comment]
After some research we discovered that this functionality is already available in lifecycle, and can be consumed by executing the `analyzer`, `exporter` & `restorer` phases with a `-cache-image` flag.

Historically, when we first implemented caching it was done entirely against a registry and we found this to be a lot less performant than using a volume, and therefore removed that option.

We would like to discuss the need for this feature in one of our upcoming working group meetings, which take place on Wednesday 8pm UTC and Thursday 7pm UTC. Please let us know if you would like an invite to come and represent the change.

Thanks,
Simon & @natalieparellano

**Comment by burdiyan** [comment]
@simonjjones Thanks for reaching out! Thanks for the call to participate in the group meeting, but I'm afraid I currently don't have bandwidth for that :( 

As for the feature itself, I think it could be super useful having an option for best-effort local volume caching, and remote caching as a fallback or something like that.

**Comment by jromero** [comment]
We've discussed this a bit in our stand-up and would like to proceed to make this an opt-in feature. The intention would be to leave existing behaviour but provide a `--cache-image` flag, similar to the `lifecycle`,  for the `build` command. This value would essentially be passed to the `lifecycle`.

@buildpacks/platform-maintainers please provide some feedback. 👍/ 🤔/ 👎

**Comment by burdiyan** [comment]
I like the opt-in nature of the feature. I think it's fair. Looking at how kaniko implements this kind of caching, I believe it wouldn't be possible to specify a single cache image for all the different layers that might be cached. Kaniko specifies cache destination as a repository (not image with a certain tag), and effectively each layer is a new image tagged by its digest.

**Comment by ekcasey** [comment]
@burdiyan

In a registry, layers blobs are always scoped to a repository. In this situation the lifecycle needs a manifest in addition to the layers themselves so that it can look up which layers to download. We can use labels in the config of a "cache image" to store metadata that allows us to locate and restore the correct layers.

Also, given that some registries will garbage collect orphaned blobs we need a manifest to keep cached layers from being gc'd. I don't know why generating a manifest per layer would be preferable to having a manifest per image cache.

**Comment by dfreilich** [comment]
It seems like there hasn't been much movement on this issue for quite a while. Any updates to add?

**Comment by jabrown85** [comment]
+1 to having this as an option for pack. It would be useful for sharing cache images between machines/users. It also makes debugging the cache easier in my opinion.

**Comment by genevieve** [comment]
+1 We would love this feature! We plan to use the pack circle ci orb and this would save a tremendous amount of time.

**Comment by genevieve** [comment]
Are there any plans to support this soon? We are using pack in CircleCI (but not the pack orb right now for different reasons) and are running it inside a docker image against a remote docker daemon which means we can't persist the pack cache as the orb does when it uses a machine executor. (The machine executor takes a lot longer to spin up, is more costly, etc.) When we use docker to build the image, buildkit has support for persisting the cache to registry and reusing it when needed.

**Comment by praveenperera** [comment]
With docker buildx you can cache to a local file:

`docker buildx build --cache-to=local,dest=cache_location,ref=user/app`

It would be amazing to do the same with pack

**Comment by jromero** [comment]
@dfreilich there seems to be a great desire to add this (and then some) as soon as possible. I know we have it scoped for the next release. We should make sure to not let it slip any further.
