### ISSUE TITLE
Preserving app file mtimes at build time

### ISSUE THREAD

**Issue by pclalv** [buildpacks/pack#492]
As of [lifecycle#80][lifecycle-80], the lifecycle ensures that all app
files have the same predetermined mtime at build time, regardless of
the app file's actual mtime. It would be nice to have an option to
preserve app file mtimes at buildtime in order to support build steps
that use mtime to validate the cache and/or its contents.

## Detailed use-case

I have a Rails app with a [Sprockets][sprockets] asset pipeline. In
order to build images for the Rails app we run several it through
several buildpacks, including a Ruby buildpack and a Sprockets asset
compilation buildpack.

The most basic Sprockets asset compilation buildpack essentially just
needs to compile static assets from source files and write those
compiled assets to a known place. It can compile every asset from
scratch every time and generate the correct results.

However, compiling every asset from scratch every time is not
efficient. We would like to enable our Sprockets buildpack to be able
to use a cache and thereby only compile assets that need to be
compiled. Sprockets is built with support for caching; as with GNU
make, a source file's mtime is the underlying mechanism for
determining whether a cached compiled asset is valid. Because every
source file has the same mtime on every build, a Sprockets buildpack
will compile an asset from a source file exactly once and never
compile it again, due to the source file mtime being the same every
every time.

[lifecycle-80]: https://github.com/buildpacks/lifecycle/pull/108
[sprockets]: https://github.com/rails/sprockets

**Comment by pclalv** [comment]
Ah yeah, my mistake. While we invoke the lifecycle directly in our remote builds, I usually test our buildpacks locally with pack, and I mistakenly assumed that lifecycle builds and pack builds would be equivalent in this regard. It would be nice to smooth out this difference, though.

**Comment by ameyer-pivotal** [comment]
Hi @pclalv, thanks for reporting this! We're in agreement with @ekcasey in that we should be able to preserve source file mod times during the build with no negative side effects (they will still get normalized before exporting the final image). This will resolve your issue and also #184.

**Comment by ameyer-pivotal** [comment]
Hi @pclalv, we've got PR #505 up for this. Feel free to take a look at that branch and try it out.
