### ISSUE TITLE
add exclude and include support in project.toml

### ISSUE THREAD

**Issue by elbandito** [buildpacks/pack#511]
### Description
Exclude and Include are not yet supported in `project.toml` for `pack build`.  Adding support for these features, moves us substantially closer to being feature complete with the Project Descriptor [RFC](https://github.com/buildpacks/rfcs/blob/master/text/0019-project-descriptor.md)

### Proposed solution
See [Exclude/Include](https://github.com/buildpacks/rfcs/blob/master/text/0019-project-descriptor.md#buildinclude-and-buildexclude) in RFC.  This particular issue will address adding support in the `pack build` command.  A separate issue will address support for `pack package-buildpack`.

### Describe alternatives you've considered
N/A

### Additional context
Nothing for now.

**Comment by jromero** [comment]
Resolved by #549
