### ISSUE TITLE
building jar gives a `project.toml` related error message

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#512]
### Summary
`pack build -p <path-to-jar>` causes ugly error message

---

##### Steps

1. pack build <image> --builder cloudfoundry/cnb:bionic -p <path/to/jar>

##### Current behavior
logs include the following error message
```
open <path/to/jar>/project.toml: not a directorybionic: Pulling from cloudfoundry/cnb
...
```

##### Expected behavior
1. No error message
1. A new line between any error and the next log line

---

##### pack info
Built from git sha 7a9ec45b94412d24577ee3a7b6826f2cbfe6b42d (head of `master` at time of writing)
```
$pack report
Pack:
  Version:  dev-2020-02-26-10:24:29
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.6.1
```

**Comment by jromero** [comment]
![image](https://user-images.githubusercontent.com/475559/75363596-f6078400-587f-11ea-8de9-98d5d9a53002.png)
