### ISSUE TITLE
Pack build --no-pull fails —publish fails without indicating how to fix

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#516]
### Summary

I was trying to build some images without internet. Having previously run builds, I assumed that cached images on my local machine would be sufficient. Does not seem like that's the case.

---

##### Steps

```bash
± zm |master U:1 ?:1 ✗| → pack build -p knote-js/01/ zmackie/knote:1.0.0 --publish --no-pull --builder cloudfoundry/cnb:bionic
ERROR: invalid run-image 'cloudfoundry/run:base-cnb': connect to repo store 'cloudfoundry/run:base-cnb': Get https://index.docker.io/v2/: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:53810->[::1]:53: read: connection refused
```

##### Current behavior

Offline build failed in looking for the base stack image.

##### Expected behavior

Cached local resources would allow the build to succeed. 

---

##### pack info

```bash
± zm |mirror-tty → zmackie ✓| → pack report
Pack:
  Version:  v0.8.1 (git sha: e776ebf0096363bbac60771a456af941827316be)
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.6.1

Config:
  default-builder-image = "some/image"
```
##### docker info

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 37
  Running: 19
  Paused: 0
  Stopped: 18
 Images: 92
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: RE3S:ZAXT:2B6G:PIR3:E7Z5:QOUZ:3B6M:UAKR:WZAX:AB2Q:I22O:GMMP
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 138
  Goroutines: 130
  System Time: 2020-03-01T16:18:54.8226788Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

**Comment by jromero** [comment]
The problem happens to be that you are using `--publish` which uses remote images and furthermore makes `--no-pull` a no-op operation. Generally speaking, `--publish` doesn't make sense in a case where network is unavailable.

For a clearer picture on how the semantics work, see the story for [packages](https://github.com/buildpacks/pack/issues/392).

If there is an outcome of this it should be that we should error or display a warning when `--publish` and `--no-pull` are used together.

**Comment by zmackie** [comment]
First off : facepalm. I somehow missed the publish flag in there. 
That being said, I think we should reopen this issue because of the reasons you stated: the flag combo i used is invalid Or maybe not exactly invalid but doesn’t really make sense. I know that, but I’m not sure it would be generally understood by a user that this it’s the a sensical state. Maybe could have better error messaging that indicates to the user what they could do to fix the issue? Happy to Edit the title and reopen or file a new issue.

**Comment by jromero** [comment]
Fair enough. I vote a new issue since this issue still provides a good historical reference.
