### ISSUE TITLE
Allow `docker list` to show actual conatiner build time/date

### ISSUE THREAD

**Issue by mikegehard** [buildpacks/pack#517]
### Description

When teaching folks new to buildpacks how they interact with Docker, it is nice to have them look at their images before and after they use `pack` to build the image.

When they look after using `pack` it can be confusing to find the image that just got built because they can't look for a timestamp that happened recently because the newly built image says `40 years ago`.

### Proposed solution

Add a command line switch to allow the generated image to have to proper timestamp. Without this switch, the timestamp would be `40 years ago`.

**Comment by jromero** [comment]
This seems to be related to https://github.com/buildpacks/rfcs/pull/50. If that's correct and have some input please feel free to add your feedback to the RFC.

**Comment by mikegehard** [comment]
Yep...added a +1 for docs there. Feel free to close this issue.

**Comment by jromero** [comment]
Thank you for understanding. We'll continue to strive to get that answered via the RFC.
