### ISSUE TITLE
use `/cnb/lifecycle/creator` to improve performance

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#523]
### Description
Given a builder with platform API >= 0.3. `pack build` should execute the lifecycle in a single container to improve performance

### Proposed solution
When Platform API >= 0.3 `pack` should execute `/cnb/lifecycle/creator` rather than executing each phase individually.

### Additional context
RFC: https://github.com/buildpacks/rfcs/blob/master/text/0026-lifecycle-all.md
Lifecycle PR: buildpacks/lifecycle#243

NOTE: Should only apply when `--trust-builder` flag is provided. Further acceptance to be done in #566 to verify that `creator` is used when a builder is statefully trusted with `pack trust-builder`.

**Comment by jromero** [comment]
👍 This would simplify our build process significantly.

https://github.com/buildpacks/pack/blob/master/internal/build/build.go#L67-L111

**Comment by ameyer-pivotal** [comment]
Blocked currently by PR #532

**Comment by yaelharel** [comment]
Hi, I'm going to start looking at this issue.

**Comment by yaelharel** [comment]
This issues depends on issue #566 and on introducing a new flag: `--trust-builder`.
Since I'm working on it while #566 is still open, I think that we need to create the `--trust-builder` flag and move the A/Cs that relate to the `pack trust-builder` command to be part of #566.

**Comment by natalieparellano** [comment]
Thanks @yaelharel for the clarification. I updated the description here and in #566 to reflect the updated A/C.

**Comment by ekcasey** [comment]
@yaelharel @natalieparellano I think this issue has interactions with trusted builders but could be implemented independently. Right now all builders are trusted. We wouldn't be making matters worse by migrating all builds to `creator`. The interactions only come in once we make a distinction between untrusted/trusted builders. If trust/untrust lands first, `creator` should only apply used w/ trusted builders. If this lands first, that the trusted builder feature would be responsible for returning to container phases when a builder is untrusted.

**Comment by yaelharel** [comment]
Discussion about performance testing can be found in the following slack thread:
https://buildpacks.slack.com/archives/CD61YAG69/p1588004835159100
