### ISSUE TITLE
pack should run `analyze`, `restore`, and `export` in an ephemeral image

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#528]
# Description
Implement [RFC 25](https://github.com/buildpacks/rfcs/blob/master/text/0025-dont-trust-builders.md)

This should be blocked on https://github.com/buildpacks/pack/issues/566.

# Motivation

Users of `pack` must select a builder image during `pack build`. The builder image is currently used to create all lifecycle phase containers.

When `pack build` is run with the `--publish` flag, the user's registry credentials are injected into the `analyze` and `export` containers as environment variables.
This means that users must place a high level of trust in their selected builder image.

Users may not realize that credentials are given to builder images and experiment with builders from untrusted vendors.

# What it is

**AC 1** `pack build my-app --publish -B untrusted-builder`

When `pack build` executes and is provided the `--publish` flag, it will generate an ephemeral "lifecycle image" on the fly, by adding a single layer container the correct lifecycle to a scratch image. `pack` will then use this image to created the `analyze`, `restore`, and `export` containers. `pack` will clean up the image when the build completes.

When generating lifecycle images `pack` will read the lifecycle version from the builder metadata and fetch the matching lifecycle version from the lifecycle github release assets.

If the lifecycle version specified in a builder image does not match any known lifecycle release, `pack build` will fail with a helpful message.

**AC 4** `pack build my-app --publish -B some-builder --trust-builder`

All lifecycle steps will be run in a single container built from the user-provided builder. (This assumes https://github.com/buildpacks/pack/issues/523 has been completed.)

The registry credentials will be provided only to `analyzer` and `exporter` processes.

**AC 5** `pack build my-app -B untrusted-builder` (no `--publish`)

When `pack build` is run without the `--publish` flag, registry credentials are not necessary.
Therefore, `pack` will treat every builder as a "trusted builder".

All lifecycle steps will be run in a single container built from the user-provided builder. (This assumes https://github.com/buildpacks/pack/issues/523 has been completed.)

###

These AC (originally in this issue) should be moved to the next issue:

**AC 2** `pack trust-builder <build-image>`

Users can run `pack trust-builder <build-image>` to permanently trust a builder.

**AC 3** `pack build my-app --publish -B trusted-builder`

All lifecycle steps will be run in a single container built from the user-provided builder. (This assumes https://github.com/buildpacks/pack/issues/523 has been completed.)

The registry credentials will be provided only to `analyzer` and `exporter` processes.

**Comment by yaelharel** [comment]
Part of the A/Cs depend on issue #566.
If we would like to work on this issue before issue #566, I think that we need to change the A/Cs to use only the `--trust-builder` flag (will be probably introduced in #523) and move the A/Cs that relate to the `pack trust-builder` command to be part of #566.

**Comment by natalieparellano** [comment]
Some spike code on this branch: https://github.com/buildpacks/pack/compare/11e3a67..feature/528-ephemeral-lifecycle-image

This code creates a lifecycle image with the following, and uses this image to run the `analyzer` and `exporter` phases. The acceptance tests are passing.

* A lifecycle layer containing the lifecycle binaries downloaded from GitHub
* A layer containing `stack.toml`
* A layer creating the `/tmp` directory
* The working directory is set to `/layers`

Thoughts & questions:
* Why does `restorer` need to run inside the lifecycle image given that it doesn't receive the `--publish` flag?
* Why does running `restorer` inside the lifecycle image cause `build` to fail with the following error: `[builder] ERROR: failed to build: mkdir /layers/simple_layers: permission denied`
* How to best refactor the code in internal/builder/builder.go to re-use the functions used in making the lifecycle image

**Comment by natalieparellano** [comment]
This is blocked on https://github.com/buildpacks/lifecycle/issues/285
