### ISSUE TITLE
Flake: auth registry unit test

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#533]
### Summary
[This test](https://github.com/buildpacks/pack/blob/007ab0cb7d61d8c999efee282c82953b56bb5b80/internal/build/phase_test.go#L290-L300) fails some of the time, but not all of the time. Let's understand why and fix it.

It fails because it can't find the `packs/build:v3alpha2` image ("manifest unknown").

---

### Reproduction
run `make unit` ??? times to see the failure

**Comment by jromero** [comment]
It appears that this is happening more frequently. :/
