### ISSUE TITLE
Lifecycle should rely on a builder interface

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#541]
### Description
As in here: https://github.com/buildpacks/pack/blob/007ab0cb7d61d8c999efee282c82953b56bb5b80/internal/build/build.go#L25

It's frustrating that we have to `docker build` an image in our tests in order to be able to call things like `lifecycle.builder.Name()`.

### Proposed solution
Lifecycle should rely on a builder interface. Should make our tests faster and easier to write.

### Describe alternatives you've considered
Do nothing.

**Comment by jromero** [comment]
Not sure I follow the connection between a `docker` binary execution and the underlying implementation. Could you elaborate? What does `docker build` have to do with whether the `lifecycle` uses a concrete object or interface?

**Comment by natalieparellano** [comment]
This was closed in #560
