### ISSUE TITLE
Use exporter -run-image flag instead of -image (platform API 0.3+)

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#548]
### Description
When platform API >=0.3 use the `-run-image` flag on the `exporter` instead of the deprecated `-image` flag.

### Additional context
> which image?

For clarity, `-image` has been deprecated in favor of `-run-image` on the `exporter` as of Platform API 0.3
- https://github.com/buildpacks/lifecycle/releases/tag/v0.7.0

**Comment by jromero** [comment]
Resolved by #560
