### ISSUE TITLE
Can pack `suggest-builders` point to Paketo builders instead of Cloudfoundry?

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/pack#551]
### Description
`pack suggest-builders` currently points to the Cloud Foundry bionic, cflinuxfs3, and tiny builders. Could we get this command updated to point to the Paketo builders? Going forward, Paketo builders will be officially supported and we're planning on deprecating the Cloud Foundry Builders fairly soon.

### Proposed solution
`pack suggest-builders` suggests the bionic, cflinuxfs3, and tiny Paketo builders. 
The Paketo Builder docker registry paths are as follows:
```
gcr.io/paketo-buildpacks/builder:bionic
gcr.io/paketo-buildpacks/builder:tiny
gcr.io/paketo-buildpacks/builder:cflinuxfs3
```

### Describe alternatives you've considered
None

### Additional context
None

**Comment by jromero** [comment]
Thanks for the notice @kvedurmu. Should we include `suggest-stacks` here? Do we know their stack ID?

**Comment by kvedurmu** [comment]
Oh I didn't even realize there's a `suggest-stacks` command 😄 . Yeah, we will need to make this update for stacks at some point, but I think that we should wait on this for now. Reason being, we're planning on adding mixins in pretty soon so that we can replace cflinuxfs3 with the bionic stack + mixins. In the interim, stack wise, we'll be publishing build/run stack images to the following paths:

Base: `paketobuildpacks/[build/run]:base-cnb`
Tiny: `paketobuildpacks/[build/run]:tiny-cnb`
**Full**: `paketobuildpacks/[build/run]:full-cnb-cf`

Note that we're publishing **full** to a temporary path to avoid breaking stuff when we add mixin support. Once that's added the path for the Full stack becomes `paketobuildpacks/[build/run]:full-cnb` and we can get this command updated!

cc: @martys34 @sclevine

**Comment by jromero** [comment]
@kvedurmu created https://github.com/buildpacks/pack/issues/552 so we can do that work separately and continue discussing it.
