### ISSUE TITLE
Could suggest-builders indicate that there are Paketo Builders for n-2 Platform API Versions?

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/pack#553]
### Description
The bionic, tiny, and cflinuxfs3 Paketo/Cloud Foundry builders are now maintained for the latest, n-1, and n-2 platform API versions. It would be great if there could be some UX for pack users to see that this is supported.

Here are the paths for the bionic builder:
```
gcr.io/paketo-buildpacks/builder:bionic
gcr.io/paketo-buildpacks/builder:bionic-platform-api-latest
gcr.io/paketo-buildpacks/builder:bionic-platform-api-n-1
gcr.io/paketo-buildpacks/builder:bionic-platform-api-n-2
```

We also support passing an explicit platform API version, but note that only the 3 latest versions will be maintained. eg.
```
gcr.io/paketo-buildpacks/builder:bionic-platform-api-0.2
```

### Proposed solution
The `pack suggest-builders` command exposes all of the Paketo builder paths. Perhaps a cheap way to do this is by updating the builder description?

### Describe alternatives you've considered
None

### Additional context
None

**Comment by jromero** [comment]
Jotting down some initial thoughts:

Because `latest` and `n-X` is a moving target, `pack` would probably use more explicit versions when suggesting builders.

In addition, it should only suggest versions that are supports or at least mark them as incompatible.

It would be nice to serve that data used to suggest builders and stacks. `pack` can then fetch and dynamically filter the suggested builders based on any given criteria. For example:

**Comment by zmackie** [comment]
@kvedurmu Is this still something you're interested in? 

I'm concerned that the UX of this is a bit confusing; `suggest-builders` is sort of oriented to newer users (people who don't really have a sense of the builders they want) and this feature would expose details about platform api that are confusing ("what is this platform api and why do I care about it I just want to build my app?").

I personally think that having the builder description and homepage discuss support policies is much better (also considering that not every builder will have multiple lines of support)

**Comment by kvedurmu** [comment]
@zmackie I'm fine dropping this. Totally agree that the UX for this is going to be pretty tricky. Is there a concept of `Homepage` for builders yet? If we had that, we could just link out to our builders repo (which explains this pretty well).

**Comment by natalieparellano** [comment]
I believe homepage is only a thing for buildpacks (vs. builders). Perhaps this information could be added to the description?

**Comment by kvedurmu** [comment]
This seems reasonable. We could add it into description for now. Closing this.
