### ISSUE TITLE
Upgrade to go1.14

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/pack#554]
### Summary

Pack is currently using go1.13 as specified [here](https://github.com/buildpacks/pack/blob/30cb3dca7c746d1b21c00dc550f5b8219d3a7b9f/go.mod#L42).
We would like to upgrade go to its latest version and to fix any potential errors.

##### Current behavior

Contributors need to install go1.13 in order to compile pack.

##### Expected behavior

Contributors will be able to compile pack with go1.14.

**Comment by dgageot** [comment]
I'm happy to take a shot at it if nobody's working on it already
