### ISSUE TITLE
add exclude and include support for package-buildpack

### ISSUE THREAD

**Issue by elbandito** [buildpacks/pack#558]
Description
According to the [Project Descriptor RFC](https://github.com/buildpacks/rfcs/blob/master/text/0019-project-descriptor.md#buildinclude-and-buildexclude) `Exclude` and `Include` should be supported for `pack package-buildpack`. 

Proposed solution
See Exclude/Include in [RFC](https://github.com/buildpacks/rfcs/blob/master/text/0019-project-descriptor.md#buildinclude-and-buildexclude). This particular issue will address adding support in the `pack package-buildpack` command.

Describe alternatives you've considered
N/A

Additional context
Nothing for now.

**Comment by jromero** [comment]
@elbandito I see you are still assigned to this issue. Is that still accurate?

**Comment by ekcasey** [comment]
@elbandito you are right that the RFC says this should apply to `pack package-buildpack` but this confuses me. The project descriptor describes an app not a buildpack.

If your buildpack uri in `pojrect.toml` was a path to a directory or something like that it would make sense to include/exclude the buildpack files when adding the buildpack dynamically during `pack build`, but I don't know that it makes sense for `package-buildpack` which currently doesn't accept `project.toml` at all?

**Comment by jromero** [comment]
This certainly requires clarity. As of right now a `project.toml` doesn't apply to [`pack buildpack package`](https://buildpacks.io/docs/tools/pack/cli/pack_buildpack_package/). This new config `include` and `exclude` should be discussed in context of `buildpack.toml` or `package.toml`. It may be the case that the RFC is so out of sync with the eventual reality that it no longer applies directly.

**Comment by dwillist** [comment]
@elbandito any further context on this? Seems like we might want to amend the RFC to clarify this point.

**Comment by dwillist** [comment]
@elbandito Closing this, feel free to re-open.
