### ISSUE TITLE
Need env var for current buildpack and version

### ISSUE THREAD

**Issue by dsyer** [buildpacks/pack#56]
My buildpack scripts keep having to refer to their own id and version. E.g. to construct a `launch.toml` I need to refer to a launch layer:

```
cat > $launch/launch.toml <<EOF
[[processes]]
type = "web"
command = "/workspace/${BUILD_PACK_ID}/native/demo"
EOF
```

or to get a reference to a cache entry I need `/buildpacks/${BUILD_PACK_ID}/${BUILD_PACK_VERSION}`. Those env vars are not available so I have to hard code their values, even though the builder knows their values from `builder.toml`.

**Comment by nebhale** [comment]
Regardless of its implementation today, the spec does not guarantee that the buildpack will be available at runtime of the application.  The only thing guaranteed to be available are the launch layers, and the app layer (which you can view as a specially named launch layer).  Therefore, your creation of the `demo` binary in your buildpack is incorrect and you should not refer to it at that location.  Instead, you need to create that binary in a launch layer, referring to it there.  This would negate the need for a reference to the buildpack's ID and version.

**Comment by sclevine** [comment]
The `/bin/build` executable is provided with `/workspace/${BUILDPACK_ID}` and `/cache/${BUILDPACK_ID}` directly, via the second and third args: https://github.com/buildpack/spec/blob/master/buildpack.md#build

**Comment by nebhale** [comment]
The invocation of `/bin/build` takes [three arguments and the working directory](https://github.com/buildpack/spec/blob/master/buildpack.md#build) as well-known locations.  Specifically `$3` is the pointer to the root of the `launch` directories.  You are then responsible for creating "layers" (e.g. subdirectories) under that location.

**Comment by dsyer** [comment]
I didn't know that  those "well known locations" were identical at runtime. If it's there in the spec, all I can say is it didn't jump out at me. I can't see anywhere in the spec where it talks about the layout of the filesystem at runtime (in the "launch" phase). Examples are good for this kind of thing.

**Comment by dgodd** [comment]
@dsyer you generally don't need to know the location of the buildpack layer directory locations at run time since subdirectories `bin` and `lib` will respectfully be in environment `PATH` and `LD_LIBRARY_PATH`. Maybe if you post a link to your repo I could make a PR with some suggestions?

**Comment by sclevine** [comment]
> I didn't know that those "well known locations" were identical at runtime. If it's there in the spec, all I can say is it didn't jump out at me. I can't see anywhere in the spec where it talks about the layout of the filesystem at runtime (in the "launch" phase).

Definitely agree this should be described in less formal documentation. If you're curious, it's [covered in the Export section](https://github.com/buildpack/spec/blob/master/buildpack.md#phase-4-export).

> Examples are good for this kind of thing.

If you haven't seen them yet, we do have some [sample buildpacks](https://github.com/buildpack/samples) that were made to help buildpack authors understand the spec.

> I don't think that changes the request (it was only one example). The other one is unpacking a tar ball from the buildpack into the cache.

This is definitely an improvement worth considering. Current (v2a/b) buildpacks use something [like this](https://github.com/cloudfoundry/ruby-buildpack/blob/master/bin/compile#L6) to make that determination, and I don't think we've discussed improving that interface for the v3 spec.

> I can cheat I suppose to parse it from the launch location, now I know that it is always /workspace/${BUILD_PACK_ID}.

Buildpacks definitely shouldn't make assumptions about the directory paths they are passed.

> I don't have a trick for the version though as far as I know. 

Buildpacks generally include their version in a `VERSION` file at the root, but I agree that it should be easier to access.

@nebhale @hone @jkutner Any thoughts on introducing these env vars for `/bin/build`, `/bin/develop`, and `/bin/detect`?

1. `BUILDPACK_DIR`
2. `BUILDPACK_ID`
3. `BUILDPACK_VERSION`

**Comment by dsyer** [comment]
@dgodd this is the `PATH` from by `build`:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/cache/org.cloudfoundry.openjdk/openjdk-jdk/bin
```

So I can see Ben's `bin` dir but nothing from my buildpack. I didn't create a `bin` directory, so maybe I should? In the spec it mentions briefly:

> `<cache>/<layer>/bin/`	Binaries for subsequent buildpacks

but there's no real indication of what that means. I guess I could interpret it as "if you build it they will come". Wish me luck.

I haven't put my builder in github yet (waiting for https://github.com/buildpack/pack/pull/55 - as soon as there is a release with that included I can share more easily).

**Comment by dsyer** [comment]
@sclevine the samples are great, and very useful, but lacking any documentation, so there's no way to figure out why they are doing what they do, or how it works.

**Comment by sclevine** [comment]
> there's no real indication of what that means. I guess I could interpret it as "if you build it they will come"

There are more details on this in the [Environment](https://github.com/buildpack/spec/blob/master/buildpack.md#environment) section.

**Comment by sclevine** [comment]
@ekcasey and @dgodd point out that the ID and version are already available in buildpack.toml, so it may be sufficient to just expose `BUILDPACK_DIR`.

Also, we should consider unsetting `PACK_*` environment variables that aren't intended for the buildpacks. (Everything but `PACK_STACK_ID`.)

**Comment by nebhale** [comment]
I still don't see the requirement for something like `BUILDPACK_DIR` even.  You know where your binary is (`$0`) and can work it out from there (`"$(dirname $0)/.."`).  `<cache>` `<launch>` and `<platform>` are all passed in, and `<app>` is the working directory.  Given those, you are expected to create sub folders as necessary to contribute to.  I still believe that the values of those things should be opaque and their structure doesn't need to be exposed to buildpack authors.

The fact that `bin/`, `lib/`, et. al. aren't obvious in the spec should be solved by better documentation, not violating the opaque-ness of the input parameters.

**Comment by sclevine** [comment]
The lifecycle can (and happens to already) guarantee that `"$(dirname $0)/.."` is reliable, but outside of this particular context, it's usually not safe to assume that it works. I'm conflicted, but I'm okay with specifying it as reliable for now.

**Comment by dsyer** [comment]
I'm using this now in case anyone else wants it:

```
build_pack_dir=`dirname $(readlink -f ${BASH_SOURCE%/*})`
```

but I really think it should be provided by the lifecycle. Even if it isn't we need some documentation that shows why you need it - it took me over a week to work out that this directory actually contained all of the stuff that I put in the buildpack, and that the version and id were available in `buildpack.toml` in that directory.

**Comment by sclevine** [comment]
Sorry for the long turnaround here. The requested env vars will be added to the environment as part of the next (potentially final) large set of breaking API changes:

Implementation: https://github.com/buildpack/lifecycle/pull/149
Spec: https://github.com/buildpack/spec/pull/53/files#diff-7f205a69e3c8a81e4eee0a39e84a9311R650

(These changes also address feedback on distributing buildpacks and the complexity of the current build plan model.)

**Comment by Zanadar** [comment]
@sclevine I think we can close this?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
