### ISSUE TITLE
New command: pack trust-builder

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#566]
### Description
This is in support of [RFC 25](https://github.com/buildpacks/rfcs/blob/master/text/0025-dont-trust-builders.md) which introduces the concept of trusted builders.

We need a way to tell pack that a builder should be trusted, so that the user does not need to supply `--trust-builder` for every build.

### Proposed solution
**AC 1a**
When I run `pack trust-builder some-build-image`
And I `cat ~/.pack/config.toml`
Then I should see a section in the output corresponding to trusted builders
And I should see that `some-build-image` is there

**AC 1b**
When I run `pack trust-builder some-build-image`
And I run `pack build -B some-build-image --publish`
Then I should see in the logs that the `creator` binary was used

**AC 2** (default builders should be auto-trusted)
When I run `pack build -B cloudfoundry/cnb:bionic --publish`(or any of the suggested builders)
Then I should see in the logs that the `creator` binary was used

### Questions
Do we need to provide a way to un-trust builders?

**Comment by jromero** [comment]
`AC #2`  doesn't look accurate unless we add a section specific for `trusted builders` that goes beyond printing the config. Maybe it's more appropriate for #567.

**Comment by natalieparellano** [comment]
I guess phrased another way - is it correct that the builders from `pack suggest-builders` should be auto-trusted (regardless of how this information is presented to the user)?

**Comment by yaelharel** [comment]
This issue relates to issues #523 and #528.
If this issue will be implemented after the others, I think that its A/C should include also running the other A/Cs after using the `pack trust-builder` command instead of the `--trust-builder` flag.

**Comment by natalieparellano** [comment]
This should be blocked on #523.

**Comment by ekcasey** [comment]
@natalieparellano whether or not we use `creator`, all builders are currently trusted. We need to create ephemeral images that contain only the trusted lifecycle as described in (https://github.com/buildpacks/rfcs/blob/master/text/0025-dont-trust-builders.md) to introduce the concept of a trusted builder. I think we need to capture that in the ACs.

**Comment by jromero** [comment]
_blocked by: https://github.com/buildpacks/pack/issues/528_

**Comment by natalieparellano** [comment]
Updated the AC to reflect the fact that `list-trusted-builders` functionality will be completed separately.
