### ISSUE TITLE
pack should provide an easy way to list trusted builders

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#567]
### Description

We should provide an easy way to see which builders are currently trusted. #566 assumes that we can do this with `pack report`, but maybe there is a better way.

### Proposed solution
AC 1
When I run `pack list-trusted-builders`
Then I should see the default builders (from `pack suggest-builders`)

AC 2
When I run `pack trust-builder <some-builder>`
And I run `pack list-trusted-builders`
Then I should see `<some-builder>` in the output

**Comment by jromero** [comment]
_blocked by: https://github.com/buildpacks/pack/issues/528_

**Comment by jromero** [comment]
Let's break this into 3 issues. Maybe only two as `pack builder list` not a thing yet.
