### ISSUE TITLE
GHA workflow to test pack master against lifecycle master

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#568]
### Description
Once #565 is complete, we won't have any automated tests of pack master against lifecycle master.

### Proposed solution
We should test master to master, but not against PRs. This configuration should only run on pushes to pack master.

**Comment by natalieparellano** [comment]
Rationale for why we don't want master to master on PRs is outlined here: https://github.com/buildpacks/pack/issues/524#issuecomment-605027891

**Comment by natalieparellano** [comment]
Consider: whether this should be in pack or lifecycle.

**Comment by jromero** [comment]
The risk is minimal and lifecycle maintainers already run acceptance test on pack using a prerelease version of lifecycle.

**Comment by dfreilich** [comment]
Automating this on lifecycle's end is blocked on https://github.com/buildpacks/pack/issues/904, which is prioritized in this milestone.
