### ISSUE TITLE
Support .cnb files in package-buildpack package.toml

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#586]
### Description
Add support for .cnb files in package.toml files for the command `pack package-buildpack`.

### Proposed solution
Most of this work would have already been as part of https://github.com/buildpacks/pack/issues/472. We should just need to evaluate what type of file it is.

#### Example usage

... with minor changes to [samples](https://github.com/buildpacks/samples):

```shell
$ pack package-buildpack hello-world.cnb --format file -p packages/hello-world/package.toml
Successfully created package hello-world.cnb

$ cat packages/hello-universe/package.toml
[buildpack]
uri = "../../buildpacks/hello-universe/"

[[dependencies]]
uri = "../../buildpacks/hello-moon"

[[dependencies]]
uri = "../../hello-world.cnb"

$ pack package-buildpack hello-universe.cnb --format file -p packages/hello-universe/package.toml
Successfully created package hello-universe.cnb
```

### Additional context
- [x] This feature should be documented somewhere

**Comment by dfreilich** [comment]
This story doesn't include supporting the `[buildpack]` being a `.cnb` file as well, does it? It is only the dependencies?

**Comment by jromero** [comment]
I'm trying to understand why you would do that... 🤔 

A `.cnb` file should contain all it's dependencies already.

**Comment by dfreilich** [comment]
That's fair, I wasn't thinking - I only noticed that we explicitly handle both images and uris for the dependencies, and thought we should do the same for the buildpack 🤦
