### ISSUE TITLE
Support .cnb files in create-builder

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#587]
### Description
Add support for .cnb files in builder.toml files for the command `pack create-builder`.

### Proposed solution
Most of this work would have already been as part of https://github.com/buildpacks/pack/issues/472. We should just need to evaluate what type of file it is.

#### Example usage

... with minor changes to [samples](https://github.com/buildpacks/samples):

```shell
$ pack package-buildpack hello-world.cnb --format file -p packages/hello-world/package.toml
Successfully created package hello-world.cnb

$ cat builders/alpine/builder.toml
# Buildpacks to include in builder
[[buildpacks]]
uri = "../../hello-world.cnb"

# Order used for detection
[[order]]
[[order.group]]
id = "io.buildpacks.samples.hello-world"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.alpine"
run-image = "cnbs/sample-stack-run:alpine"
build-image = "cnbs/sample-stack-build:alpine"

$ pack create-builder hello-builder --builder-config builders/alpine/builder.toml
...
Successfully created builder image hello-builder
```

### Additional context
- [x] This feature should be documented somewhere

**Comment by zmackie** [comment]
@dfreilich

**Comment by dfreilich** [comment]
@jromero Can we assume that a valid file must end in `.cnb`?

**Comment by dfreilich** [comment]
If so, then we should probably enforce that, by making any file we create (using `pack package-buildpack ... -f file`) end in `.cnb`, even if that wasn't provided by the user

**Comment by jromero** [comment]
> @jromero Can we assume that a valid file must end in `.cnb`?

It wouldn't be ideal to depend on extensions and therefore enforce extensions. (What is this Windows? :D). A packaged buildpack in file format is valid if it has the contents in OCI layout format and contains the appropriate labels therein.

**Comment by jromero** [comment]
> If so, then we should probably enforce that, by making any file we create (using `pack package-buildpack ... -f file`) end in `.cnb`, even if that wasn't provided by the user

This conversation has some additional context. Might be worth opening a separate issue:

https://buildpacks.slack.com/archives/CJ6B92ZSB/p1586961828112700?thread_ts=1586959710.111700&cid=CJ6B92ZSB

**Comment by dfreilich** [comment]
Interesting. I'll open another issue then! 

I certainly hear that. If we looked at extensions, it would make it easier to do this solution as part of the `Packages()` func [here](https://github.com/buildpacks/pack/blob/master/builder/config_reader.go#L20-L28), which is why I asked
