### ISSUE TITLE
Unvendor Pack

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#601]
> Q: Should we use automation to update the vendor dir in the future? Is there typically?

1. imgutil and lifecycle have moved to "un-vendored".
2. imgutil has started using dependabot ([see PRs](https://github.com/buildpacks/imgutil/issues?q=label%3Adependencies+is%3Aclosed)).

Maybe we want to follow suit.

_Originally posted by @jromero in https://github.com/buildpacks/pack/pull/600#issuecomment-622344418_

**Comment by dfreilich** [comment]
We are unvendored, and are using dependabot, so I'd consider this one resolved. 💪
