### ISSUE TITLE
Completion for zsh

### ISSUE THREAD

**Issue by ukch** [buildpacks/pack#603]
### Description
Currently, the only shell-completion that exists is for bash. Attempting to run the bash completion in zsh returns the following error:
```
/path/to/.pack/completion:type:786: bad option: -t
```

This is using pack 0.10.0, installed from the GitHub release.

### Proposed solution
If possible, make a fully POSIX-compliant completion file, that works on sh, bash, zsh among others. If this is not possible, please make a zsh-specific completion file.

**Comment by dfreilich** [comment]
@ukch Under the hoods, `pack` uses [cobra](https://github.com/spf13/cobra) to generate the bash shell completion (see [here](https://github.com/buildpacks/pack/blob/master/internal/commands/completion.go#L34).). It seems that there is support for Zsh completion in cobra (https://github.com/spf13/cobra/pull/646), but no fully POSIX-compliant completion yet (https://github.com/spf13/cobra/pull/646#issuecomment-500821302).

**Comment by zmackie** [comment]
Breadcrumb: https://github.com/VilledeMontreal/cobra/blob/feat/zshCompletionV2/shell_completions.md

cobra is getting completion for bash, zsh, powershell, and fish
