### ISSUE TITLE
What do Windows-based buildpackages look like?

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#604]
### Description
On WCOW, what should `pack package-buildpack` yield?

### Considerations

- .cnb file
    - We use GGCR's oci-layout functionality to create an OCI image which has no OS/Arch attribution.
- image
    - There is no such thing as a "scratch" image for Windows
- Do we need to consider the potential of future registry/hive functionality?

**Comment by micahyoung** [comment]
The work so far on https://github.com/buildpacks/pack/pull/840 suggests that we'll want:

#### Linux buildpackage image
* The image's `os` [property](https://github.com/opencontainers/image-spec/blob/master/config.md#:~:text=os%20string) is `linux`
* Image buildpack layers are tar files with entry paths at `/cnb/buildpacks/...`

#### Windows buildpackage image
* The image's `os` property is `windows`
* Image buildpack layers are tar files with entry paths at `Files/cnb/buildpacks/...`
* Image shim base layer is a minimal set of layer files required to support pulling and storing buildpackages on a WCOW daemon using `pack` or `docker`

#### Linux buildpackage file
* The *Linux buildpackage image* packaged as as a standard `.cnb`

#### Windows buildpackage file
* The *Windows buildpackage image* packaged as a standard `.cnb`

### Image shim base layer
This PR https://github.com/buildpacks/imgutil/pull/64 describes it better, but there is a minimal layer we can generate and add to buildpackages to allow `docker pull` and `imgutil.FromBaseImage()`. This was created from based on `moby` and `hcsshim` codebases, and everything in the layer can be generated from scratch, using OSS tools, at runtime with `imgutil` on any OS.

**Comment by jromero** [comment]
@micahyoung if I'm not mistaken, this issue can be closed due to the implementation of [Windows Buildpackages](https://github.com/buildpacks/pack/pull/840).

Re-open if I'm missing something.
