### ISSUE TITLE
Acceptance tests could be clearer, easier to separate and simpler to add to

### ISSUE THREAD

**Issue by simonjjones** [buildpacks/pack#606]
### Description
The primary acceptance test file has grown to over 2000 lines and is proving hard to reason about, especially for people who are new to working with it. The tests are supported by a range of methods, state and service objects that are variously declared throughout the codebase and instantiated anywhere from the package level to individual tests.

### Proposed solution
I propose a refactor of the acceptance test suite to accommodate the scale it has grown to, in doing so I suggest the following principles:

- As much as reasonable, *prepare*, *act* and *assert* within the test body.
  - Avoid significant, scenario specific activities obscured in nested `Before` trees.
  - Each step can be abstracted by helper service methods, or stateless package methods. The methods should be very descriptively named.
- Use immutable service objects to pass around state, and state related test methods.
  - Consider the test object `*testing.T` to be state associated with these objects, rather than repeatedly pass to stateless methods.
  - Package (static) methods should ideally only be used when all of the inputs are outcomes of test preparation or action.
- Use service objects to encapsulate our dependencies, such as test stacks and buildpacks.
  - Include more contextual state about these dependencies without reusing our implementation.
  - Allow more flexibility around how these are generated.
- Declare shared state and service objects at the deepest level of test to be used by the tests that require them.
- Identify missing, or no longer required test cases

### Additional context
- Work out how to deliver this incrementally?

**Comment by dfreilich** [comment]
I think it's fair to say that this issue has been relatively resolved, with the epic based on #673.
