### ISSUE TITLE
Buildpack `from=all` sandwich not working 🥪

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpacks/pack#609]
### Summary
Supplying a custom buildpack via the `--buildpack` flag both before and after a `--buildpack from=all` only applies one of the provided buildpacks.

---

##### Steps
From the `bug` directory, after extracting [the attached zip](https://github.com/buildpacks/pack/files/4587619/bug.zip) (this directory contains two very simple buildpacks that always pass detection):

```
pack build myapp --builder cloudfoundry/cnb:bionic -p ~/workspace/samples/apps/java-maven/ --buildpack mybp --buildpack from=builder --buildpack mybp2
```

##### Current behavior
Detection only applies custom buildpack 0.0.1:
```
...
===> DETECTING
[detector] 7 of 16 buildpacks participating
[detector] custom.buildpack                    0.0.1
[detector] paketo-buildpacks/bellsoft-liberica 2.4.1
[detector] paketo-buildpacks/maven             1.2.1
[detector] paketo-buildpacks/executable-jar    1.2.2
[detector] paketo-buildpacks/apache-tomcat     1.1.2
[detector] paketo-buildpacks/dist-zip          1.2.2
[detector] paketo-buildpacks/spring-boot       1.5.2
===> ANALYZING
...
```

##### Expected behavior
Custom buildpack 0.0.1 should be applied before the builder's buildpacks, and custom buildpack 0.0.2 should be applied after:
```
...
===> DETECTING
[detector] 8 of 16 buildpacks participating
[detector] custom.buildpack                    0.0.1
[detector] paketo-buildpacks/bellsoft-liberica 2.4.1
[detector] paketo-buildpacks/maven             1.2.1
[detector] paketo-buildpacks/executable-jar    1.2.2
[detector] paketo-buildpacks/apache-tomcat     1.1.2
[detector] paketo-buildpacks/dist-zip          1.2.2
[detector] paketo-buildpacks/spring-boot       1.5.2
[detector] custom.buildpack                    0.0.2
===> ANALYZING
...
```

---

##### pack info
```
Pack:
  Version:  0.10.0+git-06d9983.build-259
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.7.2

Config:
  default-builder-image = "cloudfoundry/cnb:bionic"
```

**Comment by zmackie** [comment]
This is a result of the detection logic: https://github.com/buildpacks/lifecycle/blame/3b41bc40cc1eca7aeca47b4612b01f2d348a12d5/detector.go#L256-L258

Given two buildpacks of the same ID and different versions, at the moment only one will be considered for detection.

The buildpacks in your zip file have the same ID.

**Comment by ameyer-pivotal** [comment]
@zmackie 🤦I should have tried that. Thanks!
