### ISSUE TITLE
Don't pass default values explicitly to the lifecycle phases

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/pack#610]
### Description

Currently, we're passing the following flags with their default values to the lifecycle phases: `-layers`, `-platform` and `-app`. There is no reason to do so and it can be confusing to the reader.
We would like to stop passing these values explicitly.

### Proposed solution

Remove the flags `-layers`, `-platform` and `-app` from the calls to the following lifecycle phases: `detect`, `restore`, `analyze`, `build` and `export` (these flags weren't added to the `creator` call - see [this PR](https://github.com/buildpacks/pack/pull/595)).

### Additional context

The phases are located [here](https://github.com/buildpacks/pack/blob/master/internal/build/phases.go).
A description of the lifecycle (creator) flags can be found [here](https://github.com/buildpacks/rfcs/blob/master/text/0026-lifecycle-all.md#usage).

**Comment by jromero** [comment]
For reference:

* List of arguments and defaults: https://github.com/buildpacks/rfcs/blob/637dedeca0cbdc4dd587cc2ba723652dc70517cf/text/0026-lifecycle-all.md#usage
* Flags implementation: https://github.com/buildpacks/lifecycle/blob/master/cmd/flags.go#L11-L23

**Comment by Subhadeep2707** [comment]
Hi, I am working on this issue.
