### ISSUE TITLE
Append .cnb to package files created without file extensions

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#612]
### Description
Append `.cnb` to package files created using `pack package-buildpack <NAME> -f file`, when there is no extension provided.  

Otherwise, it is confusing on two respects: (1) users won't know what a `.cnb` file, and (2) users may think it's a `zip` file, when it's encoded differently. 

### Additional context
Discussed [here](https://buildpacks.slack.com/archives/CJ6B92ZSB/p1586961828112700?thread_ts=1586959710.111700&cid=CJ6B92ZSB) on the Buildpacks slack
Mentioned https://github.com/buildpacks/pack/issues/587#issuecomment-625468400 as well.

**Comment by dfreilich** [comment]
Potentially, we should enforce it as well. Should we overwrite other extensions/provide warnings if given `.tar` or `.zip`, for instance?

**Comment by jromero** [comment]
Love it!
