### ISSUE TITLE
Hijack feature: shell into a buildpack container to look at the state of things

### ISSUE THREAD

**Issue by dsyer** [buildpacks/pack#62]
One of the neatest features of concourse CI is the `fly hijack` command. It would be useful to copy that somehow in `pack` so that app developers can get better visibility into what happens inside the build containers. E.g. 

```
$ pack build my/app --hijack org.cloudfoundry.openjdk:build` 
workspace/app$ # poke around and check the state of the container
workspace/app$ ^D
... build continues
```

I get a shell entry point into the "build" phase container of the "org.cloudfoundry.openjdk" buildpack. As a developer I can poke around in there and make sure all the pieces of the app and the preceding buildpacks are in place and have their proper values. When I leave the shell the build continues.

**Comment by jromero** [comment]
I've started playing with this on my free time. There seem to be some limitations which make this more difficult than I initially thought. 

My initials thought was to provide pre/post interception per lifecycle phase. A simple flow would look like this per phase:

1. Pre-phase: run container while changing CMD to a shell (interception)
2. Phase: run container with CMD set to the lifecycle executable [as currently configured]
3. Pre-phase: run container while changing CMD to a shell (interception)

The problem with the above is that CMD is not overridable per container. Ultimately a new container must be created to change the CMD. 

Alternatively there is `exec`, the flow would look like:

1. Setup: Start a container with a hanging process to keep container running
2. Pre-phase: container exec with CMD to a shell (interception)
3. Phase: container exec with CMD set to the lifecycle executable
4. Post-phase: container exec with CMD to a shell (interception)
5. Teardown: Stop container

The problems with this approach are the following:

1. There is [no way to get the logs from `exec`](https://github.com/moby/moby/issues/8662) via the API.
    - There is a workaround to [pipe stdout to the file descriptor of the original process](https://github.com/moby/moby/issues/8662#issuecomment-277396232).
2. We would need a multi-os solution for a "hanging process".

Theoretically the "hanging" process could be a service that reads all other processes output and outputs it as its own. Essentially a logging aggregation service.

Is there anything I'm overlooking or just plain looking at wrong?

**Comment by jromero** [comment]
![image](https://user-images.githubusercontent.com/475559/72554701-d3d21d80-3860-11ea-860a-47f50cba0c94.png)

> https://buildpacks.slack.com/archives/C94UJCNV6/p1578673674011700

**Comment by natalieparellano** [comment]
### Acceptance Criteria

(a/c based on the Slack convo above)

As an app developer
When I run `pack build my-app-image --intercept`
Then for each phase of the lifecycle, I get an interactive shell with the following (or similar) output:
```
====> DETECT
Intercepting...
-----------
To continue to the next phase type: exit
To manually run the phase type:
/cnb/lifecycle/detector -app=/workspace/source -group=/layers/group.toml -group=/layers/group.toml ...
-----------
/layers $
```
And the command displayed is the command that would be executed on the lifecycle for that phase

When I type `exit` within the shell
Then `pack` proceeds to the next phase of the lifecycle

cc @jromero

**Comment by natalieparellano** [comment]
Closing now that we have `pack build --interactive`
