### ISSUE TITLE
builder.toml will not allow both image and uri buildpack locations in same definition

### ISSUE THREAD

**Issue by nebhale** [buildpacks/pack#623]
### Summary

Currently, when you attempt to create a builder with a `builder.toml` that contains both a buildpack with an `image` location and another buildpack with a `uri` location, the creation will fail and an incorrect error message will be reported.

---

##### Steps
1.  `pack create-builder` with the following configuration:

```
buildpacks = [
  { id = "paketo-buildpacks/bellsoft-liberica", image = "gcr.io/paketo-buildpacks/bellsoft-liberica" },
  { id = "paketo-buildpacks/node-engine",       uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.203/node-engine-v0.0.203.tgz" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/bellsoft-liberica" },
  { id = "paketo-buildpacks/node-engine" },
]

[stack]
id          = "io.buildpacks.stacks.bionic"
build-image = "gcr.io/paketo-buildpacks/build:base-cnb"
run-image   = "gcr.io/paketo-buildpacks/run:base-cnb"
```

##### Current behavior
```
$ pack create-builder builders/test --builder-config builders/test.toml
base-cnb: Pulling from paketo-buildpacks/build
Digest: sha256:663a1781cb60a3feb43b9a2a2eae6681ca0124509b47719b5a6bf770c7638712
Status: Image is up to date for gcr.io/paketo-buildpacks/build:base-cnb
ERROR: processing order: no versions of buildpack paketo-buildpacks/bellsoft-liberica were found on the builder
```

Note that commenting out the `paketo-buildpacks/node-engine` line causes the proper error message to be returned.

##### Expected behavior

A builder to be created

---

##### pack info
```
Pack:
  Version:  0.10.0+git-06d9983.build-259
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.7.2

Config:
  default-builder-image = "[REDACTED]"
```

##### docker info
```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 50
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: DBMV:TFQH:XFZA:E57Y:SSQA:3QMA:IXNZ:5J74:NGDS:PEXH:QOVA:MZH4
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 48
  Goroutines: 52
  System Time: 2020-05-14T17:53:08.460142458Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.default.svc.cluster.local:5000
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by simonjjones** [comment]
Our acceptance tests do currently test the case of defining buildpacks with both uri and image in a single builder.toml - using this fixture https://github.com/buildpacks/pack/blob/master/acceptance/testdata/pack_fixtures/builder.toml (the variable is configured at https://github.com/buildpacks/pack/blob/master/acceptance/acceptance_test.go#L1786 ) however none of the package_image buildpacks are used in the order definition. Perhaps this is more specific to using image buildpacks in the ordering?

**Comment by nebhale** [comment]
@simonjjones Image buildpacks in ordering works fine (I've got dozens of image buildpacks in half-a-dozen builders).  But the structure of your test indicates that there might be a problem integrating both kinds into the order.

**Comment by jromero** [comment]
Was able to confirm the issue. It has nothing to do with the `order` field.

It's a result of mutating an array by index but using a filter function that ultimately shifts indexes.
https://github.com/buildpacks/pack/blob/v0.10.0/builder/config_reader.go#L135-L141

Will get the fix out in the upcoming release unless there is a higher urgency you'd like to provide.
