### ISSUE TITLE
pack report discloses sensitive information

### ISSUE THREAD

**Issue by nebhale** [buildpacks/pack#624]
### Summary
Currently the output of `pack report` discloses the name of the the default builder.  This information can be sensitive and should not be reported.  There is a very real possibility of unintended disclosure of products and projects that are sensitive and non-public.  Contrast this with the output of `docker info` which does not disclose any sensitive information about how it is configured.

---

##### Steps
1. `pack report`

##### Current behavior
Prints the default builder name.

##### Expected behavior
Not print the default builder name.

---

##### pack info
```
Pack:
  Version:  0.10.0+git-06d9983.build-259
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.7.2

Config:
  default-builder-image = "[REDACTED]"
```

##### docker info
```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 50
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: DBMV:TFQH:XFZA:E57Y:SSQA:3QMA:IXNZ:5J74:NGDS:PEXH:QOVA:MZH4
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 48
  Goroutines: 52
  System Time: 2020-05-14T17:53:08.460142458Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.default.svc.cluster.local:5000
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by jromero** [comment]
There is certainly a trade-off here. We aren't trying to print the default-builder per se but instead would want a snapshot of the pack configuration file to better understand certain issues. This would help us address issues beyond builder specific such as buildpack registry, experimental setting, trusted builders. Could the buildpack registry be sensitive, the trusted builders, etc.?

We could theoretically (attempt) to parse the config file and individually pick every item we _think_ is appropriate to be captured but eventually might end up with a similar "can you please provide your `.pack/config.toml`?".

I wonder if it wouldn't be better to simply add an obvious notice to the issue template to "review and redact any information that might be deemed sensitive from `pack info` before submitting the issue"?

Thought?

**Comment by nebhale** [comment]
We regularly see people posting in issues or gists information that is clearly sensitive and I don't think our default behavior should be to give people the rope that they will then use to hang themselves.  I think _a lot_ of that information you're suggesting (e.g. a registry URI like `registry.nsa.gov/wiretapping-the-populatation:2020`) would be considered sensitive.

I'm all for having a lot of diagnostic information, but requiring diagnostic information that contains sensitive information ends up being a line that we just shouldn't cross.

**Comment by dfreilich** [comment]
At the same time, as mentioned above, we probably would want people to be able to see that information through `pack report`; would the addition of an `--explicit/-e` flag help? Any other suggestions for a flag?

**Comment by nebhale** [comment]
Very happy to see the solution chosen for this!
