### ISSUE TITLE
When platform API 0.2 is no longer supported, analyze and export don't need to branch on publish

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#629]
### Description
When platform API 0.2 is no longer supported, we can always assume that the lifecycle will have the creator.

Therefore when publish is false we will always use the creator.

The code in analyze and export that deals with publish true / false can be simplified to assume that publish is always true.

### Proposed solution
Delete a bunch of code. Delete the TODOs in the code that pertain to this issue.

**Comment by dfreilich** [comment]
We can also remove a branch on adding `-log-level` in the build logic here: https://github.com/buildpacks/pack/blob/957bf93b9afb078b3e1f9103127f855443a86556/internal/build/phases.go#L225

**Comment by jromero** [comment]
As of https://github.com/buildpacks/pack/pull/785 we no longer support platform API 0.2. We should do a cleanup based on these comments.

**Comment by dfreilich** [comment]
I don't fully understand what should be changed. Can't you still get into those branches, if you use are using an untrusted builder, and using either `--publish` or not using it?

**Comment by natalieparellano** [comment]
I believe this issue is outdated. The original RFC said that we should only care about trusted/untrusted when publishing (to protect registry credentials), but we later decided that it's also insecure to mount the docker daemon socket in an untrusted builder. So I think we still need to branch on publish. We can probably close this issue.

**Comment by dwillist** [comment]
Came across a comment in code today that referenced this issue. Seems like we can close this & remove all the TODO's that reference it.
