### ISSUE TITLE
Pack is painfully slow

### ISSUE THREAD

**Issue by chrono2002** [buildpacks/pack#632]
Guys, I'm sorry, why pack is so painfully slow?
It takes ~20 sec to build or rebuild a simple hello world app every time.
I've got a blazingly fast machine with a huge amounts of ram.
Docker in experimental mode (with buildkit) is much faster.
Pack takes ~10 seconds on pre-detecting phase and another ~10 to build an image. 
That's ~20 seconds overhead!

```
root@host:~/buildpacks# time ./build.sh 
2020/05/15 22:13:59.290024 ===> DETECTING
[detector] io.buildpacks.sample.node 0.0.1
2020/05/15 22:14:01.262084 ===> ANALYZING
[analyzer] Restoring metadata for "io.buildpacks.sample.node:v13.14.0" from cache
2020/05/15 22:14:03.031370 ===> RESTORING
[restorer] Restoring data for "io.buildpacks.sample.node:v13.14.0" from cache
2020/05/15 22:14:04.910182 ===> BUILDING
[builder] ---> Node Buildpack
[builder] ---> Deploying Node v13.14.0... cached
[builder] build = false
[builder] launch = false
[builder] cache = true
[builder] v13.14.0
2020/05/15 22:14:06.473223 ===> EXPORTING
[exporter] Reusing layer 'launcher'
[exporter] Reusing 1/1 app layer(s)
[exporter] Reusing layer 'config'
[exporter] *** Images (9773d5c5a56f):
[exporter]       index.docker.io/library/sample-nodejs:v4
[exporter] Reusing cache layer 'io.buildpacks.sample.node:v13.14.0'
2020/05/15 22:14:10.018314 Successfully built image sample-nodejs:v4

real    0m18.914s
user    0m0.172s
sys     0m0.032s
```

**Comment by chrono2002** [comment]
I've decided to try latest master and it's much more faster but still not enough.
What are program doing for about ~10sec before the CREATING step?

root@host:~/buildpacks# time ./build.sh 
2020/05/15 22:52:00.243838 ===> CREATING
[creator] ---> DETECTING
[creator] io.buildpacks.sample.node 0.0.1
[creator] ---> ANALYZING
[creator] Restoring metadata for "io.buildpacks.sample.node:v13.14.0" from cache
[creator] ---> RESTORING
[creator] Restoring data for "io.buildpacks.sample.node:v13.14.0" from cache
[creator] ---> BUILDING
[creator] ---> Node Buildpack
[creator] ---> Deploying Node v13.14.0... cached
[creator] build = false
[creator] launch = false
[creator] cache = true
[creator] v13.14.0
[creator] ---> EXPORTING
[creator] Reusing layer 'launcher'
[creator] Reusing 1/1 app layer(s)
[creator] Reusing layer 'config'
[creator] *** Images (9773d5c5a56f):
[creator]       index.docker.io/library/sample-nodejs:v5
[creator] Reusing cache layer 'io.buildpacks.sample.node:v13.14.0'
2020/05/15 22:52:03.892267 Successfully built image sample-nodejs:v5

real    0m11.739s
user    0m0.200s
sys     0m0.028s

**Comment by jromero** [comment]
This is very valuable feedback. Thank you for the input and furthermore trying it out on master. We've got performance at the forefront of our minds so getting these insights and expectations voiced is greatly appreciated.

You can see a bit more detail by using the `--verbose`.

**Comment by jromero** [comment]
I'm will to throw a wild guess that this might be pulling the image (or at least checking if the images are up to date). I'd be interested to see what the command arguments are that you are using you can preferch the images and then run build with `--no-pull`.

**Comment by jromero** [comment]
Can we take "funky" as a positive comment? 😄

Is there more insight or conversation needed to be had here?

We are always looking to improve performance wherever possible but would hate to have an open-ended issue around. @chrono2002 were these answers satisfactory?
