### ISSUE TITLE
Remove [creator] eye catcher

### ISSUE THREAD

**Issue by nebhale** [buildpacks/pack#641]
### Description
With the recent update to use a single container for all phases, there is now a single `[creator]` eye-catcher on every single line.  This makes the output redundant and should be removed.

### Additional context
![Screen Shot 2020-05-20 at 11 56 33](https://user-images.githubusercontent.com/60754/82485901-f7b4a280-9a90-11ea-933d-fca7ef3a1bd1.png)

**Comment by natalieparellano** [comment]
Breadcrumb: see `logging.NewPrefixWriter` in internal/build/phase.go

**Comment by dgageot** [comment]
This is fixed with #653. It can be closed
