### ISSUE TITLE
Pack inspect-buildpack command

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/pack#642]
### Description
It would be great if `pack` supported a `inspect-buildpack` command. Now that more projects such as Paketo are starting to ship buildpackage artifacts both as `.cnb` artifacts and to a registry, it would be helpful for users to be able to see what's inside of the buildpack. 

### Proposed solution
Create a `pack inspect-buildpack` command. I'm sure we could display a lot of useful buildpack metadata here, but I could see at the minimum it would be great to see the following in the output:
- Buildpack ID
- Buildpack Name
- Buildpack Homepage
- Buildpack Version
- Buildpack Dependencies/Versions

Example using https://github.com/paketo-buildpacks/go/blob/master/buildpack.toml (assuming that the package.toml is similar)
``` 
pack inspect-buildpack go-buildpackage.cnb
.........
ID: "paketo-buildpacks/go"
Name: "Go Buildpack"
Version: "1.0"
Homepage: "https://github.com/paketo-buildpacks/go"

Dependencies:
   ID: "paketo-buildpacks/dep"
   Version: "0.0.109"
   ..........
   ID: "paketo-buildpacks/mod"
   Version: "0.0.112"
```

### Describe alternatives you've considered
Without this command, a user can only see more granular buildpackage metadata by running `inspect-builder` and visiting the homepage URL.

**Comment by jromero** [comment]
NOTE: This feature should support both `image` and `.cnb file` as inputs.

For example:

```
# image
pack inspect-buildpack my-org/my-buildpack:latest

# cnb file
pack inspect-buildpack my-buildpack.cnb
```

**Comment by dwillist** [comment]
Happy to look at this.

**Comment by kvedurmu** [comment]
fyi, I was just playing around with this, and noticed that the command blows up when running inspect-buildpack without arguments. It should print the help text.

```
./pack inspect-buildpack
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/buildpacks/pack/internal/commands.InspectBuildpack.func1(0xc000336000, 0x1f53d70, 0x0, 0x0, 0x0, 0x11de7e0)
	github.com/buildpacks/pack/internal/commands/inspect_buildpack.go:69 +0x421
github.com/buildpacks/pack/internal/commands.logError.func1(0xc000336000, 0x1f53d70, 0x0, 0x0, 0x0, 0x0)
	github.com/buildpacks/pack/internal/commands/commands.go:53 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000336000, 0x1f53d70, 0x0, 0x0, 0xc000336000, 0x1f53d70)
	github.com/spf13/cobra@v0.0.6/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000cd340, 0xc00033c140, 0xc0000cd340, 0x0)
	github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.6/command.go:885
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v0.0.6/command.go:878
main.main()
	github.com/buildpacks/pack/cmd/pack/main.go:26 +0xeb
```

The command is great though, and will be super helpful to users! I really like the addition of the depth flag

**Comment by jromero** [comment]
Thanks for the report. Created an issue for it. We'll get it in before the release.
