### ISSUE TITLE
Move project.toml parsing out of internal package

### ISSUE THREAD

**Issue by dgageot** [buildpacks/pack#657]
When using `pack` as a library like we do in [Skaffold](https://github.com/GoogleContainerTools/skaffold), it would be useful to use pack's code to parse `project.toml` files. The code is currently in the `internal` package which make it impossible for downstream projects to use.

**Comment by jromero** [comment]
This makes sense in the short-term. 

Long-term it might be worth moving to buildpacks/lifecycle as some of the functionality from project.toml would be ideal to implement in the lifecycle for platforms such as CI systems that execute the lifecycle directly.

cc: @ekcasey / @natalieparellano
