### ISSUE TITLE
User-defined cache volume names

### ISSUE THREAD

**Issue by dgageot** [buildpacks/pack#665]
`pack build` creates two cache volumes named after the final image name:

```
func NewVolumeCache(imageRef name.Reference, suffix string, dockerClient client.CommonAPIClient) *VolumeCache {
	sum := sha256.Sum256([]byte(imageRef.Name()))
	return &VolumeCache{
		volume: fmt.Sprintf("pack-cache-%x.%s", sum[:6], suffix),
		docker: dockerClient,
	}
}
```

One has a ".launch" suffix and the other has a ".build" suffix.

When rebuilding an image from slightly different sources, with the same base name but a different tag, brand new cache volumes are created. In a tight development loop, this leads to downloading again many things we have in cache. It also consume a lot of disk space since those volumes have to deleted manually.

It would be useful to either:

 + Base the names of those volumes on the final image's base name (without the tag), rather than the full name.
 + Let the user override those names
 + Expose a way to pass volume names in `LifecycleOptions` and `BuildOptions` so that components who use pack as a library can choose a different caching strategy.

**Comment by ekcasey** [comment]
@dgageot I think we can default to the safer (cache per image) but allow users to supply a cache volume name. However, the lifecycle currently cleans up unused layers from the cache after every build, so using the same cache for multiple images could result in unpleasant fights about which layers should be in the cache. I think some more fundamental things might have to change about caching to make this work well in a variety of cases.

Sharing a single launch cache that grows until it is explicitly cleaned up seems like a good idea to me (layers are pulled out of this cache by their shas during export, the risk low if you trust the lifecycle that put them there).

It's more complicated for the build cache, where layer contents are restored to disk if they belong to a detected buildpack, without any mechanism to check if they are the "right layers".

**Comment by jromero** [comment]
Related but not resolved by https://github.com/buildpacks/pack/pull/1039

**Comment by jromero** [comment]
@dfreilich I've added this issue to the next milestone due to the ongoing demand for it. Feel free to overrule me though. :)

**Comment by dwillist** [comment]
There is a RFC about to go through that will provide this level of flexibility and make the `caching` flags a bit more coherent here buildpacks/rfcs#149.

**Comment by jromero** [comment]
This is ready to implement as part of https://github.com/buildpacks/pack/issues/1077. Closing as duplicate.
