### ISSUE TITLE
Externalize suggested-builders output

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#666]
### Description
Currently when a user runs `suggest-builders` it looks at a built-in list of builders and looks up the manifest on the registry for additional metadata. There are two improvements that can be made here.

1. The registry lookup is expensive creating a lag time in output for the user
2. Changing the suggested builders requires a new version of pack to be released.

### Proposed solution

1. Create a file that is checked into this repo in `json` format similar to what is built-in to the compiled binary.
2. `pack` fetches this file directly from GitHub containing all the information necessary. Effectively condensing multiple http requests to just one.
3. A scheduled job periodically looks for updates on the registry for additional metadata and updates the file.

##### `pack` caching

`pack` could cache the results from the initial suggest-builders call. The initial poor UX would still be present.

### Additional context
- [ ] This feature should be documented somewhere

**Comment by jromero** [comment]
Need more thought here.

**Comment by simonjjones** [comment]
Now that we use suggested builders as our default *trusted* builders to determine whether `pack build` should use the `creator` lifecycle phase this change would have a broader impact than originally expected. More commands would be required to poll the external source which will add complexity to our codebase, and potentially complications when an internet connection is not consistent. There is also a potential attack vector added as a result of this change, in that someone distributing a malicious builder could attempt to distribute a malicious suggested builders list including their builder.

**Comment by jromero** [comment]
There's been further discussion that this information can be hosted by the buildpacks registry: https://github.com/buildpacks/registry-api/issues/56
