### ISSUE TITLE
pack should provide a way to set a builder as untrusted

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/pack#670]
### Description
In #631 the concept of trusted builders was introduced. We would like to provide a way to set a builder as untrusted.

### Proposed solution
**AC 1**
When I run `pack trust-builder <some-builder>`
And I run `pack untrust-builder <some-builder>`
And I run `pack list-trusted-builders`
Then I should not see `<some-builder>` in the output

**AC 2**
When I run `pack trust-builder <some-builder>`
And I run `pack untrust-builder <some-builder>`
And I run `pack inspect-builder <some-builder>`
Then I should see something indicating that the builder is NOT trusted

### Additional context
This issue is blocked on #567 and #669 in order to make the AC will easier.
If we prefer not to block this issue on the issues above, we can change the AC to check that `pack` will run the `lifecycle` in five separate phases when running `pack build my-app --publish -B <some-builder>` (`lifecycle image` should be available, otherwise the command will fail).
For more information, see [this blog post](https://medium.com/buildpacks/faster-more-secure-builds-with-pack-0-11-0-4d0c633ca619).

**Comment by simonjjones** [comment]
@yaelharel @jromero Do we think there is any circumstance where we might want to untrust a suggested builder? Or should this work only refer to those builders trusted with the `trust-builder` command?

**Comment by jromero** [comment]
@simonjjones we can limit this to "work only refer to those builders trusted with the trust-builder command" and expand on it once a request for it to untrust suggested builders is made.
