### ISSUE TITLE
Publish to Chocolatey

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#703]
### Description
As a Windows user, I'd like to be able to install `pack` via https://chocolatey.org/.

### Proposed solution

Use the information provided at https://chocolatey.org/docs/create-packages to create a distributable package of `pack` via https://chocolatey.org/.

### Additional context
- [x] This feature should be documented:
    - [Release notes](https://github.com/buildpacks/pack/blob/main/.github/workflows/build.yml#L186) (maintained in this repo)
    - https://buildpacks.io/docs/install-pack/

Relates to https://github.com/buildpacks/docs/issues/7

**Comment by dfreilich** [comment]
Looks like it is already hosted on Chocolatey here (by @adrianchia): https://chocolatey.org/packages/buildpacks

The source code for the package is here: https://github.com/adrianchia/chocolatey-packages/tree/master/automatic/buildpacks
