### ISSUE TITLE
Is there a way to set env vars with multiples buildpacks?

### ISSUE THREAD

**Issue by carlosbustillordguez** [buildpacks/pack#706]
I am using `pack build` with two buildpacks:

`pack build myapp:$(date +%Y%m%d%H%M%S) --builder heroku/buildpacks:18 --path ./myapp/ --buildpack ./sr-buildpacks-ffmpeg/ --buildpack ./ruby-cnb/`

The ruby-cnb buildpack is https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/make-app-runnable/

The sr-buildpacks-ffmpeg has the bin/build script:

```sh
#!/usr/bin/env bash
set -eo pipefail

echo "---> ffmpeg Buildpack"

# GET ARGS
LAYERS_DIR="$1"

# ffmpeg layer
FFMPEG_LAYER="${LAYERS_DIR}/ffmpeg"
mkdir -p $FFMPEG_LAYER

# Set the layer to be included in the final image
echo -e 'launch = true' > "$FFMPEG_LAYER.toml"

# ffmpeg URL
FFMPEG_URL="https://s3-us-west-1.amazonaws.com/kitcast/cdn/ffmpeg-release-64bit-static.tar.xz"

# Download ffmpeg to FFMPEG_LAYER
echo "---> Dowloading ffmpeg from $FFMPEG_URL"
curl -L --silent --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 $FFMPEG_URL | tar -Jx -C $FFMPEG_LAYER

# Add ffmpeg to the PATH
echo "---> Adding the ffmpeg to the PATH variable"
PROFILE_PATH="${FFMPEG_LAYER}/profile.d/ffmpeg.sh"
mkdir -p $(dirname $PROFILE_PATH)
echo "export PATH=\"\$PATH:$FFMPEG_LAYER/ffmpeg-3.4.2-64bit-static\"" > $PROFILE_PATH
echo "export FOO=\"foo\"" >> $PROFILE_PATH

echo "---> Done"
```
I noted when two buildpacks are defined, the PATH env variable if not updated. Also, I tried changing the buildpacks orders with the same result. 

Am I missing some concept or implementation?

What is the right way to modify the PATH variable?

**Comment by jkutner** [comment]
hello @carlosbustillordguez. I think you'll need to add `build = true` to your `${FFMPEG_LAYER}.toml`. For example

```bash
echo "build = true" >> ${FFMPEG_LAYER}.toml
```

This will expose the ffmpeg layer to subsequent buildpacks.

**Comment by carlosbustillordguez** [comment]
Hello @jkutner!! Thank you for your answer. I tried your recommendation, but the environment PATH variable is not updated in the container:
```sh
heroku@7790e077fcb3:/$ env
HOSTNAME=7790e077fcb3
PWD=/
HOME=/app
TERM=xterm
SHLVL=1
CNB_APP_DIR=/workspace
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CNB_LAYERS_DIR=/layers
_=/usr/bin/env
```

Also, I tried to create some symlinks in `/bin`, but the build process doesn't permissions for that.

**Comment by jkutner** [comment]
@carlosbustillordguez can you try renaming `$FFMPEG_LAYER/ffmpeg-3.4.2-64bit-static` to `$FFMPEG_LAYER/bin`. I think this way it will be [automatically put on your PATH](https://github.com/buildpacks/spec/blob/main/buildpack.md#layer-paths).

**Comment by jkutner** [comment]
Oh nevermind, i just saw your last comment. How are you starting that shell? What `docker run` command are you using?

**Comment by jkutner** [comment]
also, if your `sr-buildpacks-ffmpeg` buildpack on Github where I can give it a run?

**Comment by carlosbustillordguez** [comment]
> Oh nevermind, i just saw your last comment. How are you starting that shell? What `docker run` command are you using?

Hi @jkutner:

I am using the following command:
```sh
docker run --rm -p 8080:8080 myapp:20200626091810
```
But I noted if I use only one build pack (sr-buildpacks-ffmpeg), the path is updated

During my tests, I noted if the directory `$FFMPEG_LAYER/ffmpeg-3.4.2-64bit-static` is renamed to `$FFMPEG_LAYER/bin` the path is updated automatically, but only is I use one buildpack.

You can use the `sr-buildpacks-ffmpeg`  from here:  git@github.com:carlosbustillordguez/sr-buildpacks-ffmpeg.git

I am using the the `sr-buildpacks-ffmpeg` along with the sample buildpack: https://buildpacks.io/docs/buildpack-author-guide/create-buildpack; which I named `ruby-cnb`.

**Comment by jkutner** [comment]
@carlosbustillordguez I added this line to your buildpack and it put `ffmpeg` on my path at build and launch:

```
ln -s "${FFMPEG_LAYER}/ffmpeg-3.4.2-64bit-static" "${FFMPEG_LAYER}/bin"
```

I'm not sure why this wasn't working for you during build, but when you attach to the container with `docker exec`, I don't think your `profile.d` scripts will be sourced (nor with the files in `<layer>/env` be loaded). That's because the entrypoint (the `launcher`) is responsible for doing this. Instead, try launching a container like:

```
$ docker run -it myapp:20200626091810 bash
```

Can you give this a try and see if it works? https://github.com/carlosbustillordguez/sr-buildpacks-ffmpeg/pull/1

**Comment by carlosbustillordguez** [comment]
Hi @jkutner I added your line to the buildpack, then I launched the container like:

```shell
docker run -it --rm myapp:20200626091810 bash
```
The `${FFMPEG_LAYER}/profile.d/ffmpeg.sh` script is sourced and the `${FFMPEG_LAYER}/bin` is added automatically to the PATH environment variable automatically, as described [here](https://github.com/buildpacks/spec/blob/main/buildpack.md#layer-paths).

> I'm not sure why this wasn't working for you during build, but when you attach to the container with docker exec, I don't think your profile.d scripts will be sourced (nor with the files in <layer>/env be loaded). That's because the entrypoint (the launcher) is responsible for doing this.

That's was the problem, I was checking the environment variables with `docker exec` instead `docker run`. After inspecting the docker image, I noted the entrypoint is `/cnb/lifecycle/launcher` and passing the `env` command as argument to the launcher I can see the environment variables with `docker exec`:

```shell
docker exec 89172cbffd2d /cnb/lifecycle/launcher env
LD_LIBRARY_PATH=/layers/com.examples.buildpacks.ruby/ruby/lib
HOSTNAME=89172cbffd2d
PWD=/workspace
HOME=/app
FOO=foo
SHLVL=1
PATH=/layers/sr.cn.buildpacks.ffmpeg/ffmpeg/bin:/layers/com.examples.buildpacks.ruby/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/layers/sr.cn.buildpacks.ffmpeg/ffmpeg/ffmpeg-3.4.2-64bit-static
_=/usr/bin/env
```

I going to modify the buildpack to remove the `${FFMPEG_LAYER}/profile.d/ffmpeg.sh`, adding automatically the `${FFMPEG_LAYER}/bin` in this case is a better approach. 

Thanks for your help and support!!
