### ISSUE TITLE
Make it more obvious that a builder is trusted/untrusted

### ISSUE THREAD

**Issue by djoyahoy** [buildpacks/pack#711]
### Description
When using a custom builder via `pack build`, it is unclear whether or not the builder is trusted/untrusted. I had created a custom builder with my registry CA cert, and it was failing in the analyze step because analyze occurs using a different image. I realized that this was because my builder was not trusted, but it is not immediately obvious.  

### Proposed solution
Inform the user with a log message that the builder is not trusted and will use a different image for analyze and export. Alternatively, if the build fails in analyze or export, inform the user that this may be the result of being untrusted.

### Describe alternatives you've considered
I haven't checked documentation, but hopefully this is documented somewhere.

### Additional context
N/A

**Comment by dfreilich** [comment]
We've added it to inspect-builder (https://github.com/buildpacks/pack/pull/697), but this is definitely useful to include as well.
