### ISSUE TITLE
Pack Build --trust-builder turns off color

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#719]
### Summary

I noticed, while experimenting with `pack build --trust-builder`, that it seemed to toggle the `--no-color` flag as well. 

##### Steps

1. `$  pack build test -p samples/apps/ruby-bundler/ -B cnbs/sample-builder:bionic --trust-builder`

##### Current behavior

![image](https://user-images.githubusercontent.com/7035673/86172971-33f60c80-baed-11ea-85ae-19ade408c832.png)

##### Expected behavior

The output to look like: 
![image](https://user-images.githubusercontent.com/7035673/86173005-3f493800-baed-11ea-8806-da4968aa0775.png)

---

##### pack info

```
Pack:
  Version:  0.11.2+git-063a80d.build-677
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.7.5

Config:
  default-builder-image = "gcr.io/paketo-buildpacks/builder:full-cf"
```
##### docker info

```
Client:
 Debug Mode: false
 Plugins:
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 11
  Running: 10
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: NGMV:CCGN:FIZ2:LNQO:KXXH:S4CZ:X7PS:QA5A:3ISF:PZHM:22JA:LLDO
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 92
  Goroutines: 83
  System Time: 2020-06-30T20:18:37.5566012Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by jromero** [comment]
This might be an 'issue' with the lifecycle since when trusted pack doesn't print any colored eyecatchers. Does the last line have color (it's hard to tell on the picture)?

**Comment by dfreilich** [comment]
Ah yes, the last line does have colors.

**Comment by natalieparellano** [comment]
I believe (as @jromero said) it's because when trusted the lifecycle is running `creator` and omits printing `[creator]` in front of every line. That said I am not sure why e.g., `---> DETECTING` wouldn't be printed with color.

**Comment by jromero** [comment]
@natalieparellano this would be because it's also printed by the lifecycle. See the different output from different versions in this PR: https://github.com/buildpacks/pack/pull/653#issue-422828879

@dfreilich let me know if the explanation isn't sufficient but ultimately it's up to the lifecycle to provide this "color" as part of it's output which it does on newer versions (>= 0.8.0).
