### ISSUE TITLE
Buildpack Registry config commands

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#745]
### Description

As a `pack` user it would be nice to have commands to manage the registries in the `config` file.

### Proposed solution

- [x] `pack list-buildpack-registry` - a new command that will list all the `[[registries]]` config in `.pack/config.toml`.
- [x] `pack add-buildpack-registry` - a new command that will add to the `[[registries]]` config in `.pack/config.toml`.
- [ ] `pack remove-buildpack-registry` - a new command that will remove a registry from the `[[registries]]` config in `.pack/config.toml`.
- [ ] `pack set-buildpack-registry` - a new command that will mutate the `default-registry` config in `.pack/config.toml`.

For more details on what the data structure of the `.pack/config.toml` see [RFC #44](https://github.com/buildpacks/rfcs/blob/main/text/0044-pack-publish-buildpack.md#pack-register-buildpack-url).

### Additional Refactor/Clean-up
`add-buildpack-registry `-> `add-registry`
`list-buildpack-registry` -> `list-registries`

### Additional context
- [x] This feature should be documented somewhere

- These commands should be hidden via `experimental` config option.

**Comment by elbandito** [comment]
@jromero and @dfreilich I'm curious what your opinion is on removing `buildpack` from the command?  For example, `add-buildpack-registry` would become `add-registry`?  I personally like any opportunity to type less characters, but I also don't know if there could be other types of `registries`, making it too vague.  Thoughts?

**Comment by dfreilich** [comment]
Hmmm. I would personally find it confusing, assuming that it's talking about OCI registries, rather than anything buildpack related, and then wonder whether it relates to #821. I'd personally vote for keeping buildpacks in (and then just hope people use `pack completion`, so it's less to type)

**Comment by dfreilich** [comment]
@jromero In light of https://github.com/buildpacks/pack/issues/597, what should these commands look like?

**Comment by dfreilich** [comment]
And should that impact what the commands in #839 is as well?

**Comment by jromero** [comment]
@elbandito I'm in favor of making the buildpack registries the primary registry types we talk about. Hence they shouldn't need the explicit denotation, as you suggested. We can then use "image registries" when talking about oci/docker registries.

CC: @jkutner / @ekcasey

**Comment by elbandito** [comment]
@jromero sounds good!  I'll create an issue to refactor the following:

`add-buildpack-registry` -> `add-registry`
`list-buildpack-registyr` -> `list-registries`

Or do we want to get these ^ in as a patch?

**Comment by dfreilich** [comment]
![party](https://media2.giphy.com/media/l3nWmPFBffbkCd3Ow/giphy.gif)
