### ISSUE TITLE
Update `pack build -R` to use named buildpack registries

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#747]
### Description

As a pack user, I would like to use a **named registry* when running `build`. Currently the `-R` flag takes a git URL. This flag should also be aligned with `pack register-builderpack -r` (notice the lowercase `-r`).

### Proposed solution

1. Change the casing of `-R` flag to `-r`
2. `-r` should accept ONLY a named registry instead of a git URL

### Additional context
- [ ] This feature should be documented somewhere

**Comment by supra08** [comment]
@jromero @elbandito I would like to take up this issue.
