### ISSUE TITLE
max-time in the curl command

### ISSUE THREAD

**Issue by kranthi117** [buildpacks/pack#753]
### Summary
I see that the following command is used to fetch ruby `set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.7.0.tgz -s -o - | tar zxf - `
I am on a slow network and download does not complete in 150 seconds. I am always getting a timeout error. I am not able to use `pack` because of this

---

##### Steps

1. Run `pack` on a slow network

##### Current behavior
Getting timeout errors

##### Expected behavior
Expect pack to complete succesfully

---

##### pack info
Pack:
  Version:  0.12.0+git-a3ff87a.build-823
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.8.0

Config:
(no config file found at .pack/config.toml)

##### docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 7.778GiB
 Name: docker-desktop
 ID: HM42:JFNU:WRCD:YB3R:7L6M:5Z6T:FINV:ZFP7:KPXY:7T6L:QEM3:XURH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by natalieparellano** [comment]
Hi @kranthi117 thanks for reporting this issue. Is it possible you could share which builder you are using? I suspect this is an issue with the ruby buildpack vs. pack itself. We can help direct this to the right place.

**Comment by kranthi117** [comment]
I am using ` pack build --builder heroku/buildpacks`

**Comment by jromero** [comment]
This is an implementation detail of the buildpack and not really something that `pack` or the Cloud Native Buildpacks project has any control over. 

It may be more appropriate to file this issue on the buildpack's repo which I believe is: https://github.com/heroku/heroku-buildpack-ruby

A quick glance at the repo makes mention to an environment variable that may allow you to control the timeout:

[`CURL_TIMEOUT`](https://github.com/heroku/heroku-buildpack-ruby/blob/1486bdd34f4d110cfe13ba515db3678ec082c544/lib/language_pack/fetcher.rb#L47)

You should be able to pass it via pack using the following command:

```
pack build --env CURL_TIMEOUT=300 --builder heroku/buildpacks ...
```

CC: @jkutner / @jabrown85

**Comment by schneems** [comment]
That's right you can configure with an env var inside of the Ruby buildpack https://github.com/heroku/heroku-buildpack-ruby/blob/61b8ebd2611dcc80d4a119f847a0fffcdee3103a/lib/language_pack/fetcher.rb#L47

**Comment by jromero** [comment]
Thank you for the additional verification @schneems.

@kranthi117, I hope this answers your question.

- If this doesn't answer your question, please feel free to reopen the issue and add more information.
- If you have another question, please open a new issue.

Additionally, we have an awesome community on [slack](https://slack.buildpacks.io) that can help.
