### ISSUE TITLE
Pack CLI for Cent OS

### ISSUE THREAD

**Issue by Jajitha94** [buildpacks/pack#767]
### Description
We have been using pack CLI for  building docker images in local.But we want to use it on out bamboo agents which runs on Cent OS.

### Proposed solution
We could include the installation package for Cent OS as well which will help to run the PACK CLI on CICD pipelines as well.

### Describe alternatives you've considered
We have been using external docker files and docker compose files which works fine on bamboo but I see this PACK CLI will be lot more efficient.wanted to give it a try in my CICD pipeline through bamboo

### Additional context
- [ ] This feature should be documented somewhere

**Comment by jromero** [comment]
`pack` _should_ work on CentOS if installed manually.

```
(export GH=buildpacks/pack; export LATEST=$(curl -s https://api.github.com/repos/$GH/releases/latest | grep -o -E "https://.+?-linux.tgz"); echo "$LATEST"; curl -sSL "$LATEST" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv $(basename $GH))
```

Have you tried installing it and it didn't work?

If it does work, is the ask here that we provide an easier mechanism for installation like `.rpm`, addition to an RPM repo, or something else?

**Comment by Jajitha94** [comment]
Thanks for the response,I didn't try installing it manually but will do it soon.
The ask is actually about installation like .rpm as it would be better and simplest option to install on our servers

**Comment by jjbustamante** [comment]
Closing this issue as Centos OS is being discontinued
