### ISSUE TITLE
WARN when a deprecated buildpack API version is being used

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#788]
### Description

Since the new [lifecycle descriptor](https://github.com/buildpacks/pack/issues/780) has the potential of deprecating buildpack API (and platform API) versions we should warn when a buildpack is using a deprecated buildpack API so that it's less surprising in future versions.

### Proposed solution

```gherkin
Given there is buildpack 'id@v1' with buildpack API 0.2
And lifecycle has a descriptor with:
  [apis]
  [apis.buildpack]
  deprecated = ["0.2"]
When I run 'pack create-builder ...' including buildpack 'id@v1'
Then I should see a warning "buildpack 'id@v1' is using deprecated Buildpacks API version 0.2"
```

**Comment by danielcooperxyz** [comment]
I've made a [PR](https://github.com/buildpacks/pack/pull/816) that I think makes this change, but it might be worth discussing the best way of implementing this functionality here.

**Comment by jromero** [comment]
Hi @danielcooperxyz, thank you for your interest in resolving this issue. Given that this project revolves around specification (and it's implementation) there are typically a lot of pre-existing conversation. I could have done a bit better at providing supporting information and maybe more elaborate acceptance criteria.

For some context to this specific issue, if you follow the breadcrumbs, there is an RFC where this requirement ultimately comes from ([RFC #49](https://github.com/buildpacks/rfcs/blob/main/text/0049-multi-api-lifecycle-descriptor.md#lifecycle-descriptor)). _Keep in mind, that I've purposefully omitted support of "for versions 1.0+, version x.n implies support for [x.0,x.n]" in this implementation to minimize the complexity._

As for the implementation of this issue, it should be as straightforward as matching the buildpack API version of a given buildpack with one that is inside the `bldr.LifecycleDescriptor().APIs.Buildpack.Deprecated` array. In other words, if any of the deprecated buildpack APIs match exactly (`Compare(...) == 0`) the buildpack API of a buildpack then a warning should be logged for that buildpack. The buildpack should not be excluded.

Here are a few more scenarios if it were to help:

```gherkin
---
Scenario: Older deprecated version
---
Given there is buildpack 'id@v1' with buildpack API 0.2
And lifecycle has a descriptor with:
  [apis]
  [apis.buildpack]
  deprecated = ["0.2", "0.3"]
  supported = ["0.2", "0.3", "0.4"]
When I run 'pack create-builder ...' including buildpack 'id@v1'
Then I should see a warning "buildpack 'id@v1' is using deprecated Buildpacks API version 0.2"

---
Scenario: Newer deprecated version
---
Given there is buildpack 'id@v1' with buildpack API 0.3
And lifecycle has a descriptor with:
  [apis]
  [apis.buildpack]
  deprecated = ["0.2", "0.3"]
  supported = ["0.2", "0.3", "0.4"]
When I run 'pack create-builder ...' including buildpack 'id@v1'
Then I should see a warning "buildpack 'id@v1' is using deprecated Buildpacks API version 0.3"

---
Scenario: Non deprecated version
---
Given there is buildpack 'id@v1' with buildpack API 0.4
And lifecycle has a descriptor with:
  [apis]
  [apis.buildpack]
  deprecated = ["0.2", "0.3"]
  supported = ["0.2", "0.3", "0.4"]
When I run 'pack create-builder ...' including buildpack 'id@v1'
Then I should NOT see a warning "buildpack 'id@v1' is using deprecated Buildpacks API version"
```

**Comment by danielcooperxyz** [comment]
Thanks for the context, it helps a lot. Sorry for taking a while to respond.

I think this makes a lot of sense, and I was trying to catch all with the logic in my current change. Really would be good to understand how to translate those scenarios into the acceptance test style you guys are using currently?
