### ISSUE TITLE
Investigate Windows specific reader closing workaround

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#792]
I think we'd want to investigate this a tad further. At least have a bit better understanding as to why this was necessary. I'm afraid this could have some adverse effects. If I'm not mistaken we use this strategy in various places so making this change only here either means it's "broken" in multiple places or this particular implementation has issues.

Originally posted by @jromero in https://github.com/buildpacks/pack/pull/739#discussion_r466973393

**Comment by dfreilich** [comment]
After investigating it, it seems that it is an outgrowth of the changes they made to allow copying Windows containers ([here](https://github.com/buildpacks/pack/pull/739/files#diff-752580bc032ba1b377c8425bd4928028R79-R131)). When you don't copy the container, it successfully runs, but with it, it doesn't. I'm assuming it's a side complication of using the other container/`xcopy`, which maybe closes the reader preemptively, and causes the program to hang as a result? 

It doesn't seem like the additional `closing` check added is harmful, however.

**Comment by dfreilich** [comment]
Given this investigation, @jromero are you comfortable closing it?

**Comment by jromero** [comment]
> Given this investigation, @jromero are you comfortable closing it?

👍  Yes. Thank you for additional insight.
