### ISSUE TITLE
Expand volume tests to occur on Windows

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#793]
Hmm... in that case, I would expect the `windows` subset of tests to have the same number of cases as the `posix` ones, no? It looks like for Windows we just check that the drive is transformed, and on posix we test all sort of things.

_Originally posted by @natalieparellano in https://github.com/buildpacks/pack/pull/739#discussion_r468687677_

**Comment by dwillist** [comment]
Giving this a try.
