### ISSUE TITLE
Publish checksums/signed releases

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#799]
### Description

I would like to have proof that the `pack` releases on my system are the ones released by the Buildpacks organization. 
 
### Proposed solution

When releasing `pack` releases, we should publish checksums of the artifacts (`sha256`), and sign the artifacts as well (using PGP signing). 

### Additional context
- [ ] This feature should be documented somewhere

**Comment by dfreilich** [comment]
This has been an open issue in K8s (https://github.com/kubernetes/release/issues/914) as well for a while, with a bunch of useful links posted. Some of the tools we may want to consider are:
* [minisign](https://jedisct1.github.io/minisign/) (mentioned [here](https://blog.gtank.cc/modern-alternatives-to-pgp/))
* [tuf](https://github.com/theupdateframework/tuf/) (CNCF graduated) – Framework to secure software update systems

[goreleaser](https://github.com/goreleaser/goreleaser/) seems like a really helpful tool to remove some of the complexity around releasing, but I'm not sure it's necessary for us

Initially, I'll work towards adding 2 new files per each release artifact: 
1. `pack-X.....sha256` (`sha256` checksum)
1. `pack-X.....asc` (`gpg` signature)

**Comment by dfreilich** [comment]
The linked PR didn't include PGP signing.

**Comment by jromero** [comment]
@dfreilich can we create a new issue for that? I feel like it's not as critical given the added complexity.
