### ISSUE TITLE
Cannot find online command line reference for pack

### ISSUE THREAD

**Issue by steren** [buildpacks/pack#812]
I was looking for the list of flags of the `pack` tool.

But I was not able to find it online.

I think pack is missing a page with the reference of all its flags and what they do.

**Comment by grant** [comment]
I don't believe there are docs like in html/md files. The best reference are the help commands like `pack build -h`.

The way to produce docs would probably be to have a script that gathers the cobra commands in this directory:
https://github.com/buildpacks/pack/tree/main/internal/commands

And gen some files like such:
https://github.com/spf13/cobra/blob/master/doc/md_docs.md

**Comment by dfreilich** [comment]
@grant Good find! We actually use that to generate Pack CLI docs here: https://buildpacks.io/docs/reference/pack/

(the generating code is here: https://github.com/buildpacks/docs/blob/main/tools/get_pack_commands.go)

**Comment by dfreilich** [comment]
@steren We have that in the docs repo, as I linked above. Is this a suggestion to have that documentation in the `buildpacks/pack` repo (which we've tossed around, cc @jromero)? Or is the presence of the docs in the standard buildpacks.io/docs good enough for your purposes?

**Comment by steren** [comment]
I totally missed https://buildpacks.io/docs/reference/pack/, and I really searched multiple times.

I wonder if it's just me or a more generalized discovery issue.

Here are a few suggestions which might help:

* Link to the reference from https://github.com/buildpacks/pack
* https://buildpacks.io/docs/reference/pack/ could display an index of the sub pages. It is the pageyou get to when you click "Pack CLI". It also not obvious that sub-pages are now displayed in the left nav.
* Link to the reference from a few relevant places in the rest of the doc.
* Ensure that the reference has the appropriate keywords, notably, consider using "Command Line" instead of CLI.

**Comment by dfreilich** [comment]
@steren That's really fantastic feedback, thanks. I'll open some PRs now to incorporate that!
