### ISSUE TITLE
Extract internal archive package into a public package

### ISSUE THREAD

**Issue by tcdowney** [buildpacks/pack#814]
### Description
The archive package contains a zip to tar conversion utility that is useful outside of the `pack` CLI itself. We have a use case where we would like to convert user-submitted `zip` files containing app source code into `.tar` files so that we can construct single-layer OCI images.

The `pack` CLI is battle-tested and includes logic for handling a wide-variety of zip files (e.g. those created on Windows machines, `FAT` filesystems, files with strange permissions, etc.) so we would like to build upon this rather than reinvent the wheel. 🎡 🌝 

### Proposed solution
The code within [`internal/archive`](https://github.com/buildpacks/pack/tree/10f5f0a357ccc0b8cc4cabf7ee9a70814386f0cd/internal/archive) is part of a public package that others can consume.

### Additional context
If you're curious, currently we're vendoring in these files wholesale into our repo [here](https://github.com/cloudfoundry/capi-k8s-release/tree/07eb5c8a2205253257681c8060b67e122cb5c77c/src/package-image-uploader/archive). This works right now (especially after https://github.com/buildpacks/pack/issues/813 adds copyright info to the license), but it would be much more convenient if we could just import these packages. That way we could easily keep up as you improve the code, too! 😁 

Thanks!

Tim && @piyalibanerjee

**Comment by dfreilich** [comment]
Happy to hear that the code is being consumed!

**Comment by dfreilich** [comment]
Once consideration when we make it public - we should probably beef up the test coverage. Currently the folder coverage is 48%, which definitely should be increased anyways, but especially if we make it a publicly consumable API. 

![image](https://user-images.githubusercontent.com/7035673/92084155-a3c79280-edcf-11ea-9ee1-b70517dccbeb.png)

ref: https://codecov.io/gh/buildpacks/pack/tree/master/internal/archive

**Comment by dfreilich** [comment]
@tcdowney There's an internal discussion to perhaps move this to https://github.com/buildpacks/imgutil, instead of releasing it as part of the pack external api (it doesn't seem super related to the general pack API). We should have more clarity on that over the next few days, once we finish preparations for the upcoming pack release.

**Comment by jromero** [comment]
Reopened since #943 doesn't actually resolve this issue but instead prepares the code for moving to imgutil.
