### ISSUE TITLE
Chocolatey pack version still at 0.12.0

### ISSUE THREAD

**Issue by micahyoung** [buildpacks/pack#817]
### Summary
Release notes for 0.13.1 suggest latest pack is available with `choco install pack`. When that is run, I get version 0.12.0

Currently, Chocolatey.org site still shows 0.12.0 as well: https://chocolatey.org/packages/pack

---

### Reproduction
```powershell
PS > choco install pack

Chocolatey v0.10.15
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

Installing the following packages:
pack
By installing you accept licenses for the packages.
Progress: Downloading pack 0.12.0... 100%

pack v0.12.0 [Approved]
pack package files install completed. Performing other installation steps.
 ShimGen has successfully created a shim for pack.exe
 The install of pack was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

##### Current behavior
Pack version 0.12.1

##### Expected behavior
Pack version 0.13.1

---

### Environment
Windows 10 Enterprise 1809
Chocolatey v0.10.15
Powershell

**Comment by dfreilich** [comment]
It looks like pack `v0.13.1` is currently up on choco. In general, once we push a version you can install it manually (e.g `choco install pack --version=0.13.1`, like we have in the docs), even if it's not listed as the updated version yet in the choco package site
