### ISSUE TITLE
Add a buildpack scaffold command

### ISSUE THREAD

**Issue by josegonzalez** [buildpacks/pack#82]
It would be great to be able to run:

```
# where `$DIR` is a directory path
pack buildpack-scaffold $DIR
```

And have it build out the entire necessary buildpack structure. That would allow people to much more quickly go through the buildpack tutorial, but also make it easy for people to experiment with v3 buildpacks.

**Comment by josegonzalez** [comment]
Just something that touches the files as shell scripts - maybe with a note saying they can be executable - and chowning them?

**Comment by ekcasey** [comment]
Would it be better to create a scaffold that uses https://github.com/buildpack/libbuildpack? It's not mandatory to use `libbuildpack` of course but it does provide a nice buildpack developer experience.

**Comment by nebhale** [comment]
@ekcasey Then you are being prescriptive in choosing Go as your implementation language.  This is why I'm not keen on this feature.  You're either going to push people towards a language where scaffolding is required, or you're going to end up creating two `bash` files in a `bin/` directory that each have only a line or two in them.  The flexibility of the Cloud Native Buildpack design (e.g. any language you want) sort of means that an opinionated scaffolding isn't appropriate.

**Comment by josegonzalez** [comment]
@nebhale I realize we don't want to "prescribe" a specific language, but this just makes it easy to demo pack to new users. Thats really what I'm targeting. Shell is the lingua franca, so just having an example shell script that does the simplest thing possible would be enough to demo the basics, but also allow developers to do more.

FWIW, @jkutner mentioned wanting to build just that for his talk [here](https://buildpacks.slack.com/archives/CD61YAG69/p1544654455030500), and @sclevine mentioned that CF has a similar tool.

**Comment by zmackie** [comment]
What if we just had it inject https://github.com/buildpacks/samples/tree/master/buildpacks/hello-world

**Comment by jromero** [comment]
I'd like to see something more robust to be honest. I'm a fan of user friendly scaffolding experience that tools like:

- [cookie-cutter](https://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/cookiecutters.html) 
- [open-faas](https://www.openfaas.com/blog/template-store/#building-the-template-store)

**Comment by zmackie** [comment]
@buildpacks/platform-maintainers Is this something we want to do?

**Comment by dfreilich** [comment]
This seems like it's been a long-ranging discussion, but we do have our samples repo now. Feel free to reopen it if it's still a concern, but it doesn't seem like it's highest on our priority queue...
