### ISSUE TITLE
failed to connect to docker socket: dial unix /var/run/docker.sock: connect: connection refused when trying to build java sample on Ubuntu running on WSL2/Docker Desktop for WSL2

### ISSUE THREAD

**Issue by matveym** [buildpacks/pack#827]
### Summary

When trying to go through https://buildpacks.io/docs/app-journey/ I get an error when building the app using command:
`pack build myapp --builder cnbs/sample-builder:bionic`

I am using Ubuntu running inside WSL 2 with docker available via Docker Desktop for WSL 2.
docker run hello-world works fine.
---

##### Steps

1. Install pack on Ubuntu under WSL 2.
2. Make sure that Ubuntu has version 2 of the WSL:
$ wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
3. Integrate Docker with Ubuntu via Docker Desktop configs (https://docs.docker.com/docker-for-windows/wsl/)
4. Go thru the tutorial steps, should fail on "Next stop, the end"

##### Current behavior
mmaslov@MY-LAPTOP:~/samples/apps/java-maven$ pack build myapp --builder cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-builder
Digest: sha256:83bae557006fd8e70d5ecdbae1d06a025d5769e6a50314e43e43f97e4e63b5ac
Status: Image is up to date for cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-stack-run
Digest: sha256:95d2e14a6ba940553ec1cd697c8701b6f047621b02b2f6dfea24f10640a694c4
Status: Image is up to date for cnbs/sample-stack-run:bionic
0.9.1: Pulling from buildpacksio/lifecycle
Digest: sha256:53bf0e18a734e0c4071aa39b950ed8841f82936e53fb2a0df56c6aa07f9c5023
Status: Image is up to date for buildpacksio/lifecycle:0.9.1
===> DETECTING
[detector] samples/java-maven 0.0.1
===> ANALYZING
[analyzer] ERROR: failed to initialize docker client: failed to connect to docker socket: dial unix /var/run/docker.sock: connect: connection refused
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 1

##### Expected behavior
Build passes
---

##### pack info
Pack:
  Version:  0.13.1+git-4134cc6.build-1135
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.9.1

Config:
(no config file found at /home/mmaslov/.pack/config.toml)

##### docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: docker-desktop
 ID: KQXB:UTFD:UGPF:JEMP:G53D:UENB:3HSO:6ZC4:4RX3:AU54:YHDL:UKTS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-08-31T14:46:54.6449087Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by jromero** [comment]
Trying to formulate a mental model of how this setup is currently running.

Typically, you would have docker installed on your Windows OS (with WSL backend) and run `pack` or `docker` from Windows powershell/cmd. It looks like you are attempting to run `pack` from within the Ubuntu WSL.

Can you run the following commands?

1. `docker info` from powershell or cmd on Windows
2. `docker info` from inside the Ubuntu WSL

**Comment by jromero** [comment]
This issue seems related: https://github.com/docker/for-win/issues/5096

**Comment by matveym** [comment]
Seems `docker info` are the same from cmd and WSL.

`docker info` from cmd
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: docker-desktop
 ID: KQXB:UTFD:UGPF:JEMP:G53D:UENB:3HSO:6ZC4:4RX3:AU54:YHDL:UKTS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-08-31T15:02:48.2278504Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
--
`docker info` from WSL (same as above)
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: docker-desktop
 ID: KQXB:UTFD:UGPF:JEMP:G53D:UENB:3HSO:6ZC4:4RX3:AU54:YHDL:UKTS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-08-31T15:02:48.2278504Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by matveym** [comment]
Does not look like https://github.com/docker/for-win/issues/5096. Docker seems working. Even /var/run/docker.sock is accessible:
`curl -XPOST --unix-socket /var/run/docker.sock -d '{"Image":"hello-world"}' -H 'Content-Type: application/json' http://localhost/contai
ners/create
{"Id":"e3990a48c7bfdadfcd315b2b5a9ba38be1dae9b819695c0132b6a84879e7df7a","Warnings":[]}`
{"message":"No such image: nginx:latest"}

**Comment by jromero** [comment]
Interesting, we can get a system setup to try to repro. In the meantime, could you check what `getenforce` yields and if "enforcing" could you try disabling it?

**Comment by matveym** [comment]
$ getenforce
Disabled

**Comment by jromero** [comment]
I'm not able to reproduce the error. Notice that I am using a beta version of Docker Desktop. I'm also curious to know what version of Ubuntu you are running. The setup I have is 18.04.

## Configuration

### Docker Desktop

![Docker_Desktop_1LZo5ge8kU](https://user-images.githubusercontent.com/475559/91899308-8f19bc00-ec62-11ea-8afb-37aeafd41a2e.png)

### `docker info`

```text
Client:                                                                                                                      
 Debug Mode: false                                                                                                           
 Plugins:                                                                                                                    
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)                                                                
  ecs: Docker ECS (Docker Inc., v1.0.0-beta.5)                                                                               
  app: Docker Application (Docker Inc., v0.8.0)                                                                              
                                                                                                                             
Server:                                                                                                                      
 Containers: 5                                                                                                               
  Running: 0                                                                                                                 
  Paused: 0                                                                                                                  
  Stopped: 5                                                                                                                 
 Images: 9                                                                                                                   
 Server Version: 19.03.13-beta2                                                                                              
 Storage Driver: overlay2                                                                                                    
  Backing Filesystem: extfs                                                                                                  
  Supports d_type: true                                                                                                      
  Native Overlay Diff: true                                                                                                  
 Logging Driver: json-file                                                                                                   
 Cgroup Driver: cgroupfs                                                                                                     
 Plugins:                                                                                                                    
  Volume: local                                                                                                              
  Network: bridge host ipvlan macvlan null overlay                                                                           
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog                                        
 Swarm: inactive                                                                                                             
 Runtimes: runc                                                                                                              
 Default Runtime: runc                                                                                                       
 Init Binary: docker-init                                                                                                    
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429                                                                
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd                                                                      
 init version: fec3683                                                                                                       
 Security Options:                                                                                                           
  seccomp                                                                                                                    
   Profile: default                                                                                                          
 Kernel Version: 4.19.104-microsoft-standard                                                                                 
 Operating System: Docker Desktop                                                                                            
 OSType: linux                                                                                                               
 Architecture: x86_64                                                                                                        
 CPUs: 12                                                                                                                    
 Total Memory: 7.772GiB                                                                                                      
 Name: docker-desktop                                                                                                        
 ID: YXJK:ZKAH:TK3D:MY53:EFPL:SEOR:L4XY:S46M:XMBE:J6RS:EWKX:3UV6                                                             
 Docker Root Dir: /var/lib/docker                                                                                            
 Debug Mode: true                                                                                                            
  File Descriptors: 46                                                                                                       
  Goroutines: 55                                                                                                             
  System Time: 2020-09-01T19:52:13.9714961Z                                                                                  
  EventsListeners: 5                                                                                                         
 Registry: https://index.docker.io/v1/                                                                                       
 Labels:                                                                                                                     
 Experimental: true                                                                                                          
 Insecure Registries:                                                                                                        
  127.0.0.0/8                                                                                                                
 Live Restore Enabled: false                                                                                                 
 Product License: Community Engine                                                                                           
                                                                                                                             
WARNING: bridge-nf-call-iptables is disabled                                                                                 
WARNING: bridge-nf-call-ip6tables is disabled                                                                                
```

### `wsl --list --verbose`

```
C:\Users\jrome\workspace\buildpacks\samples\apps>wsl --list --verbose 
  NAME                   STATE           VERSION                      
* Ubuntu-18.04           Running         2                            
  docker-desktop-data    Running         2                            
  docker-desktop         Running         2                            
```

### `pack build`

```
jromero@LAPTOP-LPRQFMHE:/mnt/c/Users/jrome/workspace/buildpacks/samples$ pack build my-java-app -B cnbs/sample-builder:bionic -p apps/java-maven/

bionic: Pulling from cnbs/sample-builder
Digest: sha256:83bae557006fd8e70d5ecdbae1d06a025d5769e6a50314e43e43f97e4e63b5ac
Status: Image is up to date for cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-stack-run
Digest: sha256:95d2e14a6ba940553ec1cd697c8701b6f047621b02b2f6dfea24f10640a694c4
Status: Image is up to date for cnbs/sample-stack-run:bionic
0.9.1: Pulling from buildpacksio/lifecycle
Digest: sha256:53bf0e18a734e0c4071aa39b950ed8841f82936e53fb2a0df56c6aa07f9c5023
Status: Image is up to date for buildpacksio/lifecycle:0.9.1
===> DETECTING
[detector] samples/java-maven 0.0.1
===> ANALYZING
[analyzer] Previous image with name "index.docker.io/library/my-java-app2:latest" not found
===> RESTORING
===> BUILDING
[builder] ---> Java buildpack
[builder] ---> Installing JDK
[builder] [INFO] ------------------------------------------------------------------------
[builder] [INFO] BUILD SUCCESS
[builder] [INFO] ------------------------------------------------------------------------
[builder] [INFO] Total time:  29.139 s
[builder] [INFO] Finished at: 2020-09-01T19:55:55Z
[builder] [INFO] ------------------------------------------------------------------------
....
===> EXPORTING
[exporter] Adding layer 'samples/java-maven:jdk'
[exporter] Adding 1/1 app layer(s)
[exporter] Adding layer 'launcher'
[exporter] Adding layer 'config'
[exporter] Adding layer 'process-types'
[exporter] Adding label 'io.buildpacks.lifecycle.metadata'
[exporter] Adding label 'io.buildpacks.build.metadata'
[exporter] Adding label 'io.buildpacks.project.metadata'
[exporter] Setting default process type 'web'
[exporter] *** Images (88a96e750b78):
[exporter]       index.docker.io/library/my-java-app:latest
[exporter] Adding cache layer 'samples/java-maven:jdk'
[exporter] Adding cache layer 'samples/java-maven:maven_m2'
Successfully built image my-java-app
```

**Comment by jromero** [comment]
Let's try the following:

We'll look to ensure that the sock file exists:

1. **In WSL**:
    ```bash
    jromero@LAPTOP-LPRQFMHE:/mnt/c/Users/jrome/workspace/buildpacks/samples$ ls -al /var/run/docker.sock
    srw-rw---- 1 root docker 0 Sep  1 16:13 /var/run/docker.sock
    ````

Next, we can try writing to the socket from within the container:

1. **In WSL**, run this command (notice `--user=root` and a different builder (that has `curl`)):
    ```
    docker run -it --rm --user=root --volume=/var/run/docker.sock:/var/run/docker.sock paketobuildpacks/builder:base /bin/bash
    ```
2.  **In the container**, look at the sock file to make sure it's there and permissions are appropriate. 
    ```
    ls -al /var/run/docker.sock
    ```
3. **In the container**, try to write to the socket (as you made mention here):
    ```
    curl -v --unix-socket /var/run/docker.sock -d '{"Image":"hello-world"}' -H 'Content-Type: application/json' http://localhost/containers/create
    ```

It should yield the following:

```text
root@6994db6467f3:/layers# curl -v --unix-socket /var/run/docker.sock -d '{"Image":"hello-world"}' -H 'Content-Type: application/json' http://localhost/containers/create
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> POST /containers/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 23
>
* upload completely sent off: 23 out of 23 bytes
< HTTP/1.1 404 Not Found
< Api-Version: 1.40
< Content-Type: application/json
< Date: Tue, 01 Sep 2020 21:26:46 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/19.03.13-beta2 (linux)
< Transfer-Encoding: chunked
<
{"message":"No such image: hello-world:latest"}
* Connection #0 to host localhost left intact
```

**Comment by matveym** [comment]
```
mmaslov@MMASLOV-LAPTOP:~/samples$` ls -al /var/run/docker.sock
srw-rw---- 1 root docker 0 Aug 31 17:33 /var/run/docker.sock
mmaslov@MMASLOV-LAPTOP:~/samples$ docker run -it --rm --user=root --volume=/var/run/docker.sock:/var/run/docker.sock paketobuildpacks/builder:base /bin/bash
root@5632af34d9b4:/layers# ls -al /var/run/docker.sock
srw-rw---- 1 root 1001 0 Aug 31 14:33 /var/run/docker.sock
root@5632af34d9b4:/layers# curl -v --unix-socket /var/run/docker.sock -d '{"Image":"hello-world"}' -H 'Content-Type: application/json' http://localhost/containers/create
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> POST /containers/create HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 23
>
* upload completely sent off: 23 out of 23 bytes
< HTTP/1.1 201 Created
< Api-Version: 1.40
< Content-Length: 88
< Content-Type: application/json
< Date: Thu, 03 Sep 2020 09:19:25 GMT
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/19.03.12 (linux)
<
{"Id":"ed9e5984c892a4249b8bfd0bbd6d135e30a0ed0b73f1780486f1bd240a5726b0","Warnings":[]}
* Connection #0 to host localhost left intact
```

**Comment by matveym** [comment]
You have a newer version of Docker Desktop: Docker/19.03.13-beta2 (you) vs Docker/19.03.12 (me).

**Comment by matveym** [comment]
```
$ lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Comment by matveym** [comment]
Works for me on Docker/19.03.13-beta2 :)

**Comment by matveym** [comment]
I guess we can close this issue, right?

**Comment by jromero** [comment]
Great! It's unfortunate that it's still in beta but 🤞 that a stable version comes soon.

Thank you for the follow up.

**Comment by souhailSQLi** [comment]
Hello everyone 👋🏽👋🏽

In my case I'm using docker cli in WSL2 on Windows 10 (Ubuntu 22.04) (**Not Docker Desktop**)

I fixed this issue by adding `unix:///var/run/docker.sock` to the hosts array in `/etc/docker/daemon.json`:
![image](https://github.com/buildpacks/pack/assets/120159876/8ef51d85-e74a-4e82-8fb2-b22b8c4de051)

**NB:** I used this [ tutorial](https://dataedo.com/docs/installing-docker-on-windows-via-wsl) to install docker cli, and mid step 5 describes how and where to add the hosts array
