### ISSUE TITLE
Provide debug output of env vars used during build

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#836]
As a builder or platform author, I'd like to know what env vars are being used during the build process. This entails known what env vars are passed on to the container as well as what env vars are placed in `/platform/env`.

> Provide debug output of env vars passed to container + env vars in `/platform/env` (deferred)

_Originally posted by @jromero in https://github.com/buildpacks/pack/issues/335#issuecomment-693526802_

**Comment by Clivern** [comment]
I wanna pick this up, @jromero if u have something in mind, please let me know otherwise i will check/open a PR

**Comment by jromero** [comment]
@Clivern all yours! Thank you. Please reach out if you have any questions. 

_Note: We recently enabled [discussions](https://github.com/buildpacks/community/discussions) as another form of communication._
