### ISSUE TITLE
Add default official registry

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#842]
> With regards to always having a "official" registry, I would have to double check or maybe @jkutner knows off the top of his head. However, we don't have complete control over this file, so if the user wanted to they could intentionally (or accidentally) delete it. If this were the case what's the expected behavior? Should we automatically re-create the official registry and always display it at a minimum?

I believe a strategy that _may_ work is to hardcode it in memory instead of appending it to the config file. A similar example of this would be trusted-builders in which case we list trusted-builders as "user-defined trusted builder" (from config.toml) + "suggested builders" (from hard coded values).

_Originally posted by @jromero in https://github.com/buildpacks/pack/pull/839#discussion_r492211992_

**Comment by dfreilich** [comment]
My understanding was like yours, @jromero, in that there was going to be a default official registry, but I could be totally off on that. Regardless, I think it's a good feature to initialize pack with, so that the registry flow can work out of the box.

**Comment by elbandito** [comment]
I think this seem like a reasonable pattern.  :+1:

**Comment by jkutner** [comment]
Yes, there should be an official registry, and it should be the default in the code (not the pack config file). In that way, deleting the config file will not delete the official/default registry.
