### ISSUE TITLE
Publish with multiple tags

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#844]
### Description

I'd like to publish an image with pack, with multiple tags. For instance, `dfreilich/pack:latest` and `dfreilich/pack:v0.0.15`. 

### Proposed solution

Add a flag `--tag` to allow for inputting multiple tags. This should work in cases where we call the creator, and can pass in the `-tag` flag. https://github.com/buildpacks/spec/blob/main/platform.md#creator

### Additional context
- [x] This feature should be documented somewhere

**Comment by ekcasey** [comment]
> This should work in cases where we call the creator, and can pass in the -tag flag

This should also work with untrusted builders, as `exporter` can accept multiple tags as positional arguments.
