### ISSUE TITLE
Create AUR package

### ISSUE THREAD

**Issue by bouk** [buildpacks/pack#85]
It would be nice if this project were to be submitted to the [AUR](https://aur.archlinux.org/) so it's easy to install for Arch Linux users. I've created a sample PKGBUILD for version 0.0.8 that installs the binary

```
pkgname=pack 
pkgdesc="Buildpack CLI"
pkgver=0.0.8
pkgrel=1
arch=('x86_64')
url="https://buildpacks.io/"
license=('apache')
source_x86_64=("https://github.com/buildpack/pack/releases/download/v$pkgver/pack-$pkgver-linux.tar.gz")
sha256sums_x86_64=('df381e3d9c922dfbd5530f425675728f8cbecdd571f59315887eb50c6d573e7c')

package() {
  install -Dm 755 "$srcdir/pack" "$pkgdir/usr/bin/pack"
}
```

**Comment by ttpcodes** [comment]
Hi, I have an `AUR` package maintained for this located [here](https://aur.archlinux.org/packages/pack-cli/). Rather than downloading the binary, this `AUR` script is set to build the latest release from source.

Please let me know if there are any glaring issues. I'm relatively new to `AUR` packaging still and would love to get feedback on improving the packaging.

**Comment by Zanadar** [comment]
@ttpcodes This is awesome. Thanks for putting that together. Is there some way to keep it up to date as new releases are cut? Looks like the `AUR` is a bit out of date.

**Comment by natalieparellano** [comment]
We brought this up in the latest WG meeting and decided this is something that we'd like to do eventually.

@ttpcodes could we work with you on this? We'd like to be able to use the `pack-cli` namespace if possible.

**Comment by ttpcodes** [comment]
I'd be willing to help with this. What resources would you need from me?

You can contact me via my email address on my profile if you want to discuss this over email.

**Comment by jromero** [comment]
This is now done. Many thanks for @ttpcodes! 

See [releases](https://github.com/buildpacks/pack/releases) for details.
