### ISSUE TITLE
[Java] Wrong log of builder

### ISSUE THREAD

**Issue by liangyuanpeng** [buildpacks/pack#865]
![image](https://user-images.githubusercontent.com/28711504/94779261-3bcd9180-03f9-11eb-9277-c96d2800dfe4.png)

# Reproduce:  
```
cd samples  

pack build -p apps/java-maven --builder cnbs/sample-builder:bionic sample-app  
```

#  other  

OS: Mac 
Pack version:  master (From make build)

**Comment by jromero** [comment]
@micahyoung, an FYI that this exists and might require more thought since `PrefixWriter#Write` could be getting called mid-line. :/ My solution wouldn't address this.

**Comment by jromero** [comment]
@micahyoung, I just tried this out on the Java sample app as reported by @liangyuanpeng and it's still well beyond broken with the latest changes. We might need to revert the original change until we can apply a better logging solution at the same time. I will make a few attempts tonight and keep this thread up-to-date.

**Comment by jromero** [comment]
I was able to get a fix in. Hoping for it to be released tomorrow.

@liangyuanpeng It would be great if you could verify that the fix (merged to the `main` branch) works specifically for you.

**Comment by liangyuanpeng** [comment]
@jromero  Cool , It's working now.  Actually I started from the main branch, not master. 👍  I didn't notice the default branch changed.
