### ISSUE TITLE
Add manual execution capability to Arch Linux pack-cli delivery pipeline

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#875]
### Description
As part of https://github.com/buildpacks/pack/pull/874, we added manual execution capabilities for **`pack-cli-bin`**. We should also enable it for the **`pack-cli`** job.

### Proposed solution

For `pack-cli`, we should seperate the workflow source from the pack source in the pipeline similar to delivery-docker. This needs to be done so that we can update the release workflow and be able to checkout the source code for pack at any given tag. As an example, we do this for [`delivery/docker`](https://github.com/buildpacks/pack/blob/main/.github/workflows/delivery-docker.yml#L39-L42)

**Comment by dfreilich** [comment]
Should this be expanded to all of our delivery pipelines? With #927, we have `workflow_dispatch` support in:
- `chocolatey`
- `docker`
- `archlinux (pack-cli-bin)`
- `ubuntu PPA`

but we don't have for `homebrew`. 

Also, it seems to me that we have manual execution capabilities for both `pack-cli-bin` and `pack-cli`, but not for `pack-cli-git`; am I wrong in that?

**Comment by dfreilich** [comment]
Ah never mind, I see that `if: github.event_name == 'release'` gates `pack-cli` now.

**Comment by jromero** [comment]
Closed by #936
