### ISSUE TITLE
pack v0.14.1: logger causing runtime error

### ISSUE THREAD

**Issue by arjun024** [buildpacks/pack#890]
Looks like v0.14.1 hits a runtime error on doing a `pack build` printing the log into github actions, when used with certain buildpacks.

```
[builder] Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.3.0.RELEASE/spring-boot-starter-parent-2.3.0.RELEASE.pom
panic: runtime error: index out of range [-1]

goroutine 102 [running]:
github.com/buildpacks/pack/logging.(*PrefixWriter).Write(0xc000239a10, 0xc000402008, 0x1, 0x8001, 0x9, 0x0, 0x0)
	/workspace/logging/prefix_writer.go:34 +0x445
github.com/docker/docker/pkg/stdcopy.StdCopy(0x55fae7788e40, 0xc000239a10, 0x55fae7788e40, 0xc000239a70, 0x55fae7788820, 0xc0000acb40, 0x0, 0x0, 0x0)
	/workspace/vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go:174 +0x472
github.com/buildpacks/pack/internal/container.Run.func1(0x55fae7788e40, 0xc000239a10, 0x55fae7788e40, 0xc000239a70, 0xc0004c3140, 0xc000514900)
	/workspace/internal/container/run.go:34 +0xa8
created by github.com/buildpacks/pack/internal/container.Run
	/workspace/internal/container/run.go:33 +0x2d0
Error: Process completed with exit code 2.
```

Looks like an illegal access [here](https://github.com/buildpacks/pack/blob/v0.14.1/logging/prefix_writer.go#L34)

**To reproduce**
Run the equivalent of the following in a github workflow:
```
curl -LO https://raw.githubusercontent.com/paketo-buildpacks/full-builder/366ac3c223f02a964000f2162e9b5ce277d3532a/builder.toml
pack create-builder testbuilder --config builder.toml
git clone git@github.com:paketo-buildpacks/samples.git
pack build testapp -p samples/java/maven --builder testbuilder
```
E.g. https://github.com/paketo-buildpacks/full-builder/runs/1226199877?check_suite_focus=true#step:5:596

**Versions**
* Works fine with pack v0.14.0
* Runtime error with pack v0.14.1

**Comment by jromero** [comment]
Thanks for the report @arjun024. This one is rather embarrassing to me personally. 🤦  (I ran with an assumption rather than doing a simple check.) 

We'll try to get a patch out there soon.

**Comment by jromero** [comment]
Update: so I discovered that the solution is not as simple are a length check. 

The root cause is a single `CR` (carriage return) used for progress updates from Maven.

Although a length check would resolve pack from crashing, the logs are still somewhat unreadable due to maven not picking up on "non-interactiveness". As a workaround for this particular case the following command works are expected:

```
pack build testapp -p samples/java/maven --builder testbuilder -e BP_MAVEN_BUILD_ARGUMENTS="-B -Dmaven.test.skip=true package"
```

Notice the added `-B` for `--batch-mode` (aka non-interactiveness)

**Comment by jromero** [comment]
CC: @micahyoung, another caveat of ContainerLogs versus ContainerAttached. :(

**Comment by micahyoung** [comment]
Ugh. What a hassle. I'm happy to revert that if it makes more sense. I could attempt another workaround the `ContainerLogs` issue for Windows, especially understanding more about how Logs work now.

**Comment by arjun024** [comment]
Thanks for the quick response
