### ISSUE TITLE
Configurable Previous Image

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#897]
### Description
`pack build` should accept am optional `--previous-image` flag that allows users to set the previous image to a particular tag reference, digest reference, or (when performing a daemon build) image ID.

This is useful If I want to rebuild from a particular previous version of my app. Currently I would need to tag the previous image with the tag to which I want to export to force this behavior. This is an extra and potentially undesirable step.

### Proposed solution
 Usage: `pack build --previous-image <prev-image> <image>`

#### Lifecycle Arguments
When the builder is trusted, `pack` should invoke `creator` with the `-previous-image` flag or `CNB_PREVIOUS_IMAGE` env var.
```
creator -previous-image <prev-image> <image>
```
When the builder is not truster, `pack` should pass the previous image to `analyzer`
```
analyzer <prev-image>
```
#### Edge Cases
When `pack build` is called with `--publish`, `<prev-image>` must be in the same image registry as `<image>` (`exporter` currently does not support previous images in a different registry).

Until we have a better solution for managing caches volumes this feature will only be useful for reusing `launch = true`, `cache = false` layers, because the previous cache is not necessarily provided.

### Additional context
- [ ] This feature should be documented somewhere

**Comment by micahyoung** [comment]
This feels a bit like `docker build`'s [`--cache-from`](https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources) option, which really speeds up rebuilding Windows images.

**Comment by samj1912** [comment]
does `pack build --cache-image` implement the required functionality for this? In which case should this be closed?

**Comment by ekcasey** [comment]
@samj1912 some layer metadata comes from the previous app image, rather than from the cache image.

How these options interact might be a bit confusing for users but I think it is worth exposing this useful knobs now (maybe as an experimental feature?), and we can brainstorm a more cohesive UX for future iterations.

**Comment by importhuman** [comment]
Hello! I'd like to work on this. Can you give me some pointers as to where I should start? I know some Go, and the basics of Docker and how to use the pack CLI.

**Comment by jromero** [comment]
Hi @importhuman, very excited to hear that this is something you are interested in contributing.

Here are a few steps I can think off:

Prerequisites:
1. Read our DEVELOPMENT.md document and install all the [prerequisites](https://github.com/buildpacks/pack/blob/main/DEVELOPMENT.md#prerequisites).
1. Make sure you can run `make test` and all tests pass.

Development:
1. Create a **unit test** for `analyze` phase [within here](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/internal/build/lifecycle_execution_test.go#L869).
1. Implement changes for `analyze` phase [here](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/internal/build/lifecycle_execution.go#L300).
1. Follow steps 1-2 for `create` (aka `creator`) [[tests](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/internal/build/lifecycle_execution_test.go#L281) and [implementation](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/internal/build/lifecycle_execution.go#L176)].
1.  Add new flag `previous-image` [here](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/internal/commands/build.go#L167).
1. Create a set of **unit tests** similar to [`cache-image`](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/internal/commands/build_test.go#L330) with requirements detailed in issue description.
1. Create an **acceptance test** similar to [`cache-image`](https://github.com/buildpacks/pack/blob/7a08937e10c079c449e9d8e1a956509fef459b45/acceptance/acceptance_test.go#L1728).

Hope this helps. If you run into any issues along the way feel free to reach out either here or in [slack](https://slack.buildpacks.io).
