### ISSUE TITLE
[Investigation] Use HEAD request to determine if the digest had changed

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#899]
### Description

Currently, when we `pack build`, we attempt to pull some images (eg, we check whether there is a new version of your builder) over [here](https://github.com/buildpacks/pack/blob/main/internal/image/fetcher.go#L94). With DockerHub rate limits, that can be an issue. 

### Proposed solution

First use a HEAD request (perhaps using [go-containerregistry](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/remote#Head) `remote.Head`) to check whether the digest has changed, and only pull if it has. 

### Additional context

Slack discussion [here](https://buildpacks.slack.com/archives/C94UJCNV6/p1602856355153200)

**Comment by jromero** [comment]
Relevant code: 
 - pack: https://github.com/buildpacks/pack/blob/main/internal/image/fetcher.go#L60-L68
 - imgutil: https://github.com/buildpacks/imgutil/blob/main/remote/remote.go#L195-L202

**Comment by ImJasonH** [comment]
It looks like pack's fetcher.go uses `github.com/docker/docker/client`, which I believe, being maintained by Docker, would already do the right thing and avoid unnecessarily-counted pulls if it can determine it can do so.

That leaves remote's Image.Found which pack calls before `pullImage`, which can be fixed to use `remote.Head` instead. Let me know if there's about this code path that I might be missing.

**Comment by jromero** [comment]
@ImJasonH, got your imgutil feature incorporated in #908. 

Based on your statement this is resolved. It's more that it delegates the lookup to the docker daemon that then should already do the right thing. Tomatoes potatoes.
