### ISSUE TITLE
codecov is not uploading Windows report

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#906]
### Description

We are no longer getting codecov reports on PRs. A cursory looks shows that Window uploads are missing.

See an example of lack of Window uploads here: https://codecov.io/gh/buildpacks/pack/commit/096088d2ccc16471e4dc508f6ff90d6023be2a8c/build

And the following error message here:  https://github.com/buildpacks/pack/runs/1283513426?check_suite_focus=true

```
==> Uploading to Codecov
Warning: Couldn't read data from file "/tmp/codecov.afKFpj.gz", this makes an 
Warning: empty POST.
```

**Comment by dfreilich** [comment]
I'm not sure whether macos is working appropriately either – Seems like there's also an issue with `macos`, at least as shown here: https://github.com/buildpacks/pack/pull/935/checks?check_run_id=1355960584, though it's a different error, and showed something as being uploaded.
