### ISSUE TITLE
Cross-compile binary for ARMv7 and ARM 64

### ISSUE THREAD

**Issue by yankeexe** [buildpacks/pack#907]
### Description

Current binary distribution for `pack` only supports `amd64` . Adding binaries for ARM will enable `pack` to be used on Raspberry Pi and similar hardware.

### Proposed solution

Cross-compile binaries for `ARM v7` and `ARM 64`

### Additional context
- [ ] This feature should be documented somewhere

**Comment by alexellis** [comment]
Thank you @jromero 👍 👍

**Comment by dfreilich** [comment]
@yankeexe @alexellis I was just looking into doing this! I'm pretty unfamiliar with the arm64/armv7 ecosystem, so two questions: 
1. Can we assume that testing with the normal linux github action runner (`ubuntu-18.04`) will give sufficient coverage for linux systems, or should we test it on those architectures as well? (I'm assuming we should test it, and I've opened https://github.com/buildpacks/ci/issues/23 as a result, but if that's not the case, great!)
1. Is the ask to just publish in our release, or to publish to a package manager? 

Again, I don't know the ecosystem at all, so I'm sorry if these are super basic questions!

**Comment by dfreilich** [comment]
I'm assuming that this is blocked at the moment on https://github.com/buildpacks/lifecycle/issues/435. When we tried running an `arm64` compiled `pack` with an extant builder, we saw:
```
pack build -B gcr.io/buildpacks/builder:v1 ${IMAGE}
v1: Pulling from buildpacks/builder
Digest: sha256:889d1cc172467dfb5560c69e5a24d8215804e0fb9ae36e2774f33bc2033ffb8c
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:35c7b9995b7b0ad398e504bc178e38b28626e1ce9052cfeabc8750fc313b4d36
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
standard_init_linux.go:190: exec user process caused "exec format error"
ERROR: failed to build: executing lifecycle: failed with status code: 1
```

**Comment by briandealwis** [comment]
@dfreilich that specific error is related but different from https://github.com/buildpacks/lifecycle/issues/435: `gcr.io/buildpacks/builder:v1` is `linux/amd64`-only.  Your build should work if you have `binfmt_exec` extensions configured, though it will produce a `linux/amd64` image.

**Comment by jromero** [comment]
If I'm not mistaken this issue is now completely resolved provided all referenced issues are resolved. If that is wrong, please feel free to re-open with more detail on what's missing.

**Comment by josegonzalez** [comment]
Is this "just"

- adding a new entry to the build matrix: https://github.com/buildpacks/pack/blob/main/.github/workflows/build.yml#L137
- add a stanza like this for linux-arm: https://github.com/buildpacks/pack/blob/main/.github/workflows/build.yml#L191

Or is there something I'm missing?

**Comment by willianpaixao** [comment]
@josegonzalez I took the freedom and went ahead to test your assumption. #1401
