### ISSUE TITLE
Specify Build Command

### ISSUE THREAD

**Issue by JakeCooper** [buildpacks/pack#912]
### Description
Is there, or should there be a way, to specify a dependency, or some sort of command to setup a dependency, as part of the build process?

### Proposed solution
Would be really great to have a pack.sh or something that ran on build to fetch a dependency (e.g let's say I needed jq or something inside the container)

### Describe alternatives you've considered
N/A

### Additional context
- [x] This feature should be documented somewhere

**Comment by jromero** [comment]
Hi @JakeCooper,

I'm not sure I understand the issue. Could you elaborate a little? What problems specifically are you facing? 

From the phrases "build process", "on the build", and "inside the container", I feel like this may be more related to the [builder](https://buildpacks.io/docs/concepts/components/builder/) you are using. If so, what builder are you using?

**Comment by JakeCooper** [comment]
I'd like to be able to specify some dependency that's also loaded by the buildpack.

E.g let's assume yarn isn't provided by the buildpack for nodejs. I'd like some way to define that yarn should be fetched when the container is built.

**Comment by dfreilich** [comment]
I know that the Paketo buildpacks occasionally dealt with cases where you could request a dependency (for ex., requesting `node` with a .NET Core app). I think that that would be taken care of by buildpacks, however, rather than at the platform level.

**Comment by dfreilich** [comment]
Revisiting this issue, this is a buildpack issue that different buildpack authors/projects can take care of differently. I'll close this here, and I'd recommend reaching out to the communities of the respective buildpacks (at the least, as I mentioned above, I believe that Paketo buildpacks have a method for this) to see how you can accomplish this.
