### ISSUE TITLE
Environment variables not accessible at Runtime

### ISSUE THREAD

**Issue by JakeCooper** [buildpacks/pack#914]
### Summary
Environment variables from buildtime don't seem to be accessible at runtime

### Reproduction
Build a container with `pack build --env "TEST=hello" <app_name>`

Run the container detached

bash echo $TEST

##### Current behavior
empty echo

##### Expected behavior
hello

---

##### pack info
Pack:
  Version:  0.14.2+git-0fd189d.build-1450
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.9.1

Supported Platform APIs:  0.3, 0.4

Config:
  default-builder-image = "[REDACTED]"

##### docker info
lient:
 Debug Mode: false

Server:
 Containers: 17
  Running: 3
  Paused: 0
  Stopped: 14
 Images: 276
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: HSQA:W2D5:CBXJ:6FEZ:QPHC:KIYX:5UCD:JNMA:NC5I:GSJX:UXZ6:DGEX
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 51
  System Time: 2020-10-23T05:20:51.80510667Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by jromero** [comment]
`--env` sets **build-time** environment variables as described in the help message.

```
  -e, --env stringArray             Build-time environment variable, in the form 'VAR=VALUE' or 'VAR'.
                                    When using latter value-less form, value will be taken from current
                                      environment at the time this command is executed.
```

Runtime environment variables can be set by the buildpacks or by the platform running the app image (eg. `docker run --env MYVAR2=foo`).

**Comment by JakeCooper** [comment]
To me, build time variables would be more akin to something like Dockers build time envvars, which can be specified throughout the image lifecycle (into the container lifecycle)

Probably:
* Environment variables passed to the buildpack. Note: These do NOT carry into the container lifecycle.
* Ideally, a method of defining variables which do end up in the image such that they're accessible without having to define them at runtime

**Comment by dfreilich** [comment]
This definitely took longer to check on on than we thought, so sorry for the holdup @JakeCooper ! I'll add in that clarification note to close out this issue. 

Ultimately, the feature definitely makes a lot of sense, but it would require driving an RFC through our RFC process (https://github.com/buildpacks/rfcs/). We may pick that up at some point though, it's a very sensible feature, but we're happy if you want to help/drive that!
