### ISSUE TITLE
pack inspect subcommand

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#920]
### Description

Based on [RFC #58](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md), pack should have a subcommand `inspect`.

### Proposed solution

`pack inspect` should support inspecting any of the following image types:

- app image (produced by CNB)
- builder
- buildpack

If an image is none of the above, it should error out saying that it could not determine the type of image.

_**NOTE: Previous commands should be hidden and if used deprecation warning should be printed.**_

##### Image

```gherkin
Given image X contains label `io.buildpacks.build.metadata`
When user executes `pack inspect X`
Then pack should output the same information as `pack inspect-image X`
```

##### Deprecation

```gherkin
When user executes `pack help`
Then pack output should NOT contain `inspect-image`
```

```gherkin
Given image X contains label `io.buildpacks.build.metadata`
When user executes `pack inspect-image X`
Then pack should output the same information as `pack inspect X`
And pack should output "Warning: inspect-image is deprecated, use inspect instead."
```

##### Image

```gherkin
Given image X contains label `io.buildpacks.builder.metadata`
When user executes `pack inspect X`
Then pack should output the same information as `pack inspect-builder X`
```

##### Deprecation

```gherkin
When user executes `pack help`
Then pack output should NOT contain `inspect-builder`
```

```gherkin
Given image X contains label `io.buildpacks.builder.metadata`
When user executes `pack inspect-builder X`
Then pack should output the same information as `pack inspect X`
And pack should output "Warning: inspect-builder is deprecated, use inspect instead."
```

##### Image

```gherkin
Given image X contains label `io.buildpacks.buildpackage.metadata`
When user executes `pack inspect X`
Then pack should output the same information as `pack inspect-buildpack X`
```

##### File

```gherkin
Given file X is a valid OCI layout tar buildpackage (determined by existence of `/oci-layout`)
When user executes `pack inspect X`
Then pack should output the same information as `pack inspect-buildpack X`
```

##### Deprecation

```gherkin
When user executes `pack help`
Then pack output should NOT contain `inspect-buildpack`
```

```gherkin
Given image X contains label `io.buildpacks.buildpackage.metadata`
When user executes `pack inspect-buildpack X`
Then pack should output the same information as `pack inspect X`
And pack should output "Warning: inspect-buildpack is deprecated, use inspect instead."
```

#### Unknown

```gherkin
Given image X does not container label `io.buildpacks.build.metadata` OR `io.buildpacks.builder.metadata` OR `io.buildpacks.buildpackage.metadata`
When user executes `pack inspect X`
Then pack should error
And pack should output "unable to determine image type of image X."
```

### Additional context

Relates to: https://github.com/buildpacks/pack/issues/597
Relates to: https://github.com/buildpacks/rfcs/pull/93 ([RFC](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md))

**Comment by dfreilich** [comment]
One side-effect of making this a common entrance (i.e. having one command, `pack inspect`, which will inspect builders, buildpacks, and CNB built images), is that we also have to figure out what to do with flags. Currently:

`inspect-image` has 1 flag:
* `--bom`

`inspect-buildpack` has 2 flags:
* `--depth`
* `--registry`

`inspect-builder` has 2 flags:
* `--depth`
* `--output`

What should we do, with a single `inspect` command? `--output` makes sense to apply to all of 3 of them, but `--depth`, `--registry` and `--bom` seem to be restricted to the commands they currently apply to. Should we list them as flags, with the restrictions that they only work for certain types of artifacts? Or is it better to have `inspect` be a command with 3 different subcommands, like we did with most of the other stories in #597 ?

**Comment by dfreilich** [comment]
Should we first proceed with renaming the three subcommands (making it `pack inspect image`, `pack inspect buildpack`, and `pack inspect builder`) to follow the pattern that the other resource based subcommands follow, and punt on combining it all into one inspect command? Or should we resolve the above questions?

**Comment by jromero** [comment]
> Should we first proceed with renaming the three subcommands (making it `pack inspect image`, `pack inspect buildpack`, and `pack inspect builder`) to follow the pattern that the other resource based subcommands follow, and punt on combining it all into one inspect command? Or should we resolve the above questions?

It's a good goal to have a single `inspect` command but as you've mentioned there are some complexities. I would agree that going with individual resource specific subcommands would be a good first step. The challenge would be "image". Image/app/project is a current point of contention. What if we had...?

- `pack buildpack inspect <buildpack-uri>` - inspect a buildpack
- `pack builder inspect <builder-image>` - inspect a builder
- `pack inspect <app-image>` - inspect an app image

**Comment by dfreilich** [comment]
Thinking about it, I'm of two minds about that UX – it definitely makes sense, but I'm also uncomfortable with the `pack inspect <app-image>`, because that could confuse users. I was also thinking about `pack build inspect <app-image>`, to inspect a result of a build, but I'm not sure if I love it either.

**Comment by dfreilich** [comment]
Ultimately, I don't think that it should hold this release – it's a relatively small aspect, and I'd rather we not rush it out the door, and think about what the best UX is.

**Comment by dfreilich** [comment]
@jromero What do you think of doing
* `pack buildpack inspect <buildpack-uri>` - inspect a buildpack
* `pack builder inspect <builder-image>` - inspect a builder
and leaving `pack inspect-image`, to make it clear for users? Once we'd be leaving it top-level, I don't see much of a point in renaming it `pack inspect`, especially since that would make users think that they could inspect all CNB artifacts.

**Comment by jromero** [comment]
@dfreilich I like it and falls inline with the original intent of the RFC. 

The only thing I would do is argue that `pack inspect-image` is no more disambiguous than `pack inspect` since any of the CNB resources can be "images" and we don't use the term `image` in any other reference. 

I would vote for us to rename `pack inspect-image` to simply `pack inspect` to have a clearer story when talking about [app/project/image actions](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md#app--project--image-images-commands). This way any top-level command is acted upon app/project/image and likely targets the same persona (app developer).

ie.

```
pack
   build - build an app/project/image
   inspect - inspect an app/project/image
   rebase - rebase an app/project/image
```
