### ISSUE TITLE
pack config trusted-builders subcommands

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#921]
### Description

Based on [RFC #58](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md), pack should have a subcommand `config trusted-builders`.

### Proposed solution

The following existing commands should be mapped accordingly with all options preserved.

* `pack trust-builder ...` -> `pack config trusted-builders add ...`
* `pack untrust-builder ...` -> `pack config trusted-builders remove ...`
* `pack list-trusted-builders ...` -> `pack config trusted-builders list ...`
* `pack config trusted-builders` (without args) should be aliased to `pack config trusted-builders list`

_**NOTE: Previous commands should be hidden and if used deprecation warning should be printed.**_

### Additional context

Relates to: https://github.com/buildpacks/pack/issues/597
Relates to: https://github.com/buildpacks/rfcs/pull/93 ([RFC](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md))

**Comment by GGSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
