### ISSUE TITLE
pack config registries subcommands

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#923]
### Description

Based on [RFC #58](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md), pack should have a subcommand `config registries`.

### Proposed solution

The following existing commands should be mapped accordingly with all options preserved.

* `pack add-buildpack-registry ...` -> `pack config registries add ...`
* `pack list-buildpack-registries ...` -> `pack config registries list ...`
* `pack config registries` (without args) should be aliased to `pack config registries list`
* Implement new `pack config registries remove ...`

_**NOTE: Previous commands should be hidden and if used deprecation warning should be printed.**_

### Additional context

Relates to: https://github.com/buildpacks/pack/issues/597
Relates to: https://github.com/buildpacks/rfcs/pull/93 ([RFC](https://github.com/buildpacks/rfcs/blob/main/text/0058-pack-subcommands.md))

**Comment by GG-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by jromero** [comment]
Hi @GG-Sheridan,

I would say that this issue is very suitable to be a good first issue but I would personally add more information to make it easier to pick up. That's probably an opinion based on the target audience (ie. dev experience, familiarity with the project).

Our project has some guidelines on [creating good first issues](https://github.com/buildpacks/community/blob/main/contributors/triage.md#good-first-issues) and typically we would add acceptance criteria so that the contributor knows _exactly_ what to expect as the outcome of the change.

Your project seems very promising, if at least for us to identify issues that _could_ be good first issues if we added a little more context/expectation.

**Comment by dfreilich** [comment]
Open question: 
What should `pack set-default-registry` change to?
* `pack config registries default [--set|--unset]`
* `pack config default-registry [--set|--unset]`
?

**Comment by dfreilich** [comment]
Given that `pack add-registry` has a `--default` flag that allows you to set it as default, I feel like it would be best served under `registries`
