### ISSUE TITLE
Rust is not supported even though I have seen it mentioned

### ISSUE THREAD

**Issue by thedewpoint** [buildpacks/pack#930]
Running pack against a rust project yields this result
```

 │ 2020/10/29 22:30:50.979025 DEBUG:  Pulling image buildpacksio/lifecycle:0.9.2
 │ 0.9.2: Pulling from buildpacksio/lifecycle
 │ Digest: sha256:845a165fa064a589887dd22fa1587ae7daf62c8e6589a04c1689b35d0c7cd572
 │ Status: Image is up to date for buildpacksio/lifecycle:0.9.2
 │ 2020/10/29 22:30:52.397286 DEBUG:  Using build cache volume pack-cache-93c0be5a1
 │ 0ce.build
 │ 2020/10/29 22:30:52.397335 INFO:   ===> DETECTING
 │ [detector] ERROR: No buildpack groups passed detection.
 │ [detector] ERROR: Please check that you are running against the correct path.
 │ [detector] ERROR: failed to detect: no buildpacks participating
! failed with status code: 100
dewy@dewyserver:~/expense-api$ ls -ltr
total 76
drwxrwxr-x 2 dewy dewy  4096 Oct 29 22:16 src
-rw-rw-r-- 1 dewy dewy   544 Oct 29 22:16 Cargo.toml
-rw-rw-r-- 1 dewy dewy 65064 Oct 29 22:16 Cargo.lock
-rw-rw-r-- 1 dewy dewy   455 Oct 29 22:29 waypoint.hcl
```

**Comment by jromero** [comment]
Pack itself doesn't support any programming language. It's the buildpacks that provide that support. The buildpacks are typically distributed in [builders](https://buildpacks.io/docs/concepts/components/builder/). When you run `pack build` you either provided a `--builder` option or you set one by default using `pack set-default-builder`.

Doing a quick search I was able to find that the [paketo project](https://paketo.io/) is working on [adopting an existing rust buildpack](https://github.com/paketo-buildpacks/rfcs/pull/25/files?short_path=a24ca38#diff-a24ca387f8c220133edb10f8838a03879d4d53ce328d08ada68acad297cd34d7). You can find the buildpack [here](https://github.com/dmikusa/rust-cnb).

**Comment by thedewpoint** [comment]
thanks @jromero !!
