### ISSUE TITLE
Build JEE Image with Pack

### ISSUE THREAD

**Issue by CodeClinch** [buildpacks/pack#933]
### Summary

I tried to create a image based on java buildpack. But it fails with the following error. 

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:10 min
[INFO] Finished at: 2020-11-02T13:10:10Z
[INFO] ------------------------------------------------------------------------
unable to invoke layer creator
unable to contribute application layer
unable to resolve artifact
unable to find single built artifact in target/*.[jw]ar, candidates: []
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145

---

##### Steps

1. download jee application from internal github
2. pack build espm-web --builder paketobuildpacks/builder:base

##### Current behavior

see error message above

##### Expected behavior

Created image

---

**Comment by jromero** [comment]
Hi @CodeClinch, pack doesn't provide any language support. It only facilitates buildpacks to be executed. It sound like this issue would be more appropriately served by the paketo buildpacks community: https://github.com/paketo-buildpacks/java

**Comment by jromero** [comment]
Redirected to https://github.com/paketo-buildpacks/java/issues/42
