### ISSUE TITLE
Provide git-credential helper available to builders

### ISSUE THREAD

**Issue by shaxbee** [buildpacks/pack#941]
### Description
As a developer I need ability to clone private repository within builder.

### Proposed solution
Provide credential helper that forwards the calls to host credential helper using [git-credential](https://git-scm.com/docs/git-credential).
This could be enabled via feature flag and possible require trusted flag to be set.

### Describe alternatives you've considered
Vendoring dependencies, however developer experience is not great as it requires additional setup.

### Additional context
- [ ] This feature should be documented somewhere

**Comment by dfreilich** [comment]
@shaxbee To clarify the question – You want `pack create-builder` to be able to download packaged buildpacks (in either `tar` or `tgz` format) with secured URLs? Or were you looking for something else?

**Comment by shaxbee** [comment]
@dfreilich I would like the builders to have git credential-helper calls forwarded to host.

**Comment by dfreilich** [comment]
For what purpose? How would that be used?

**Comment by shaxbee** [comment]
@dfreilich builders sometimes need to access private repositories to fetch dependencies, for example Go is doing that

**Comment by dfreilich** [comment]
Ahh ok. I wasn't sure where cloning repositories came in, but using it for dependency management makes sense. Sorry for that back and forth! 

In that case, I would assume that git-credentials would be something that individual builders would need to provide, and as such, you should file a bug on the repo of the builder that you use.

**Comment by shaxbee** [comment]
Understood. Thanks for clarification.
