### ISSUE TITLE
Pack should stop providing default process type `web` by default to the lifecycle

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#946]
### Description

As per https://github.com/buildpacks/rfcs/pull/110, beginning Platform API 0.X ([TBD](https://github.com/buildpacks/spec/issues/160)) pack should no longer pass `-process-type` unless the user provides given value.

> pack stops sending -process-type web when CNB_PLATFORM_API is greater than 0.X. The lifecycle will assume default = true for web processes from buildpacks implementing buildpack APIs earlier than 0.Y. The lifecycle could print an info message when buildpacks do not specify a default process type. -process-type <unknown process type> could then become a failure case (vs. warn, what it is today).

**Comment by samj1912** [comment]
https://github.com/buildpacks/pack/pull/1051 should fix this?
