### ISSUE TITLE
Provide an option to change "CNB_PLATFORM_EXPERIMENTAL_FEATURES" setting

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#947]
### Description

As per https://github.com/buildpacks/rfcs/pull/115, we'll likely want to provide a mechanism to change the ability to tweak the `CNB_PLATFORM_EXPERIMENTAL_FEATURES` setting.

### Proposed solution

A few options:

- Add a flag to build (ie. `--experimental={warn|silent|error}`)
- Add an option to `config.toml` to globally set value
- Roll it up into pack's existing `experimental=true` in `config.toml` to equal "silent" otherwise "error"

### Additional context

We should make sure it's clear, if we separate them, that there is a distinction between pack and lifecycle experimental features.

**Comment by jjbustamante** [comment]
Closing this one, we ended up implementing option 3 with this [PR](https://github.com/buildpacks/pack/pull/984)
