### ISSUE TITLE
Support multiple image tags when using 'pack build'

### ISSUE THREAD

**Issue by anniefu** [buildpacks/pack#990]
### Description
Add multiple image tags to an image produced by 'pack build', for example `:latest` and `:somethingDescriptive`. 

For example, `docker build -t` can be used to [specify an image tag](https://docs.docker.com/engine/reference/commandline/build/#tag-an-image--t), and can be passed multiple times

### Proposed solution
`pack build imageName -t latest -t somethingDescriptive ...` produces imageName:latest and imageName:somethingDescriptive

### Describe alternatives you've considered
Not many, not particularly picky about how it's specified, as long as the functionality is there.

**Comment by dfreilich** [comment]
Hey @anniefu , 

Thanks for the request! It was actually merged in a few days ago from #972, and it will be released when we cut our next release (which I think will be after the holidays). You can use it right now by building `pack` from the main branch.

**Comment by anniefu** [comment]
Awesome, thanks for the update!
