### ISSUE TITLE
Allow global configuration of default pull-policy 

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#991]
### Description
I use `pack` many times per day and I almost always want `--pull-policy if-not-present`. Sometimes I forget to pass this flag and the default behavior clobbers the dev version of a buildpack or builder image I was attempting to use. Appending this flag to every command also make usage of `pack` more cumbersome.

It would be very convenient if I could set this default once in `config.toml`. Then, I would only need to pass the `--pull-policy` flag on the occasions when I _do_ want to pull down the newest version of every image (once a week or so).

### Proposed solution
Add the following option in `config.toml`
```
pull-policy = "<pull policy>"
```

### Describe alternatives you've considered
I considered requesting that pack's default behavior change to `if-not-present` but this might not be best because it could introduce vulnerabilities in cases where pack is used to create production images. Also, this default may not be the most convenient UX for app developers rather than folks like me who use `pack` mainly to develop buildpacks and/or the lifecycle.

### Additional context
- [ ] This feature should be documented somewhere

**Comment by dfreilich** [comment]
I like this a lot, I think it makes sense to allow people to add it to their config with the new `config` subcommand. 

## Acceptance Criteria
The following existing commands should be created
# sets the default pull-policy
pack config pull-policy <if-not-present | always | never>

# unset the default pull-policy
pack config pull-policy --unset

# gets the default pull-policy
pack config pull-policy

This will require parsing that config value at points in our code where we allow users to provide a `pull-policy`.

**Comment by nkuik** [comment]
I've started taking a stab at this (I am new to Go and completely new to this project, so we will see how it goes), and I have a rough implementation, using the new `config` subcommand. However, some questions came up after beginning the task:
1. Should it still be possible to specify `--pull-policy`, in addition to setting the default? And if it should still be an option, I'm guessing it should take precedence over the configured default?
2. `always` is the default pull policy at the moment. If so, should this also be the default if no default is specified in `config.toml` or set by using `pack config pull-policy`?

**Comment by dfreilich** [comment]
Thanks for the help, @nkuik! 

1. Yes, it should still be, similar to how we allow people to override their default builder and run image. 
2. I think it's the first, that it's the default if no default is specified in `config.toml`. We don't currently write default values to `config.toml` unless they are explicitly set (which we'll probably have to revisit at some point, since it's not very intuitive), so I would keep that pattern with pull-policy as well.

**Comment by nkuik** [comment]
Thanks for the answers. They were both in line with my intuition (and what had I gone with in continuing work on the issue), so I hope to have something for review this week.

**Comment by nkuik** [comment]
> Thanks for the answers. They were both in line with my intuition (and what had I gone with in continuing work on the issue), so I hope to have something for review this week.

PR for this has been created [here](https://github.com/buildpacks/pack/pull/1008).
