### ISSUE TITLE
Buildpacks in a Closed Environment

### ISSUE THREAD

**Issue by neilchaudhuri** [buildpacks/pack#997]
I work in an environment that does not have unfettered access to the Internet. However, it is possible to download images and other artifacts for use within our environment.

I was wondering if anyone can provide a pointer to some documentation or case studies or guidance of their own on how we can use Cloud Native Buildpacks in such an environment. 

Thanks.

**Comment by dfreilich** [comment]
Hey @neilchaudhuri ! if you are looking to consume currently available OSS so called 'offline' Cloud Native Buildpacks, I don't know of any open source implementations at the moment, though there are proprietary solutions. (cc @nebhale ). 

If you'd like to learn more about implementing your own, there is an RFC open right now (https://github.com/buildpacks/rfcs/pull/81) for standardizing the structure of an offline buildpack. You can read the current proposal (though it is fairly focused on the layer structure), and participate in the discussion there to learn more.

**Comment by neilchaudhuri** [comment]
Thanks for the information, @dfreilich. I also found information on [bindings and configuration](https://paketo.io/docs/buildpacks/configuration/#building-behind-a-firewall) that could be helpful.

**Comment by abdennour** [comment]
this is highly needed including:
- setting private registry hostname that all cascaded images should pulled from it.
- setting buildconfig files ( settings.xml) so app dependencies also are downloaded from a private repositories.

**Comment by ekcasey** [comment]
> setting private registry hostname that all cascaded images should pulled from it.

I see you have already commented in the thread but I will link [this related issue](https://github.com/buildpacks/pack/issues/821) here for future reference.

> * setting buildconfig files ( settings.xml) so app dependencies also are downloaded from a private repositories.

This features is already implemented by several cloud native buildpack implementations. In [this Paketo example](https://paketo.io/docs/buildpacks/language-family-buildpacks/java/#connecting-to-a-private-maven-repository), a binding is used to provide a `settings.xml` file.

**Comment by abdennour** [comment]
Thank you @ekcasey ! most probably ,this is the exact guide for offline dependencies upload: https://github.com/paketo-buildpacks/samples/tree/main/java/maven

**Comment by stevenkitter** [comment]
So there is no suggestion??
